### PR TITLE
Support local chart app upgrade & rollback

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
- Cannot upgrade local chart app
- Cannot rollback local chart app

**Solution:**
- Input local app templates when upgrading
- Record local app templates in `AppRevision`, restore them into `App` when rollbacking

**Issue:**
#15711

**Related PR:**
- https://github.com/rancher/types/pull/664

### CODE REVIEW

**Comment by gitlawr** [comment]
It doesn't feel right to store template files in app resource, we should check if we can store it in templateVersions like ordinary apps. This consistency helps when we want to move template stuff out of etcd in the future. It could be tricky though since local charts have no externalIds.

**Comment by thxCode** [comment]
Base on https://github.com/rancher/rancher/pull/17278#issuecomment-451096542, this PR only fix the upgradding by local template folder (#15711). I will open another issue to follow the app `rollback` problems.

**Comment by thxCode** [comment]
We cannot agree on whether to continue using `App.Spec.Files` to store "local folder" app files. 

@gitlawr suggest refactoring the logic for local folder installation to store those files into `TemplateContent` to reduce the pressure on etcd (https://github.com/rancher/rancher/issues/14322), and enrich `App.Spec.ExternalID` to support "local folder" app types, then the original upgrade and rollback logic can work both "rancher catalog" and "local folder" apps. 
 
What kind of user will like to use a local folder CVS but not remote CVS or helm repository to manage apps? Is "local folder" app not just for debugging? `TemplateContent` looks like being version control, not content contorl, right ?

**Comment by gitlawr** [comment]
Per the design discussion, we store template files in app/appRevision to support upgrade/rollback. We distinguish local-chart app by empty externalId as it is right now.

**Comment by gitlawr** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
I attempted to rebase in https://github.com/rancher/rancher/pull/18060, but i cannot get a green build. Can you rebase and see what happens for you?

**Comment by thxCode** [comment]
@cjellick , rebased.

**Pull request merged**
