### PR TITLE
Backport: Remove deprecated Fluentd config

### PR DESCRIPTION
**Pull request by kinolaev**
Issue #22320
Original issue #22219
Original PR #21969

### CODE REVIEW

**Comment by kinolaev** [comment]
Hello @aiwantaozi! Can you please take a moment to review this PR?

**Comment by aiwantaozi** [comment]
LGTM

**Comment by kinolaev** [comment]
Thank you @aiwantaozi!
@cjellick, can you please merge this PR? I’m sure it won’t take much of your time)

**Comment by kinolaev** [comment]
Hi @cjellick,
I saw the 2.2.9-alpha release and wanted to remind of this PR that was already approved by your colleague.

**Pull request closed without merging**
