### PR TITLE
Fix harvester cloud credential migration when using non-existent token

### PR DESCRIPTION
**Pull request by jakefhyde**
## Problem

When attempt to migrate existing harvester credentials to add the `rancher.io/expiration-timestamp` annotation, if the cloud credential secret's kubeconfig contains a token which no longer exists, a `NotFound` error will be returned when attempting to get the `v3.Token` object.

## Solution

Ignore not found errors during migrations (note: the error is still valid during a norman Update, since we don't want users to create invalid credentials, but we have no control over whether the token was already removed during migrations).

## Testing

Tested Manually & with unit tests

### Manual Testing

Updated existing unit tests to cover this case

## QA Testing Considerations

N/A

### Regressions Considerations

N/A

Existing / newly added automated tests that provide evidence there are no regressions:
* Updated tests in `store_test.go`

### CODE REVIEW

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
Are there any side effects for the Harvester cloud credential that was skipped during migration due to its use of a non-existent token? One clear side effect is that the UI will not be able to easily display the expiration time according to https://github.com/rancher/dashboard/issues/11332

**Comment by jakefhyde** [comment]
> Are there any side effects for the Harvester cloud credential that was skipped during migration due to its use of a non-existent token? One clear side effect is that the UI will not be able to easily display the expiration time according to [rancher/dashboard#11332](https://github.com/rancher/dashboard/issues/11332)

The alternative is Rancher crashloops, and I don't think we settled on a sentinel time to indicate it already expired.

**Comment by jiaqiluo** [comment]
> > Are there any side effects for the Harvester cloud credential that was skipped during migration due to its use of a non-existent token? One clear side effect is that the UI will not be able to easily display the expiration time according to [rancher/dashboard#11332](https://github.com/rancher/dashboard/issues/11332)
> 
> The alternative is Rancher crashloops, and I don't think we settled on a sentinel time to indicate it already expired.

Crashloop is too bad, and we need to avoid 😆

**Review by jiaqiluo — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Review by m-ildefons — APPROVED** [review]
LGTM, thanks Jake!

**Comment by snasovich** [comment]
Merging as this is a release blocker for 2.9.3

**Pull request merged**
