### PR TITLE
Add ingressClassName support

### PR DESCRIPTION
**Pull request by elmariofredo**

### CODE REVIEW

**Comment by elmariofredo** [comment]
This is still relevant, if anyone cares 🙄

**Comment by aslafy-z** [comment]
@superseb this needs to be merged asap. Can you have a look? Thanks

**Comment by superseb** [comment]
It seems that this will be handled in https://github.com/rancher/rancher/issues/37971, I will let @maxsokolovsky decide what to do with this PR.

**Comment by maxsokolovsky** [comment]
Thanks a lot, @elmariofredo! I have created a separate PR that cherry-picks your commit preserving your authorship, and added a couple of small changes on top of it. Specifically, the default value in `values.yaml` and a description in the chart's README.
https://github.com/rancher/rancher/pull/38202

**Pull request closed without merging**
