### PR TITLE
Remove deprecated Fluentd config

### PR DESCRIPTION
**Pull request by kinolaev**
See https://github.com/rancher/rancher/issues/15880#issuecomment-517671647

Issue:

https://github.com/rancher/rancher/issues/22219

### CODE REVIEW

**Comment by aiwantaozi** [comment]
LGTM

**Comment by aiwantaozi** [comment]
Hi @cjellick Above two configure is for plugin https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter. These two configures are remove since 2.1.x, the latest version is 2.1.6.

Here is the note from fluent-plugin-kubernetes_metadata_filter.
```
NOTE: As of the release 2.1.x of this plugin, it no longer supports parsing the source message into JSON and attaching it to the payload. The following configuration options are removed:

merge_json_log
preserve_json_log

One way of preserving JSON logs can be through the parser plugin
```
If the user still wants to parse the source message info JSON, can use the following ways.
1. Send log to target Fluentd A
2. Parse log inside the target Fluentd A, could use the suggested parser https://docs.fluentd.org/filter/parser, an example
```
<filter foo.bar>
  @type parser
  key_name log
  reserve_data true
  <parse>
    @type json
  </parse>
</filter>
```
3. Target Fluentd A send logs to Elasticsearch/Splunk etc.

**Comment by aiwantaozi** [comment]
Related issue: https://github.com/rancher/rancher/issues/22219

**Comment by kinolaev** [comment]
Thank you @aiwantaozi and @cjellick! What about backport to 2.2? Need I create separate issue and PR for it?

**Comment by aiwantaozi** [comment]
Sure, can you create them? @kinolaev

**Comment by kinolaev** [comment]
Hello @aiwantaozi! Done: issue #22320, PR #22321. Thank you!

**Pull request merged**
