### PR TITLE
Compatible with old fetching UI file logic

### PR DESCRIPTION
**Pull request by orangedeng**
https://github.com/rancher/rancher/issues/19327

### CODE REVIEW

**Comment by alena1108** [comment]
@loganhz @orangedeng can you describe the root cause of the issue we are trying to fix. The thing I want to understand is how it is possible for the user running an official 2.1.7 release, to get a ui-index pointing to the latest rancher.

**Comment by loganhz** [comment]
@alena1108 

> how it is possible for the user running an official 2.1.7 release, to get a ui-index pointing to the latest rancher.

It happens since v2.0.0. Before 2.2, it will always use `local` UI not matter what ui-index is in a release build.

The root cause is Rancher server will update the default setting value during start up. It means the default value for ui-index decided by which rancher container started most recently. Somehow, some 2.1.7 version container started after 2.2.0 version. So it changed the default value of `ui-index` to the latest rancher.

To avoid it, we would like to check if it is a formal release container and if the ui-index is exactly the same with latest rancher UI on CDN. If so, we should use `local` UI.

**Comment by vincent99** [comment]
I don't really like this change; a release pointing at the CDN latest is a perfectly valid and useful value, probably the most common value, and this permanently blacklists it.

Is this really for the edge case of 2.1 -> 2.2 -> 2.1 that one person hit?  Can't they just edit the value?

**Comment by loganhz** [comment]
@vincent99 

> Is this really for the edge case of 2.1 -> 2.2 -> 2.1 -> 2.2 that one person hit? 

No. It's like some rolling update stuff wrong in k8s when they do the upgrade from 2.1 to 2.2.
During the rolling update, 2.1 server starts after 2.2. And 2.1 container get moved by k8s.
I don't know why it happened. 
But @orangedeng noticed this happened in his HA setup and we also have another user has the similar issue https://github.com/rancher/rancher/issues/19213.  I guess we will have more tickets when we make it stable.

> Can't they just edit the value?

Yes, users can just edit it to `local` manually. But I think we will get some tickets make us confused due to this issue. For example, users reported the logging doesn't work in UI. We used 2 QA and few devs to reproduce and investigate it. But we found the root cause is the ui-index. Maybe we can add it into release notes or doc. But I guess it will be a known issue and we always keep it open and always have it in release nodes.

> I don't really like this change; a release pointing at the CDN latest is a perfectly valid and useful value, probably the most common value, and this permanently blacklists it.

`https://releases.rancher.com/ui/latest2/index.html` is changing every day. Every time we merge a PR into master. It will get updated.

I'm not sure how it is useful for users now. Can we push our latest UI to `ui/latest3/index.html` in the feature?  

Given Rancher version is 2.2.2 and users are using latest CDN UI

Case One) If we add a new schema in backend mater branch and we make some change in master UI to support it. Sometimes UI breaks. This happened when we add kontainer-engine into rancher. So users will not be able to create cluster if they are using latest UI but old release version Rancher as backend. 

Case Two) We made some mistake in master UI and it broken.

**Pull request closed without merging**
