### PR TITLE
agent: allow CADVISOR_OPTS/CATTLE_CADVISOR_INTERVAL to be passed

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@Mic92 you can create a file `/var/lib/rancher/etc/agent.conf` on the host with

```
export CATTLE_CADVISOR_INTERVAL=42
```

To address this.  Does that work for you?

**Comment by Mic92** [comment]
Did not now that this is possible, which would take the preference if both values are set?

**Comment by ibuildthecloud** [comment]
The file should take precedence.

**Comment by Mic92** [comment]
Would work for me. Your choice, if you want to provide an additional way or not.

**Comment by ibuildthecloud** [comment]
@Mic92 Just to be clear, I'm saying this works today.  I'm not proposing something different from this PR.

https://github.com/rancher/rancher/blob/6299deb6e2309ce450bf436759fc197b0aadacf6/agent/run.sh#L117

**Comment by Mic92** [comment]
Well, one option could be to pass all variables to the agent starting with "CATTLE_" and then allow them to be overwrited in agent.conf. This way the agent could be configured in a convinient way from with chef, ansible or whatever is orchestration in one flush (by starting the container with a specific environment variable)

**Comment by superseb** [comment]
Thanks for your contribution @Mic92. cAdvisor is superseded by docker stats, this is no longer relevant and alternative is supplied. Please comment if you don't agree, or open a new issue/PR.

**Pull request closed without merging**
