### PR TITLE
Fix bug where clusterAuthToken not being created

### PR DESCRIPTION
**Pull request by StrongMonkey**
There seems to be a regression bug in creating clusterAuthToken when refactoring token code. https://github.com/rancher/rancher/commit/a213e857b2d5d5931ae74804532133140ad8068d#diff-3c5d685b5eb2cef5dc750a2d507238457b6b7f72e0965240f6528c74713453a8L34-R39

It is no longer creating clusterAuthToken due to the new logic.

https://github.com/rancher/rancher/issues/33771

### CODE REVIEW

**Review by dramich — APPROVED** [review]

**Review by rmweir — CHANGES_REQUESTED** [review]
It should be creating it in the api layer https://github.com/rancher/rancher/pull/30853/files#diff-19e1b4bcc3b3129050f1840c3b5afd40923d5e4cfb073cd246da5962bb592ae4R62. This was done due to token hashing. Here is an explanation I wrote for @thedadams awhile ago: `what the handler used to do is it it would get the token and then make a cluster auth token out of it. Now, by this point the token is hashed, so it would just be using the hashed value to create another token which would be incorrect. The cluster auth token then gets hashed, so you end up with this doubled hashed token value. So now the auth token is created when the regular token is created and the raw value is still in memory`.
I'm guessing this doesn't work because steve doesn't use the validators. So we probably need to discuss this further to figure out a solution that will work with token hashing.

**Comment by StrongMonkey** [comment]
@rmweir Ok good to know that I missed this part. Sounds like there is no good way to fix this since it is not possible to know the original token. Maybe we should figure out something otherwise the local auth endpoint feature will likely be broken.

**Comment by dramich** [comment]
@rmweir Should some of your explanation live in that code?

**Comment by cbron** [comment]
@rmweir @StrongMonkey can we close this now ?

**Comment by rmweir** [comment]
@cbron I think so.

**Pull request closed without merging**
