### PR TITLE
[release/v2.4] Vendor rke

### PR DESCRIPTION
**Pull request by PennyScissors**
Issue: https://github.com/rancher/rancher/issues/31223

### CODE REVIEW

**Comment by PennyScissors** [comment]
> We'd need a backport issue for this, right @kinarashah ?

We have one, I linked the wrong one. Thanks for pointing it out @cbron

**Review by cbron — APPROVED** [review]
Seems fine

**Review by superseb — CHANGES_REQUESTED** [review]
We still vendor in `release/v2.4` right?

**Comment by PennyScissors** [comment]
> We still vendor in `release/v2.4` right?

We do, just updated with vendor

**Review by superseb — APPROVED** [review]

**Pull request merged**
