### PR TITLE
Add Istio VirtualService and DestinationRule to Rancher API

### PR DESCRIPTION
**Pull request by gitlawr**
Address issue: https://github.com/rancher/rancher/issues/20894
Depend on types PR: https://github.com/rancher/types/pull/870

Notes:
For project scoped resources we add `projectId` field in API layer in `https://github.com/rancher/norman/blob/master/api/handler/validate.go`. For native kubernetes resources like `service/deployment` apiserver will drop it in deserialization. But for CRDs like Istio resources, it is stored as part of the manifest, and fails the validation from pilot because it is an undefined field. Therefore we update the projectsetter store to drop the `projectId` field. It is unnecessary because the store reads `projectId` from the namespace object.

### CODE REVIEW

**Comment by orangedeng** [comment]
LGTM

**Comment by gitlawr** [comment]
Rebased

Also, encountered a flaky test in CI: https://github.com/rancher/rancher/issues/17567#issuecomment-509885850

**Comment by orangedeng** [comment]
LGTM

**Comment by cjellick** [comment]
merged the types pr. this one is lgtm once types gets updated

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/pull/21484

**Pull request closed without merging**
