### PR TITLE
Corrected kiali path that changed.

### PR DESCRIPTION
**Pull request by floatingman**
## Problem
With the latest Istio chart, the path of Kiali has changed.
 
## Solution
Updated the path of Kiali to the new path
 
## Testing
Ran locally

* Test types added/modified:
    * Validation (Go Framework)

### CODE REVIEW

**Comment by igomez06** [comment]
can you create a forward port PR for v2.8?

**Comment by floatingman** [comment]
Forward port to 2.8 https://github.com/rancher/rancher/pull/42500

**Comment by caliskanugur** [comment]
PR needs a rebase and/or revert

**Comment by floatingman** [comment]
Rebased from release/2.7

**Pull request closed without merging**
