### PR TITLE
[Fix] declare slice with nil

### PR DESCRIPTION
**Pull request by airking05**
Hi,
I have fixed some var declarations.
I would like you to review :smile:

### CODE REVIEW

**Comment by superseb** [comment]
Thanks for the PR, can you rebase?

**Comment by airking05** [comment]
@superseb thanks for your check. I'll do it now.

**Comment by cjellick** [comment]
what does this fix/address?

**Comment by ibuildthecloud** [comment]
@cjellick It's just best practice to use nil instead of a slice of length zero.

**Comment by cjellick** [comment]
yeah, ive been more consistent about using nil lately, I was just curious if there was some nuance I was missing where this had a functional impact

**Pull request merged**
