### PR TITLE
[forwardport] Allow TF to ssh into 22.04 nodes

### PR DESCRIPTION
**Pull request by slickwarren**
## Issue: 

https://github.com/rancher/qa-tasks/issues/505
 
## Problem

rke2 clusters in jenkins fail to create when using ubuntu 22.04 but not other (older) versions. 
upon further investigation, this was due to an incompatibility with TF when sshing into 22.04 node(s)
 
## Solution

created an elliptic-based ssh key in aws to use. 
 
## Testing

tested in jenkins (see thread) and locally

### Regressions Considerations

this PR updates _ALL_ jenkins ssh keys to use the new key. This will require an update in jenkins and all engineers using jenkins to acquire the new key.

### CODE REVIEW

**Review by markusewalker — DISMISSED** [review]
LGTM, thanks @slickwarren. Since this will break workflows, we should hold off on merging until Monday to not cause weekend panic 😄

**Review by Josh-Diamond — COMMENTED** [review]
LGTM ✅ .. Thanks @slickwarren

**Review by Josh-Diamond — APPROVED** [review]
oops. i just left a comment above ^^ 😄 Here's approval

**Review by igomez06 — DISMISSED** [review]
LGTM

**Comment by jameson-mcghee** [comment]
LGTM 👍

**Review by markusewalker — APPROVED** [review]

**Pull request merged**
