### PR TITLE
Changes setting name for kubeconfig TTL.

### PR DESCRIPTION
**Pull request by KevinJoiner**
## Problem
The setting name was misleading
 
## Solution
Update the name.
 
## Testing
Verify endpoints are available for the new name.

### CODE REVIEW

**Review by cbron — APPROVED** [review]
never went live so lgtm

**Review by rmweir — APPROVED** [review]
LGTM

**Comment by rmweir** [comment]
Were docs updated yet?

**Comment by KevinJoiner** [comment]
@rmweir They are in review but have the updated name https://github.com/rancher/docs/pull/4140

**Pull request merged**
