### PR TITLE
Excluded GVK of Logging v1 schemes for projectlogging and clusterlogging

### PR DESCRIPTION
**Pull request by eliyamlevy**
Issue: https://github.com/rancher/rancher/issues/37644

### CODE REVIEW

**Review by superseb — CHANGES_REQUESTED** [review]
Is this a forwardport of https://github.com/rancher/rancher/pull/37181? If so, why are only 2 of the 6 added in this PR?

**Comment by eliyamlevy** [comment]
It's not a forward port but it makes sense to include those as well.

**Review by superseb — CHANGES_REQUESTED** [review]
Now there are 12 ExcludeGVK here and 10 in `release/v2.5`, is `release/v2.5` incomplete?

**Comment by eliyamlevy** [comment]
The two I added are only causing problem in 2.6.x and 2.5.12 as far as the issue goes. Since the chart is deprecated I think it's ok to fix it for the main use case of the customer asking for the fix which is to have it work on the next 2.6 release.

**Comment by eliyamlevy** [comment]
> **Expected Result**
> Be able to work and save existing configs. Logging v1 settings to be visible in the Rancher 2.6.4 UI.

**Comment by eliyamlevy** [comment]
Also for some reason its not showing up on the issue so I'm linking the issue again.

Issue for this PR: [#37644](https://github.com/rancher/rancher/issues/37644)

**Review by superseb — APPROVED** [review]

**Pull request merged**
