### PR TITLE
Support uppercase characters in version strings

### PR DESCRIPTION
**Pull request by stearz**
Added support for uppercase characters in version strings by adding a ToLower in getValidTemplateNameWithVersion

### CODE REVIEW

**Comment by maggieliu** [comment]
related to #19615

**Comment by dramich** [comment]
Thanks @stearz for the fix.

**Comment by harikrishnamopuri** [comment]
in which release this change is available

**Comment by harikrishnamopuri** [comment]
?Please share the release version having this fix ?

**Comment by dramich** [comment]
@harikrishnamopuri It should be in 2.4.4 once that is released.

**Comment by harikrishnamopuri** [comment]
Thanks for reply,
Adding to above fix,  i checked In 2.4.4-rc1 release above issue is resolved. 
But there is a issue related upgrading the app. 
App name  is converting to small letters and it saying release version deleted.

**Comment by brendarearden** [comment]
@harikrishnamopuri the upgrade is completing successfully and then you are seeing that it is deleting the previous release? Is it an app that is already installed prior to upgrading rancher? If you can, will you provide an example of the initial chart name and version (in your repo, not how it looks in rancher) and then what the upgraded chart name and version is so we can continue to troubleshoot this issue.

**Comment by brendarearden** [comment]
@harikrishnamopuri thank you for the additional details! That appears to be the same problem as https://github.com/rancher/rancher/issues/19615#issuecomment-626007957 which we were able to fix with this PR https://github.com/rancher/rancher/pull/27068 - and should be available for you in the next RC to test out.

**Comment by harikrishnamopuri** [comment]
Thanks for reply,
From master branch source code i built docker images and ran rancher server.
Looks like issue is resolved, but not able to show upgrade version available.
simply saying UP to date even though latest version available.
image

**Comment by marinoborges** [comment]
I upgraded to v2.4.4 and the issue persists with catalog URL https://kubernetes-charts.alfresco.com/stable

Screenshot_7
Screenshot_1

**Comment by brendarearden** [comment]
@marinoborges try using v2.4.4-rc3 to test it out, we had to bump all 2.4.4 items to 2.4.5 so the 2.4.4 release does not include this fix

**Comment by marinoborges** [comment]
When I search for rancher in the helm repo, the last version is shown as 2.4.4. See:

root@rancher:~# helm repo list && helm repo update && helm search repo rancher
NAME            URL
rancher-stable  https://releases.rancher.com/server-charts/stable
alfresco-stable https://kubernetes-charts.alfresco.com/stable
rancher-latest  https://releases.rancher.com/server-charts/latest
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "alfresco-stable" chart repository
...Successfully got an update from the "rancher-stable" chart repository
...Successfully got an update from the "rancher-latest" chart repository
Update Complete. ⎈ Happy Helming!⎈
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
rancher-latest/rancher  2.4.4           v2.4.4          Install Rancher Server to manage Kubernetes clu...
rancher-stable/rancher  2.4.4           v2.4.4          Install Rancher Server to manage Kubernetes clu...

**Comment by brendarearden** [comment]
@marinoborges only alpha release are available in the helm repositories - you might still be able to use helm to install the rc by setting the rancher image tag: 
```
helm install --set rancherImageTag=v2.4.5-rc2 rancher rancher-latest/rancher
```
or you can try to use docker for install 
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.4.5-rc2
```

**Comment by brendarearden** [comment]
@harikrishnamopuri thank you for pointing that out - I will be opening another issue to track the fix for that, as it appears to be an existing UI problem. I will mention you on the new issue so you will get updates on its progress.

**Pull request merged**
