### PR TITLE
Change paths of ingressRule from map to slice

### PR DESCRIPTION
**Pull request by orangedeng**
Related issue: https://github.com/rancher/rancher/issues/17065

Related types PR: https://github.com/rancher/types/pull/652

### CODE REVIEW

**Comment by alena1108** [comment]
@orangedeng with the data structure change, would upgrade for existing ingresses work? old way should continue working along with the new one to provide backwards compatibility

**Comment by orangedeng** [comment]
@alena1108 The data structure in k8s ingress object is not changed so the old way will continue working.

**Comment by alena1108** [comment]
@orangedeng the UI would need to change too. Lets not merge this pr till the UI changes are in.

**Comment by kinarashah** [comment]
LGTM, if we're okay with approach of not keeping the user set order intact

**Comment by alena1108** [comment]
@orangedeng @kinarashah the pr's title is not relevant to what we do; it will be just sorting by length instead of changing the type, and would be pulled in via vendor update. In any case, this pr can't be merged till https://github.com/rancher/types/pull/652 is merged.

**Comment by orangedeng** [comment]
Updated.

**Comment by cjellick** [comment]
Waiting on UI to be done so I can coordinate merging, since this breaks the UI https://github.com/rancher/rancher/issues/17529

**Comment by cjellick** [comment]
clsoing in favor of https://github.com/rancher/rancher/pull/17615, which is the same but with updated vendor, so we can get it merged

**Pull request closed without merging**
