### PR TITLE
Drop legacy ownerRefs cleaner controller

### PR DESCRIPTION
**Pull request by moio**
## Issue

#42846
 
## Problem
Handlers `legacy-role-ownerref-cleaner` and `legacy-rolebinding-ownerref-cleaner` fire at every `Role` or `RoleBinding` change, which can be very often (>half million times in a few hours with 1000 RestrictedAdmin users and 3 downstream clusters).
 
## Solution
Drop offending code altogether.

This code existed to correct wrong `onerRefs` created before Rancher 2.4.7:

https://github.com/rancher/rancher/pull/29184/files#diff-aba184f9956e344293abcd7df23de73e81e0ede82a219e15a3c426afb171cc9dR1-R12

Given that support statements require:

1) upgrading to the latest patch version before a minor version:

https://www.suse.com/support/kb/doc/?id=000020727

"All upgrades should go from the latest to the latest. For instance, if you are on 2.5.3, you should go to 2.5.latest and then to 2.6.latest. The stop on 2.5.latest should be about a week to ensure you can catch any issues before moving forward."

2) not skipping minor versions:

https://www.suse.com/support/kb/doc/?id=000020061

"Avoid skipping minor versions when upgrading. For example: when upgrading from v2.4.x -> v2.6.x we encourage upgrading v2.4.x -> v2.5.x -> v2.6.x"

this patch should be very safe. It assumes no user will upgrade from 2.4.6 or earlier to 2.8.0 or later without any version in between.
 
## Testing
Repro in issue

### Manual Testing
Manually tested per issue instructions

### Automated Testing

* If "None" - Reason: code was only removed. No code, no need to test it.
Summary: Nothing to do

## QA Testing Considerations
No particular indication.
 
### Regressions Considerations
No regression expected whatsoever.

### CODE REVIEW

**Comment by moio** [comment]
@rmweir, @MbolotSuse: I took the liberty of asking you for a review, as I believe you might have the right background and visibility to provide quality feedback. Please let me know if for any reason you are not the best person (and ideally who is better suited).

Thank you very much in advance!

**Comment by moio** [comment]
Note: Drone build is failing because of a known flaky test https://github.com/rancher/rancher/issues/43094

**Review by pmatseykanets — DISMISSED** [review]
Seems reasonable 👍 
The build pipeline is failing though. May need to be restarted.

**Review by JonCrowther — DISMISSED** [review]

**Comment by pmatseykanets** [comment]
I assume this will be forward-ported to v2.9, correct?
Ideally, this should've been opened against v2.9 and then back-ported to v2.8.

**Comment by moio** [comment]
You're right - this PR was opened in September 2023, when none of these branches and policies were in place 😇 

I will take care of the ports.

Thanks for the reviews

**Comment by moio** [comment]
Gentlemen I am sorry I forgot this one again, it went stale, and now needs another round of reviews 🤦 

will not happen again

**Review by pmatseykanets — APPROVED** [review]

**Pull request merged**
