### PR TITLE
Okta openldap v2.8 backport

### PR DESCRIPTION
**Pull request by bigkevmcd**
## Issue: 

Backport of #45507 for release/v2.8
 
## Solution

Same as it was for #45507 

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

### CODE REVIEW

**Review by crobby — COMMENTED** [review]
Was the change to test_dns.py intentional here?  It didn't appear in the 2.9 version of this fix.

**Comment by bigkevmcd** [comment]
@crobby I suspect I'll need to forward-port it, it was failing repeatedly during the test run.

**Review by crobby — APPROVED** [review]
lgtm

**Review by andreas-kupries — APPROVED** [review]
lgtm

**Pull request merged**
