### PR TITLE
Add DefaultCatalog setting to control if enable or not

### PR DESCRIPTION
**Pull request by ukinau**
https://github.com/rancher/rancher/issues/15486
From this commit, you can configure default
catalog(https://git.rancher.io/charts.git) is enabled or not by
passing CATTLE_DEFAULT_CATALOG=false environment variable

### CODE REVIEW

**Comment by guangbochen** [comment]
@StrongMonkey can u review the last commit of changing default library settings upon the UI changes.

**Comment by StrongMonkey** [comment]
@guangbochen not sure if we need to support such cases... if the setting only controls whether rancher will create default catalog then the first commit is enough. Then if User want to turn it back, they should turn on the catalog directly, instead of flipping the setting.

**Comment by StrongMonkey** [comment]
if you really need to change that, you might have to watch the setting in a routine where you enable or disable catalog according the value.

**Comment by guangbochen** [comment]
I will make a new PR for supporting the UI changes of defaultCatalog setting, @ukinau can you reset the PR to your origin one, thanks.

**Comment by vincent99** [comment]
Setting this in the UI, and exposing it as an actual setting in the API make no sense.  The point is to have a way to have it never been on in the first place.  If you're already into the UI, just turn it off from the existing screen.

**Comment by ukinau** [comment]
@guangbochen @StrongMonkey 
I reset PR to my original one.  Coud you check it out?

**Comment by ukinau** [comment]
Now some feature (like monitoring) is depended on default catalog, that's why this might cause some confusion, so let me close this PR

**Pull request closed without merging**
