### PR TITLE
Support RKE1 custom clusters and Harvester provisioning

### PR DESCRIPTION
**Pull request by markusewalker**
## Issue: 

[[RKE1] Add support for Harvester for RKE1 cluster provisioning](https://github.com/rancher/qa-tasks/issues/454)

[[RKE1] Create custom_cluster_test.go test case for RKE1 cluster provisioning](https://github.com/rancher/qa-tasks/issues/456)
 
## Problem

As part of the broader effort to have parity between RKE1 and RKE2, there are two additional items that have yet to be implemented:

- Harvester cluster provisioning
- Custom cluster provisioning

Both of these functionalities need to be present to provide additional test coverage, but also to be more on parity with the existing RKE2 tests. This PR addresses both of those and adds the functionality.
 
## Solution

For Harvester support, added the following:

- `tests/framework/extensions/rke1/nodetemplates/harvester/create.go`
- `tests/framework/extensions/rke1/nodetemplates/harvester_config.go`
- New Harvester entry in `tests/framework/extensions/rke1/nodetemplates/nodetemplates.go`
- New Harvester entry in `tests/v2/validation/provisioning/rke1/providers.go`

For custom cluster support, added the following:

- `tests/v2/validation/provisioning/rke1/custom_cluster_test.go`

Additionally, I moved `nodeproviders.go` into the parent directory `provisioning` as now both RKE1 and RKE2 use the file.
 
### Manual Testing

Manually created custom clusters with new `rke1/custom_cluster_test.go` file and created Harvester clusters with `rke1/provisioning_node_driver_test.go` file.

### Automated Testing

Will run Jenkins jobs and pass them to the reviewers offline.

### CODE REVIEW

**Comment by slickwarren** [comment]
just an update: Worked with Markus on Wednesday - still waiting on a jenkins run to finish (probably due to setup taking longer than standard providers)

**Comment by markusewalker** [comment]
As mentioned above, we're working through Jenkins run for Harvester. The custom cluster Jenkins run completes fine, so once I'm able to dive deeper into Harvester environment and fix the Jenkins run, this PR will be good to merge.

**Review by slickwarren — APPROVED** [review]

**Comment by markusewalker** [comment]
@igomez06 everything look all good on your end?

**Review by igomez06 — APPROVED** [review]
Looks good

**Review by igomez06 — APPROVED** [review]

**Pull request merged**
