### PR TITLE
Add environment flags to the test framework

### PR DESCRIPTION
**Pull request by caliskanugur**
**Framework Updates:**

- Implemented:
  - Flags that can be declared within the configuration:
    - Value getter from the environment flags map
    - Map constructor for consistency in the client instantiation
- Refactored:
  - `restConfig` order in the client struct for docs purposes

### CODE REVIEW

**Review by igomez06 — APPROVED** [review]
Looks good Ugur!

**Review by izaac — COMMENTED** [review]
Looks good but could we have if possible a document with examples on how to set these environment flags kind of there's examples for the configuration that @igomez06 written.

**Review by izaac — APPROVED** [review]
LGTM, there's internal documentation for reference now.

**Review by nataliefyi — APPROVED** [review]
LGTM

**Pull request merged**
