### PR TITLE
Fix eks import test

### PR DESCRIPTION
**Pull request by aaronRancher**
Changed the eks_config to remove unnecessary public and private access fields.

### CODE REVIEW

**Review by sowmyav27 — CHANGES_REQUESTED** [review]
`"secretsEncryption": False,` can also be removed
Can you double check what UI is sending while adding an imported cluster?

**Comment by aaronRancher** [comment]
Full EKS config from UI:
```
eksConfig: {amazonCredentialSecret: "cattle-global-data:cc-xlr4z", displayName: "test18643-ekscluster",…}
 amazonCredentialSecret: "cattle-global-data:cc-xlr4z"
 displayName: "test18643-ekscluster"
 imported: true
 region: "us-east-2"
 type: "/v3/schemas/eksClusterConfigSpec"
```
Will delete extra fields in automation eks_config.

**Comment by aaronRancher** [comment]
Updated PR to match EKS config from UI.

**Review by sowmyav27 — APPROVED** [review]
LGTM

**Review by sangeethah — APPROVED** [review]
LGTM

**Pull request merged**
