### PR TITLE
Implement script to list docker images required by infra-services

### PR DESCRIPTION
**Pull request by LLParse**
This script accepts Rancher server version (default: v1.6.2) and
enumerates the docker images by repository/tag needed to run the
infrastructure services for a specific Rancher version.

### CODE REVIEW

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/9189

**Comment by cjellick** [comment]
@LLParse Since this requires python libraries, can you add a `requirements.txt` so that one can run `pip install -r requirements.txt` to install the necessary deps?

**Comment by LLParse** [comment]
@cjellick Good idea, I've added it.

**Comment by cjellick** [comment]
@LLParse I think it makes sense to give its own folder, yes.

**Comment by cjellick** [comment]
Also, can you explain how this differs from what scripts/print-tags.sh outputs? I believe it is different and more useful, but i dont fully understand how/why

**Comment by LLParse** [comment]
@cjellick Moved to a subdir.

The existing script accepts Rancher version and prints out all Docker images in the infra-services folder cached in the `rancher/server:<version>` Docker image. This includes duplicate images and old version image that might not even be available based on Rancher server version filters.

This script accepts Rancher version and computes the Docker images needed to run each infrastructure service based on latest official `rancher-catalog`. It selects the latest catalog version that Rancher will run by default. This is valuable for preparing an air-gap Rancher installation with the latest and greatest services and none of the legacy image bloat.

**Comment by LLParse** [comment]
As I write this, I realize we might want to print out the catalog commit hash. We might also want to parameterize `git.rancher.io/rancher-catalog`.

**Comment by cjellick** [comment]
@LLParse I tried, but I just can't merge python code that so blatantly violates pep8.
Can you add flake8 to requirements.txt, install it, run `flake8 print-catalog-images.py` and address the errors?

Also, that description you wrote is very useful. Can you either cause the program to output it when it is ran or add it as a comment to the program?

**Comment by LLParse** [comment]
@cjellick Here are the requested changes. The description prints when the user requests the help:
```
$ ./print-catalog-images.py -h
usage: print-catalog-images.py [-h] -v VERSION

Computes Docker images required to run each infrastructure service for a
specific Rancher version. This is valuable when preparing an air-gapped Rancher
installation for the latest infrastructure services without legacy image
bloat.

optional arguments:
  -h, --help            show this help message and exit
  -v VERSION, --version VERSION
                        Rancher Server version
```

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
