### PR TITLE
[Alerting]For 2.2: Support set http_proxy config on Rancher notifier

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
Not support http_proxy setting now
Solution:
Add http_proxy configure for slack, pagerduty, wechat, webhook

https://github.com/rancher/rancher/issues/20867

### CODE REVIEW

**Comment by orangedeng** [comment]
LGTM

**Comment by aiwantaozi** [comment]
update error message

**Comment by mrajashree** [comment]
This PR is exactly same as https://github.com/rancher/rancher/pull/20742 except with a commit for the types changes?

**Comment by alena1108** [comment]
@mrajashree : I think it's a backport pr for release/v2.2 branch. The types pr have been merged, @aiwantaozi this pr can be updated

**Pull request merged**
