### PR TITLE
[2.6] Add vsphere node driver provisioning support

### PR DESCRIPTION
**Pull request by markusewalker**
## Problem

Currently, the Go test framework does not have support for the node driver vsphere. As this is used extensively internally and by customers, we need to ensure we are covering support for this node driver.
 
## Solution

Added node driver support for vsphere in RKE1/RKE2/K3S cluster types. This covers only Linux nodes for now as adding Windows support potentially will involve more in-depth refactoring. More investigation is needed before Windows support is provided.
 
### Manual Testing

Manually tested that vsphere node driver clusters provisioned for all supported cluster types.

### Automated Testing

Jenkins runs will be given offline to reviewers.

### CODE REVIEW

**Review by slickwarren — APPROVED** [review]
lgtm

**Review by Josh-Diamond — COMMENTED** [review]
Same comment as mentioned in `v2.7` PR - 

Should we maybe add logging to  `CreateVsphereCloudCredentials()` and `CreateVSphereNodeTemplate()` functions?

Outside of that suggestion, I think everything else looks great and the behavior is as expected. Great Job Markus!

**Review by Josh-Diamond — APPROVED** [review]
Above suggestion is outside scope of this PR. 

Approved ✅

**Review by igomez06 — APPROVED** [review]
Looks good

**Pull request merged**
