### PR TITLE
Change charts branch to dev-v2.8

### PR DESCRIPTION
**Pull request by rohitsakala**

### CODE REVIEW

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
There are more places to be fixed. 
Please check [this comment](https://github.com/rancher/rancher/commit/5e73a2608400cfa4236d8f0d0374503855f2758b) as an example.

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Review by a-blender — COMMENTED** [review]
What about CATTLE_KDM_BRANCH in Dockerfile.dapper? https://github.com/rancher/rancher/blob/bd5b19072d3e4323291a8abfd314cd8c4e5cc469/Dockerfile.dapper#L16

Is that going to be updated in a separate PR?

**Comment by snasovich** [comment]
Is likely superseded by https://github.com/rancher/rancher/pull/42698

**Comment by rohitsakala** [comment]
Closing this as https://github.com/rancher/rancher/pull/42698 has all changes.

**Pull request closed without merging**
