### PR TITLE
Update Nutanix driver to v3.3.0

### PR DESCRIPTION
**Pull request by tuxtof**
update Nutanix Rancher Node driver to v3.3.0

https://github.com/rancher/rancher/issues/39333

### CODE REVIEW

**Review by snasovich — APPROVED** [review]

**Comment by snasovich** [comment]
@tuxtof , thank you for submitting the PR. The changes themselves look good, but we want to hold off merging it after 2.7.0 is out (which is currently in "code freeze" stage). I also see that CI for some reason didn't run and PR is waiting for a passing build.
Could you try force-pushing to retrigger CI?

**Comment by tuxtof** [comment]
Hi @snasovich test seems in progress now

**Comment by HarrisonWAffel** [comment]
Build failure will be addressed by https://github.com/rancher/rancher/pull/39347

**Comment by HarrisonWAffel** [comment]
#39347 has been merged, allowing this PR to pass CI.  @tuxtof please rebase this PR on top of `release/v2.7`, the build will pass on the next try.

**Comment by snasovich** [comment]
@tuxtof , the build is consistently failing on `windows-ltsc2022` step and it looks like it's due to issue with merging `go.mod`. I'm not exactly sure why it's happening, but can you rebase this PR again to see if this resolves the CI issue?

**Review by snasovich — APPROVED** [review]

**Pull request merged**
