### PR TITLE
Adding read-nodes permission to project owner

### PR DESCRIPTION
**Pull request by MbolotSuse**

### CODE REVIEW

**Comment by MbolotSuse** [comment]
Requested by the windows team to help resolve #36432 .

When attempting to exec into a pod, the UI now needs to know if that pod represents a windows container or a linux container. Presumably this is because it needs to know which shell command (`cmd` vs `sh`) to use to exec into the container. @phillipsj correct me if I am wrong there. 

It attempts to do this by looking at the node. Project owners, in the current state, can't see nodes, and as such can't tell if this is a windows/linux container. This adds the permissions to the project owner to see the node, and adds the `node` resource to the list of objects that is created in the `project-owner-promoted` cluster role (i.e. permissions granted by a cluster role binding which represents non-namespaced resources).

The security concern here would be if we want, in the long term, project owners to be able to see nodes.

**Review by phillipsj — APPROVED** [review]
I was close. LGTM!

**Review by rmweir — CHANGES_REQUESTED** [review]
Because of this are project owners privy to the nodes ssh keys or can now do a node exec?

**Comment by MbolotSuse** [comment]
@rmweir 
> Because of this are project owners privy to the nodes ssh keys or can now do a node exec?

I'm not 100% sure what you mean here. 

I think that you were thinking of `node` objects in the `management.cattle.io` api group. This change does not grant access to those resources.

This grants access to node objects in the core api group (i.e. the default node object in k8s). I don't see a ssh key in the [api spec](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/node-v1/) or in an example object. I also don't see how you would exec into a node without the ssh key/ permission to deploy a daemonset - if you could elaborate there I would appreciate it.

**Review by rmweir — APPROVED** [review]

**Comment by MbolotSuse** [comment]
@thedadams One of the questions that came up here was surrounding potential sensitive data in the node objects (keep in mind these are nodes from k8s core api group, not our CRD defined nodes). Would you happen to see any potential issues with giving read (`get`, `list`, `watch`) permissions to project-owners for nodes of clusters that they own projects in?

**Review by thedadams — APPROVED** [review]

**Comment by phillipsj** [comment]
@MbolotSuse I just tested the following and it all now works as expected. I created a project and namespace deploying the 
daemonset we have [here](https://github.com/rancher/windows/blob/main/manifests/workloads/daemonset.yaml). I was able to exec into both OSes with the following account types. 

- exec shell on linux workload:
  - as admin -- pass
  - as standard user, cluster owner -- pass
  - as standard user, project owner -- pass
- exec shell on windows workload:
  - as admin -- pass
  - as standard user, cluster owner -- pass
  - as standard user, project owner -- pass

This a screenshot while being a standard user that is a project owner. The failed node call is now fixed and you can exec into a Windows pod just fine.

image

**Comment by MbolotSuse** [comment]
@phillipsj Ok - looks like we are good on our side from a permissions perspective. I need to run a couple of checks to make sure that this doesn't have any negative side effects, but once I make that confirmation we should be clear to merge this in and close out your issue.

The other thing that we will need to do here is have to docs updated so that people know they need read permissions on nodes if they want to exec into windows pods on those nodes. Not everyone uses the standard RBAC roles so this will need to be published so that people who roll their own RBAC setups can deal with this too.

**Pull request merged**
