### PR TITLE
[Draft][v2.9] Implement new kubectl command function

### PR DESCRIPTION
**Pull request by brudnak**
## Issue: 

Had to make changes to kubectl extension for other issues. Updating where kubectl apply and explain were previously used to the new kubectl command.
 
## Problem

Updated kubectl from apply and explain to a single kubectl command function that can handle any kubectl situation. Also fixed a bug in the previous apply implementation.

## Backports

- https://github.com/rancher/rancher/pull/44608
- https://github.com/rancher/rancher/pull/44609

### CODE REVIEW

**Comment by brudnak** [comment]
using https://github.com/rancher/shepherd/pull/17

**Review by Priyashetty17 — APPROVED** [review]

**Review by Priyashetty17 — CHANGES_REQUESTED** [review]
@brudnak Looks like drone build is failing due to an extra parameter "`bufferSizeStr`" added to the GetPodLogs function in your shepherd PR [shepherd/pull/17](https://github.com/rancher/shepherd/pull/17) that's not provided in the calling function in projects.go:
```
/bin/golangci-lint 115s
745Running: golangci-lint 115s
746tests/v2/validation/projects/projects.go:1: : # github.com/rancher/rancher/tests/v2/validation/projects 386s
747tests/v2/validation/projects/projects.go:108:67: not enough arguments in call to kubeconfig.GetPodLogs 386s
748 have (*rancher.Client, string, string, string) 386s
749 want (*rancher.Client, string, string, string, string) (typecheck)

```
Can you please fix this by modifying projects.go to include the additional parameter in the GetPodLogs function?

**Comment by brudnak** [comment]
Fixed usage of GetPodLogs in project.go. Drone passing now! 😀 Thanks @Priyashetty17

**Review by Priyashetty17 — APPROVED** [review]
lgtm

**Pull request merged**
