### PR TITLE
[2.5] Fix missing handle error cause prometheus-operator dosen't deploy

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
We used to just log error when failed to deploy/withdraw systemMonitor, if it failed to deploy prometheus-operator, no error return cause operator isn't get deployed until next time cluster sync.

Solution:
Return error when failed to deploy/withdraw systemMonitor

Issue:
https://github.com/rancher/rancher/issues/29318

### CODE REVIEW

**Review by orangedeng — DISMISSED** [review]
LGTM

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
left comments on https://github.com/rancher/rancher/pull/30124

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
Needs to be updated to reflect changes in https://github.com/rancher/rancher/pull/30124

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Pull request merged**
