### PR TITLE
Handle CIS rbac as part of CRTB lifecycle, allow cluster-owner users to access cis info

### PR DESCRIPTION
**Pull request by prachidamle**
This is based on @leodotcloud's PR: https://github.com/rancher/rancher/pull/26048

https://github.com/rancher/rancher/issues/25990

Since UI fetches cis scan related information from the API and
the user didn't have privileges, empty data was returned, hence
the drop down was empty.

CIS RBAC is now added as part of crtb lifecycle

### CODE REVIEW

**Comment by cjellick** [comment]
Are these resources "cisconfigs", "cisbenchmarkversions" ever specific to a particular cluster or user or are they always the same for everyone in the cluster? Are they just simply generic configuration data? If so, can we simply add get/list/watch for them to the `"user"` global role? That role already has plenty of permissions somewhat smilar to this (assuming my categorization of these two resources is acurate).
```
		addRule().apiGroups("management.cattle.io").resources("principals", "roletemplates").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("preferences").verbs("*").
		addRule().apiGroups("management.cattle.io").resources("settings").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("features").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("templates", "templateversions", "catalogs").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("clusters").verbs("create").
		addRule().apiGroups("management.cattle.io").resources("nodedrivers").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("kontainerdrivers").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("podsecuritypolicytemplates").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("nodetemplates").verbs("create").
		addRule().apiGroups("*").resources("secrets").verbs("create").
		addRule().apiGroups("management.cattle.io").resources("multiclusterapps", "globaldnses", "globaldnsproviders", "clustertemplaterevisions").verbs("create").
		addRule().apiGroups("project.cattle.io").resources("sourcecodecredentials").verbs("*").
		addRule().apiGroups("project.cattle.io").resources("sourcecoderepositories").verbs("*").
		addRule().apiGroups("management.cattle.io").resources("rkek8ssystemimages").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("rkek8sserviceoptions").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("rkeaddons").verbs("get", "list", "watch")
```

**Comment by cjellick** [comment]
@leodotcloud see my above question (when and if youre up for it)

**Comment by leodotcloud** [comment]
@cjellick Yes, those two resources are generic configs. We can definitely add to the rules to the "User" role.

**Comment by prachidamle** [comment]
Closing in favor of https://github.com/rancher/rancher/pull/26156

**Pull request closed without merging**
