### PR TITLE
Fix go routine leak

### PR DESCRIPTION
**Pull request by rmweir**
## Issue: 

 https://github.com/rancher/rancher/issues/41070

## Problem

Prior, in the case of a timeout the there would be no receiver on
the channel. This would cause the go routine to block.

Demonstration of the issue: https://go.dev/play/p/LZhJ3slW1Xf

## Solution

 Now, closing the channel will signal the go routines completion. This will not
be prevented by the timeout.

Demonstration of the solution. Can swap the timeout to simulate either the scenario where the parent function receives timeout signal first or the scenario where the go function finishes before the timeout: https://go.dev/play/p/H5j2TQGRp_S

### CODE REVIEW

**Review by Oats87 — APPROVED** [review]

**Comment by Oats87** [comment]
@briandowns would you mind giving a look at this? Ricky/I can give you additional context on Slack if you need.

**Comment by briandowns** [comment]
Any value in a context with cancel?

**Comment by rmweir** [comment]
@briandowns I don't think so since there is no place with the interfaces used to pass a context. If I had more direct access to the client without convert I could just set a timeout as well. A context could be used in a similar way to the struct channel but I don't see it having any benefits over the current pattern.

Also for anyone interested I posted go playground links demonstrating the issue and the fix.

**Comment by rmweir** [comment]
Testing steps:
1. install rancher on a cluster
2. provision an aws rke1 cluster or import aws k3s cluster.
3. turn off underlying ec2 nodes by either setting them to sleep or terminating them.
4. wait for cluster to be unavailable in UI
5. swap out rancher server image for `rmweir/rancher:fix-leak-test`
6. wait for a couple minutes or longer.
7. Download leaders logs by going to "View Logs" and then selecting "Download". Must download them as the logs in the UI are trimmed. You can figure out which rancher pod is the leader by looking at the annotation for the `cattle-controllers` configmap in the `kube-system` namespace.
8. Open logs and use ctrl/cmd + f to find occurrences of `callTest do()` and `callTest`. The first should be half the number of the second. If there's a difference of one then it should be that the second is 1 more than the first and the last log with `callTest` suffix was `callTest wait finished due to timeout`.

Explanation: this image is based on https://github.com/rmweir/rancher/commits/fix-leak-test. The logs were added to demonstrate that the go routine will end whether that do() function  finishes before the timeout or after.

**Comment by erkki** [comment]
I'm a little bit confused on how - why this call is running for disconnected clusters and what resource usage, if any, is happening  behind the scenes.

We are planning for a usecase which involves (potentially) thousands of disconnected clusters at edge locations -- is it worth considering context (for resource usage) or something further upstream to try to make sure this code only fires for connected clusters?

**Review by Oats87 — APPROVED** [review]

**Review by maxsokolovsky — APPROVED** [review]
LGTM! Thank you for including the Playground examples!

**Pull request merged**
