### PR TITLE
Add setting to skip hosted cluster chart installation

### PR DESCRIPTION
**Pull request by alexander-demicev**
In the current implementation, it's not possible to install a custom helm chart for hosted providers. When a cluster is created,   helm chart from the upstream repo will be installed.
We need a way to install custom charts that are built for every PR as part of our e2e test suite https://github.com/rancher/aks-operator/blob/master/.github/workflows/e2e.yaml.
Providing an alternative helm chart repository will not work for us. 
This PR adds a new setting for skipping helm chart installation and will be used for development purposes only.

Issue: https://github.com/rancher/highlander/issues/4

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
LGTM

In my opinion, it would also be good to have some notes/documentation explaining how to use/pass it (as we discussed offline, it has to be passed to rancher pod through helm chart [options](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#setting-extra-environment-variables) using `extraEnv` variable)

**Review by mjura — APPROVED** [review]
LGTM, please fix CI

**Comment by furkatgofurov7** [comment]
CI needs to be fixed on this one, I can't re-run it though for some reason, can someone else try?

**Comment by richardcase** [comment]
> The job that fails breaks during the build, it doesn't even start the tests. It's likely not caused by this PR.

The tests are flakey. I had to restart them multiple times to get them green.

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
