### PR TITLE
Update kontainer-engine and change formatter

### PR DESCRIPTION
**Pull request by rmweir**
WIP

Problem: User wants to be able to configure node volume size.

Solution: The latest version of kontainer-engine enables the configuration of
node volume size. Formatter will automatically change values of nil to 20.
Clusters that were created before this commit will not have a value for
nodeVolumeSize in configMap, despite being set to 20 by AWS.

Depends on: https://github.com/rancher/kontainer-engine/pull/118

Issue: #16437

### CODE REVIEW

**Comment by nathan-jenan-rancher** [comment]
LGTM

**Comment by nathan-jenan-rancher** [comment]
LGTM

**Comment by cjellick** [comment]
@rmweir remove `[WIP]` when a PR is ready to go

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
failure is unrelated and is already fixed or being fixed in a different PR

**Pull request merged**
