### PR TITLE
[2.9] Deprecate `rancher/aws-iam-authenticator` over upstream

### PR DESCRIPTION
**Pull request by pjbgf**
Rancher's fork of `aws-iam-authenticator` has only [one change](https://github.com/rancher/aws-iam-authenticator/pull/1) over the upstream project. Since the fork was created, a [similar change](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/474) was made upstream for `v0.6.0`, rendering our fork redundant.

This PR bumps the dependency from [v0.5.9 to v0.6.17](https://deps.dev/go/sigs.k8s.io%2Faws-iam-authenticator/v0.5.9/compare?v2=v0.6.17).

### CODE REVIEW

**Review by macedogm — DISMISSED** [review]
LGTM. We also need an approval from @kinarashah, please.

**Comment by pjbgf** [comment]
PR rebased.

**Review by macedogm — DISMISSED** [review]

**Review by kinarashah — DISMISSED** [review]

**Comment by kinarashah** [comment]
Approved but looks like it needs another rebase, conflicting changes in go.mod

**Comment by pjbgf** [comment]
Thank you for the reviews. The PR is now rebased. PTAL.

**Review by macedogm — APPROVED** [review]

**Pull request merged**
