### PR TITLE
Add new feature flag to allow RKE1 UI functionality to be hidden

### PR DESCRIPTION
**Pull request by nwmac**
## Issue: 

#43131
 
https://github.com/rancher/dashboard/issues/9823

## Problem

This PR adds a new feature flag to allow a user to hide the RKE1 functionality in the UI.

## Solution

Simple new feature flag in support of the UI work here - https://github.com/rancher/dashboard/issues/9823 and https://github.com/rancher/dashboard/pull/10056
 
## Testing

Testing will be covered by the UI PR.

### Automated Testing

* Test types added/modified:
    * Unit - UI Unit tests

### Regressions Considerations

None

Existing / newly added automated tests that provide evidence there are no regressions:

See UI tests

### CODE REVIEW

**Review by torchiaf — CHANGES_REQUESTED** [review]
I think you pushed some unrelated changes along with the current one. We only need the new flag in `pkg/features/feature.go` isn't it ?
Otherwise LG

**Comment by nwmac** [comment]
sorry @torchiaf - my bad - updated now

**Review by torchiaf — APPROVED** [review]
LGTM

**Comment by nwmac** [comment]
@prachidamle Could we get a review from someone in backend for this, please? FYI @gaktive

**Review by maxsokolovsky — APPROVED** [review]

**Pull request merged**
