### PR TITLE
Added nanoseconds to project-container

### LINKED ISSUE #29078: Nanoseconds in projectlogging
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Activate Elasticsearch at project level

**Result:**
Log timestamps contain only seconds

**Other details that may be helpful:**
In https://github.com/rancher/rancher/issues/20675 it was fixed for cluster level but when we look at this template it isnt for project level? See https://github.com/rancher/rancher/blob/master/pkg/controllers/managementuser/logging/generator/templatesource.go

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
1.18.6
```

- Docker version (use `docker version`):

```
19.3.11
```

### PR DESCRIPTION
**Pull request by stayfrostnl**
resolves #29078

### CODE REVIEW

**Review by McRonald — DISMISSED** [review]

**Comment by McRonald** [comment]
@phillc @izaac @SvenDowideit we need somebody with write access, please, please, pleeeaasse click the aprove button, fyi @stayfrostnl

**Comment by McRonald** [comment]
@cbron Hey man, can you help us? dateformat pattern does not contain nannoseconds, this commit should fix it.

**Comment by cbron** [comment]
This needs to be rebased against release/2.4 branch in order to go into Rancher 2.4.x. In rancher 2.5 this logging system is deprecated, although we should also open a PR against release/2.5 to add it in there.

**Comment by stayfrostnl** [comment]
@cbron Is there any action required from my side?

**Comment by cbron** [comment]
@stayfrostnl yes can you rebase this against the release/v2.4 branch.

**Comment by stayfrostnl** [comment]
@cbron I create a new pr against the release/v2.4 branch: https://github.com/rancher/rancher/pull/29806. This PR can be closed.

**Pull request closed without merging**
