### PR TITLE
WIP: Alpine Rancher with Lazy Local DB Install

### PR DESCRIPTION
**Pull request by dx9**
Have been hacking around with this setup. Was an experiment that ended up looking like it may be useful. Thought I'd share to see if there's any interest in the approach.

Downloads a bit quicker mostly because the Ubuntu base image is replaced by Alpine's base image. Also no local DB is installed until the container boots. This approach avoids downloading the DB bits until the configured setup is detected (db version / link).

Here are the test containers for anyone interested in taking it for a spin. Included virtual size comparisons, however not apples to apples for server (no DB in image).

rancher/server:v0.27.0-rc1 (501 MB) = dx9err/alpine-rancher-server:v0.27.0-rc1 (189 MB)
rancher/agent:v0.7.10 (372 MB) = dx9err/alpine-rancher-agent:v0.7.10 (113 MB)

Supports running PostgreSQL, currently hits some snags with cattle which was expected.
To try PostgreSQL just use '-e CATTLE_DB_CATTLE_DATABASE=postgres' arg when running the container.

Should be noted that I've taken this as far as "looks like it works". ;)

### CODE REVIEW

**Comment by cjellick** [comment]
Pretty cool @dx9. We've been playing with alpine in a couple other places, so it's cool to see rancher running on it.

I'm not sure if we'll want to switch from ubuntu to alpine because of the warm fuzzies ubuntu gives a lot of users, but its worth looking at.

@cloudnautique you may be interested in this.

**Comment by ibuildthecloud** [comment]
@dx9 This is way too cool :)  I like alpine so I could see us switching, but we have to do a bit more due diligence.  I also like that you have Postgres in there.  Keep this going.

**Comment by cloudnautique** [comment]
This is good stuff!  We are Alpine fans where we can use it. Saw that you had to recompile the websocket-proxy. We are going to start compiling it statically, so that should save some time.

**Comment by dx9** [comment]
@cjellick @ibuildthecloud @cloudnautique Thanks guys for the encouraging feedback. The Alpine + Rancher combo is a saweet mashup for sure. I've had a lot of fun learning Rancher and Alpine.

The static proxy would be great. I'll keep it going and y'all can land it if you decide on it. Also plan on looking into the Postgres Cattle boot issues, more learning required...

**Comment by dx9** [comment]
Hey guys, I've been playing with this a bit more. Want to get some input on a few things.

1 - On Alpine nsenter and socat packages exist. One option is to update the apply logic of agent-binaries to not install on Alpine (would work on ubuntu and alpine envs).

2 - Can we statically link host-api?

3 - Is it a bad idea to mount the docker bin from the host into the agent? Saves some bytes in the agent image.

**Comment by pwFoo** [comment]
> rancher/server:v0.27.0-rc1 (501 MB) = dx9err/alpine-rancher-server:v0.27.0-rc1 (189 MB)
> rancher/agent:v0.7.10 (372 MB) = dx9err/alpine-rancher-agent:v0.7.10 (113 MB)
AS OS I prefer CentOS and also like RancherOS, but Alpine inside a docker container is great

Would like to see server and agent switching to alpine because of size (compared to ubuntu and also centos).

**Comment by andyshinn** [comment]
What is the latest on this? Do you need any assistance on the Alpine side @dx9?

One thing I'd like to point out is that Alpine doesn't query `nameserver` in order or use `search` paths at all in `resolv.conf`. This might not be an issue for Rancher server or agent. But it could be an issue with load balancer images if they search for services by DNS suffix.

**Comment by yunspace** [comment]
@dx9 thanks for this very useful PR. Personally I'm a big fan of alpine and postgresql also. Perhaps this PR can be broken down into a separate alpine and postgresql PRs? Dividing up the changes will probably make it easier for the maintainers to compare and merge.

**Comment by drewblas** [comment]
I too would very much love to see Alpine replace Ubuntu as the base image

**Comment by taketnoi** [comment]
+1 for Alpine to replace Ubuntu base image.

**Comment by ibuildthecloud** [comment]
We at rancher too want to see alpine replace Ubuntu.  We need to add glibc to alpine though which I believe has been accomplished somewhere.  It's just not feasible for use to use musl or statically link for all our software.

Timing wise I don't see us realistically switching for another month or so.

**Comment by frol** [comment]
+1 for Alpine!

@ibuildthecloud Just for your info, while glibc on Alpine is just a workaround, it seems to work fine not only for me, but also for a great number of people using my [`frolvlad/alpine-oraclejdk8`](https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/) (10k pulls) and [`frolvlad/alpine-mono`](https://hub.docker.com/r/frolvlad/alpine-mono/) (3k pulls) (these images are based on [`frolvlad/alpine-glibc`](https://hub.docker.com/r/frolvlad/alpine-glibc/)). In the perfect world, I would suggest you build everything you need for musl libc, but realistically, I can advise you to use [`frolvlad/alpine-glibc`](https://hub.docker.com/r/frolvlad/alpine-glibc/).

**Comment by yunspace** [comment]
I use @frol's `frolvlad/alpine-oraclejdk8` at my current company and also the last company. It's a good stable base image for jvm applications. Highly recommended. And as he suggested, the `glibc` dependency is readily included in `frolvlad/alpine-glibc`

**Comment by SydOps** [comment]
+1 for Alpine base image. 

@frol & @yunspace 
Some information for you about running Oracle java on docker. 
http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/

**Comment by frol** [comment]
@SydOps Yeah, I have already read the article. I will remove my Oracle image if they don't like my free work popularizing their product (I'm not an Oracle fun anyway). BTW, Docker Official Images has been moving to Alpine and [Official Java image already has Alpine-enabled tag](https://hub.docker.com/_/java/), so I would suggest to move there if it is possible and stay with my workaround images until Oracle shuts it down.

**Comment by withinboredom** [comment]
If you're going to build on top of alpine, with docker inside of it, why not just use `FROM docker:latest` (where latest is the actual docker version you want)?

**Comment by frol** [comment]
@withinboredom I guess `docker` image simply didn't exist it the time this PR was introduced. This is the answer to your why. Yet it is a good point that currently `docker` is a better base image.

**Comment by otavio** [comment]
@dx9 did you made more progress here? What is holding up the switch?

**Pull request closed without merging**
