### PR TITLE
adds skip_refresh_on_startup and read_from_head to fluentd collector

### PR DESCRIPTION
**Pull request by rayisbadat**
…f generated fluentd collector config file. https://github.com/rancher/rancher/issues/25048

### CODE REVIEW

**Comment by rayisbadat** [comment]
I was fixated on project logs at the time, but yeah that makes sense to me.

> Why we only add `read_from_head true` in source-project-container section? How about source-container?

**Comment by loganhz** [comment]
Hi @rayisbadat could you rebase it, please? The CI build failed due to the flaky test which has been fixed in `master` now.

**Comment by aiwantaozi** [comment]
Could you check your commit message and update them, describe the problems and solutions. For example: 
Problem: ....
Solution: ...
Issue: ...

And when the refresh is skip in start up, when will the refresh happen?

Rebase master to solve the test failed. Thanks.

**Comment by rayisbadat** [comment]
I wasn't sure what the difference between issue and problem was.  Do u need the commit message modified for both or just the latest?  Wasn't sure how to amend the first commit.

**Pull request merged**
