### PR TITLE
[2.9] Fixes the local upgrade failure

### PR DESCRIPTION
**Pull request by anupama2501**
Back port of https://github.com/rancher/rancher/pull/48292

### CODE REVIEW

**Review by markusewalker — APPROVED** [review]

**Review by markusewalker — COMMENTED** [review]
Looks like there's some conflicting go.sum entries that need to be fixed.

**Review by lscalabrini01 — APPROVED** [review]
LGTM

**Comment by anupama2501** [comment]
> Looks like there's some conflicting go.sum entries that need to be fixed.

@markusewalker resolved the conflicts in go.sum and go.mod

**Review by markusewalker — APPROVED** [review]

**Review by lscalabrini01 — APPROVED** [review]
LGTM

**Pull request merged**
