### PR TITLE
add ingress path+pathType customization to helm chart

### PR DESCRIPTION
**Pull request by SamuZad**
## Problem
Certain load balancers (such as AWS Load Balancer controller or GKE Ingress) require a slightly different path to work with Rancher.
 
## Solution
Making both the path and the pathType customisable via helm values will mean wider compatibility and greater flexibility.
 
## Testing
Having tried the native chart with both AWS Load Balancer controller and GKE Ingress, the ingress returned 404 consistently on the /dashboard/ endpoint.
### Manual Testing
I created a helm installation with the following values:

```
hostname: rancher.mycompany.net
ingress:
  ingressClassName: alb
  includeDefaultExtraAnnotations: false
  extraAnnotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
      alb.ingress.kubernetes.io/target-type: ip
tls: external
```
After deploying, the Rancher dashboard returned 404 while trying to reach via the ingress, but port-forwarding worked flawlessly.

After updating the path of the ingress from "/" to "/*", the dashboard became reachable via the ingress.

This is a small change overall, with the relatively big benefit of making the Rancher chart compatible with 2 major cloud providers' ingress controllers.

### CODE REVIEW

**Comment by SamuZad** [comment]
This is still relevant

**Comment by sadoMasupilami** [comment]
This is very relevant and such an easy change that you should really merge it

**Comment by sadoMasupilami** [comment]
I opened a support ticket with SUSE for this, lets see If that helps :-)

**Review by brandond — APPROVED** [review]

**Comment by SamuZad** [comment]
Is there any way this could be merged before v2.8 gets released? 🙏

**Comment by brandond** [comment]
You'd probably want to rebase against the dev/v2.8 branch, I think that's where all new stuff needs to go first.

**Comment by SamuZad** [comment]
@brandond thank you for your response! I don't see `dev/v2.8`, so I changed my target branch to `release/v2.8`

Let me know if you need anything else from me 🙂

**Review by brandond — APPROVED** [review]

**Comment by SamuZad** [comment]
@brandond sorry to tag you again.. does anything else need to happen to get this merged?

**Comment by brandond** [comment]
Not on your side, no. I'm advocating for it but it might be a bit.

**Comment by gabrielstein** [comment]
Hi team,
2.8 is out[0] and the merge needs an intervention - would that arrives to 2.8?

Thanks!
[0] - https://github.com/rancher/rancher/releases/tag/v2.8.0

**Comment by SamuZad** [comment]
@brandond happy new year! (I think we are still in the window there that's an appropriate greeting)

Any updates on this per chance?

**Comment by sadoMasupilami** [comment]
Hello, is there any plan to merge this in the foreseeable future?

**Review by manuelbuil — APPROVED** [review]

**Review by ericpromislow — APPROVED** [review]
I don't see anything breaking when I run it, and the code makes sense.

Just a note that in the future please choose a branch name that doesn't start with the word "release". Better to submit a PR with a self-descriptive branch name.

**Comment by gaktive** [comment]
I see 3 approvals and since this is an external contribution, if no one objects I can merge.

**Comment by SamuZad** [comment]
> I don't see anything breaking when I run it, and the code makes sense.
> 
> Just a note that in the future please choose a branch name that doesn't start with the word "release". Better to submit a PR with a self-descriptive branch name.

Noted, will do 🙂 

And yay, it's finally merged! It's been a long journey, but eventually got there! Thank you to everyone involved.

Is there an internal process whereby this change will get forward-ported into v2.9, or would a new PR need to be opened?

**Comment by gaktive** [comment]
@SamuZad you can track the forward port in https://github.com/rancher/rancher/issues/44780

Thanks for your contribution!

**Comment by gabrielstein** [comment]
@gaktive HI! would that be ported to 2.9 or do we need a PR for it?

**Comment by gaktive** [comment]
@gabrielstein the forward port target is 2.9.0 (which is what 2.9.next1 maps to in this repo) so whoever works on that can make a new one. I'll defer to the engineer on how they'll do that in #44780

**Pull request merged**
