### PR TITLE
[2.9] Remove all references to github.com/golang/mock/gomock

### PR DESCRIPTION
**Pull request by aruiz14**
## Issue: #47752

Backports #47128

### CODE REVIEW

**Review by JonCrowther — APPROVED** [review]
LGTM, thanks for doing this!

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
Looks good to me! 
Apologies for the delay—I was out of the office last week. 
Could you resolve the conflicts, and I'll review the PR again?

**Comment by snasovich** [comment]
@aruiz14 , are we still planning to merge it to v2.9 given it's past code freeze for v2.9.4 release? Please note we're no longer getting https://github.com/rancher/rancher/pull/47700 into v2.9 for v2.9.4 release (which I believe was a driver behind this change - not sure if it's the only driver).

**Comment by aruiz14** [comment]
> @aruiz14 , are we still planning to merge it to v2.9 given it's past code freeze for v2.9.4 release? Please note we're no longer getting #47700 into v2.9 for v2.9.4 release (which I believe was a driver behind this change - not sure if it's the only driver).

No, I don't plan to merge this until the freeze is lifted. The only exception would be that we needed to bump wrangler for whatever reason, so this changes would be needed too.

**Review by jiaqiluo — DISMISSED** [review]
Good Job! 
LGTM 💯

**Pull request merged**
