### PR TITLE
Backport: Disable Monitoring via detecting Condition

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
Can't completely clean up after disabling cluster monitoring, as the
`MonitoringStatus` may be `nil` before disabling Monitoring operation

**Solution:**
- Detect the status of `MonitoringEnabled` condition
- Fill `MonitoringStatus` before Prometheus ready checking

**Issue:**
https://github.com/rancher/rancher/issues/19666

### CODE REVIEW

**Comment by orangedeng** [comment]
The key problem is that we don't create a `cluster.Status.MonitoringStatus` before the prometheus is ready. The code is in https://github.com/rancher/rancher/blob/master/pkg/controllers/user/monitoring/clusterHandler.go#L105-L115. We should also create that status even prometheus is not ready.

**Comment by orangedeng** [comment]
LGTM

**Comment by alena1108** [comment]
Closing as the commit was incorporated into daily 2.2 cherry-picks pr https://github.com/rancher/rancher/pull/19923

**Comment by loganhz** [comment]
Change is already in 2.2 branch https://github.com/rancher/rancher/blob/release/v2.2/pkg/controllers/user/monitoring/clusterHandler.go#L136

**Pull request closed without merging**
