### PR TITLE
Remove Global DNS

### PR DESCRIPTION
**Pull request by rohitsakala**
Please check the issue for more details...

### Summary 

- Global DNS was deprecated in v2.8.0. Removing the backend codebase related to it.

### CODE REVIEW

**Comment by diogoasouza** [comment]
Should [this](https://github.com/rancher/rancher/blob/f2de3bdd8d8e76892fd3534c1168973ad8710973/tests/integration/suite/test_system_app_creator.py#L12) and [this](https://github.com/rancher/rancher/blob/6e41b09cdc7d42b24c1ecd82f18bfe3efa0bf2a5/tests/v2/validation/publicapi/resources/crds.json#L23) be altered?

**Comment by diogoasouza** [comment]
I think you also need to remove the CRDs you deleted from the list in `pkg/crds/names.go`

**Review by diogoasouza — DISMISSED** [review]

**Review by caliskanugur — APPROVED** [review]
Shepherd bits LGTM

**Review by diogoasouza — APPROVED** [review]

**Review by prachidamle — APPROVED** [review]

**Comment by prachidamle** [comment]
How about the chart or system-chart if present for globalDNS?

**Pull request merged**
