### PR TITLE
Updated apiVersion for ClusterRoleBinding to avoid deprecation warning

### PR DESCRIPTION
**Pull request by dnoland1**
Fix for https://github.com/rancher/rancher/issues/30043

### CODE REVIEW

**Review by nickgerace — APPROVED** [review]
LGTM, but I would like more reviewers to take a look.
Re-ran the CI build too

**Comment by nickgerace** [comment]
It's worth mentioning that https://github.com/rancher/rancher/pull/30585 covers the same change as well.

**Comment by nickgerace** [comment]
Spoke to @dnoland1 and recommended closing this in favor of https://github.com/rancher/rancher/pull/30585.

**Comment by dnoland1** [comment]
Closing in favor of https://github.com/rancher/rancher/pull/30585

**Pull request closed without merging**
