### PR TITLE
Helm-Chart: add support for rancher pod annotations

### PR DESCRIPTION
**Pull request by ChrisNoSim**
For the rancher audit log we need to set some filebeat annotations to the rancher pods. With the current version of the rancher helm-chart this is not possible. So with this small PR we are adding support for custom annotations for the pods (like in other known charts).

Example `values.yaml`:

```yaml
podAnnotations:
  co.elastic.logs.rancher-audit-log/json.add_error_key: 'true'
  co.elastic.logs.rancher-audit-log/json.expand_keys: 'true'
  co.elastic.logs.rancher-audit-log/json.keys_under_root: 'true'
```

On this occasion many thanks to all who have contributed to this useful project. 🚀

### CODE REVIEW

**Review by rd-goran-pulevic — APPROVED** [review]

**Comment by ChrisNoSim** [comment]
What do you guys think about the changes? I would appreciate some positive feedback if you would also find this useful. In any case thanks in advance 🙌

**Comment by ChrisNoSim** [comment]
Any comments please? We really need this :sos:

**Comment by Jono-SUSE-Rancher** [comment]
@aiyengar2 or @prachidamle - Can either of you take a peek at this PR and see about merging it in the future? No promises for v2.6.5 but maybe beyond that.

**Comment by ChrisNoSim** [comment]
Would be very nice to have this in future release 🙏

**Comment by ChrisNoSim** [comment]
Any news on that?

**Comment by ChrisNoSim** [comment]
Can I get any more information so we can merge this change? @prachidamle @aiyengar2 @Jono-SUSE-Rancher

**Review by ppuschmann — APPROVED** [review]

**Comment by tcraxs** [comment]
still relevant to have support for adding custom annotations for the pods

**Comment by beatkind** [comment]
@Jono-SUSE-Rancher could you see if there is any update on this?

**Review by beatkind — APPROVED** [review]

**Comment by Jono-SUSE-Rancher** [comment]
@prachidamle - When you get a free moment can you take a look at this PR or have Arvind take a peek?

**Comment by beatkind** [comment]
This is still relevant

**Comment by beatkind** [comment]
Still relevante

**Comment by beatkind** [comment]
Still relevant

**Comment by beatkind** [comment]
Hey @Jono-SUSE-Rancher any updates here? I know the PR is open for a while now, and it is kind of frustrating.

We are happy to close the PR if this change is not accepted by the project, but we are wondering what's going on, because nothing happend at all.

**Comment by ChrisNoSim** [comment]
Do you plan to merge that in 2023?

**Comment by ChrisNoSim** [comment]
Will close that, because no hope left..

**Pull request closed without merging**
