### PR TITLE
Deprecate helmVersionCommits from v3.Catalog

### PR DESCRIPTION
**Pull request by nickgerace**
Backport of: https://github.com/rancher/rancher/pull/32992
Relevant issue(s):
- https://github.com/rancher/rancher/issues/32938
- https://github.com/rancher/rancher/issues/33156

This was a clean `cherry-pick` of the commit on `master`.

### CODE REVIEW

**Comment by StrongMonkey** [comment]
@nickgerace I see your issue is for v2.6, do you need backport?

**Comment by nickgerace** [comment]
Yes I do for that issue

**Review by StrongMonkey — APPROVED** [review]

**Comment by nickgerace** [comment]
Milestone has changed to 2.5.9 (CC: @cbron).

**Comment by cbron** [comment]
@nickgerace just to confirm, we'll need to merge into both branches for 2.5.9

**Pull request merged**
