### PR TITLE
Bump AgentImage setting to use rancher-agent:v2.7-head

### PR DESCRIPTION
**Pull request by crobby**

### CODE REVIEW

**Review by cbron — DISMISSED** [review]
I think this get's set elsewhere during a tag, but good to update it for head builds.

**Review by maxsokolovsky — APPROVED** [review]
LGTM! Interesting - this whole time it's been a 2.6 tag for 2.7 Rancher, unless overridden by an env var? :)

**Comment by crobby** [comment]
rebased

**Comment by crobby** [comment]
> LGTM! Interesting - this whole time it's been a 2.6 tag for 2.7 Rancher, unless overridden by an env var? :)

Yeah.  I think it does get overridden for any sort of "official" build, but for my local build, it was still getting 2.6 and leaving me wondering why the downstream webhook wasn't getting installed :)

**Pull request closed without merging**
