### PR TITLE
Assign fleet-local/local agentNamespace from helm install

### PR DESCRIPTION
**Pull request by ibuildthecloud**
https://github.com/rancher/rancher/issues/34866

### CODE REVIEW

**Review by nickgerace — COMMENTED** [review]
Is this always going to be the case? Every bootstrap agent will be in this namespace?

**Comment by nickgerace** [comment]
We should also consider adding it here: https://github.com/rancher/rancher/blob/8a9d383baac34a4d518741831f56a64c9d2988bf/pkg/settings/setting.go#L72

**Comment by ibuildthecloud** [comment]
Updated the setting

**Review by StrongMonkey — APPROVED** [review]

**Review by nickgerace — APPROVED** [review]

**Comment by Jono-SUSE-Rancher** [comment]
@nickgerace - Are you allowed/able to merge this for the Harvester team? If not, can we ping someone who can merge it? Caleb maybe?

**Pull request merged**
