### PR TITLE
Bump the rancher/shell image version

### PR DESCRIPTION
**Pull request by maxsokolovsky**

### CODE REVIEW

**Comment by macedogm** [comment]
@maxsokolovsky just to share that rancher/shell updates are done automatically by the Updatecli automation in [rancherlabs/updatecli-automation](https://github.com/rancherlabs/updatecli-automation). See the old PR https://github.com/rancher/rancher/pull/40733 for info and the new ones for this update - https://github.com/rancher/rancher/pull/41476 and https://github.com/rancher/rancher/pull/41475. We can still do the updates manually, but just sharing that the automations can help. If you need any help with this, please let me know.

**Comment by maxsokolovsky** [comment]
@macedogm, thanks for letting me know. I was wondering about that, since I saw via Git blame that the last such update had been done by a bot.

**Review by JonCrowther — APPROVED** [review]

**Review by cbron — APPROVED** [review]
Fine with code change, just 2 additional things: 
1. The first mate for 2.7 q2 needs to ensure this get's un-rc'd. Can you let them know. 
2. We need to figure out QA process around this one

We can merge while those two things happen

**Comment by macedogm** [comment]
Are we also updating v2.6 - https://github.com/rancher/rancher/pull/41475?

**Comment by samjustus** [comment]
#41528

**Pull request merged**
