### PR TITLE
Increase log precision

### PR DESCRIPTION
**Pull request by kinolaev**
Hello!

This PR increases log precision in fluentd config templates.

### CODE REVIEW

**Comment by kinolaev** [comment]
Hello @aiwantaozi! Can you please review this?

**Comment by kinolaev** [comment]
Hello @cjellick! Maybe you can review this PR? Seconds precision is not enough for sorting logs. Interesting that you already use [nanoseconds precisions for rke logs](https://github.com/rancher/rancher/blob/master/pkg/controllers/user/logging/generator/templatesource.go#L9) but not for user's containers. PR #17239 increases precision for project logging but it was lost after you and @aiwantaozi made [logging template refactoring](20243).

In version 2.0 I could just change fluentd configmap, but in version 2.2.3 this configmap periodically replaced with the generated one. So this PR is very important for rancher logging solution.

**Comment by kinolaev** [comment]
Hello @vincent99! Maybe you can review this PR?

**Comment by aiwantaozi** [comment]
LGTM

**Comment by aiwantaozi** [comment]
@loganhz could you help to schedule merge?

**Comment by loganhz** [comment]
Please file an issue first. Thanks!

**Comment by kinolaev** [comment]
Hello @loganhz! You already have issue https://github.com/rancher/rancher/issues/17238 and merged PR https://github.com/rancher/rancher/pull/17239. Need I create another one?

**Comment by kinolaev** [comment]
@loganhz, I filed issue #20405.
It would be cool if you can backport it to 2.2.4 release!

**Comment by loganhz** [comment]
@kinolaev Thanks. Will check with release manger later

**Comment by kinolaev** [comment]
@loganhz do I still have a chance to see it in 2.2.4?)

**Comment by kinolaev** [comment]
Hello!
Another week has passed(
This PR adds only 3 symbols but it brings a big value for your users, because logs with seconds precision is not usable.
Still hope to see it in 2.2.4)

**Comment by cjellick** [comment]
Thanks for the ping @kinolaev. Apologies for the long delay. Unfortunately, this will not make it into v2.2.4. But we can get it backported to the v2.2 branch so that it goes out in the next release.
@loganhz can you have someone open up a backport issue and PR?

**Comment by loganhz** [comment]
Backport issue: https://github.com/rancher/rancher/issues/20675
Backport PR: https://github.com/rancher/rancher/pull/20676

**Pull request merged**
