### PR TITLE
[2.6.4] Support certificate rotation for v2 clusters

### PR DESCRIPTION
**Pull request by paynejacob**
issue: #35343 

# PROBLEM

The certificates on the machines need to be rotated at the user's request.  This may be because they are going to expire or the user has a new CA.  This feature allows users to update all or some of the certificates on their cluster via the rancher API.

# SOLUTION

Using the same certificate rotation object as rke1 clusters You can define what certificates to rotate.  The rotation is controlled by the generation field on the certificate rotation object.  Once certificates have been rotated the controlplane status will be updated with the latest certificate generation.

In my testing I also discovered a bug where clusters would get stuck deleting if they have a bad machine-config.  The fix for this was small and is included in this pr.

# TESTING

- 3 node rke2 cluster with all roles on all nodes
- 3 controlplane, 3 etcd, and 3 worker rke2 cluster

I tested these two cases with node drain enabled and disabled and on k3s clusters as well.

```
kubectl patch -n fleet-default --patch '{"spec":{"rkeConfig":{"rotateCertificates":{"caCertificates":true,"generation":1}}}}' --type=merge cluster/<cluster name>
```

### CODE REVIEW

**Review by jakefhyde — APPROVED** [review]
LGTM

**Review by annablender — APPROVED** [review]
LGTM, long as testing was successful

**Comment by thedadams** [comment]
@paynejacob From these changes, it looks like the cluster/control plane will not have any condition updates to indicate that something is happening with the cluster. Is this the case?

If it is, then I think it would be good to have a way to indicate to the user that certificates are rotating and when rotation is finished.

**Comment by paynejacob** [comment]
Talked about this offline: the cluster goes into an updating state while the plan is applied.

**Pull request merged**
