### PR TITLE
Use positive option instead of negative in cluster logging

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
excludeSystemComponent is a negative field

Solution:
change to includeSystemComponent and use true as default

Issue:
https://github.com/rancher/rancher/issues/15555

Types:
https://github.com/rancher/types/pull/715

### CODE REVIEW

**Comment by orangedeng** [comment]
LGTM, should merge after types PR is merged.

**Comment by alena1108** [comment]
@aiwantaozi is there corresponding UI PR?

**Comment by cjellick** [comment]
Types PR is merged, but once it is merged into rancher, the UI will not function properly. The UI needs updated to use the new property.

**Comment by cjellick** [comment]
closing in favor of https://github.com/rancher/rancher/pull/18025

Also, I opened this UI ticket: https://github.com/rancher/rancher/issues/18026

**Pull request closed without merging**
