### PR TITLE
add option inherit advance from alert group in the alert rule as the default value.

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
both alert group and alert rule advance option is confused, we need to make then simple

Solution:
alert rule use alert group level advance option as default but user can edit if they don't have to inherit from group

Issue:
https://github.com/rancher/rancher/issues/17538
https://github.com/rancher/rancher/issues/15663

Types:
https://github.com/rancher/types/pull/722

### CODE REVIEW

**Comment by aiwantaozi** [comment]
need to work with UI

**Comment by orangedeng** [comment]
LGTM, need rebase.
This PR should be merged after types PR is merged.

**Comment by aiwantaozi** [comment]
Updated.
Changes: update field IsInherited -> Inherited

**Comment by cjellick** [comment]
types merged. please update, then slack me

**Comment by loganhz** [comment]
UI PR is https://github.com/rancher/ui/pull/2693

**Comment by cjellick** [comment]
Lgtm

**Pull request merged**
