### PR TITLE
Hanlding keycloak client uncaught panic. Closes #38683

### LINKED ISSUE #38683: [BUG] Potential panic in keycloakoidc client caused by uncaught error
**Rancher Server Setup**
- Rancher version: v2.6.7
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: no proxy, self-sigend cert

**Describe the bug**
rancher with keycloak auth configured constantly crashes with the following backtrace:
```
2022/08/22 06:35:05 [INFO] Starting management.cattle.io/v3, Kind=SamlToken controller
E0822 06:35:05.202301      52 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 5333 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3f478c0, 0xc005166120})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009088c0})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3f478c0, 0xc005166120})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00537af90, 0x4})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc00260a998, {0xc0019fc6d4, 0x24}, {0xc0019fc6cd, 0xeda95187f}, 0xc006571a40)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xd3
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc00260a95a, 0x5}, {0xc0032e3680, 0x17}}, {{0xc00260a9a0, 0xb}, {0xc00260a960, ...}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2e7
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc00260a95a, 0x5}, {0xc0032e3680, 0x17}}, {{0xc00260a9a0, 0xb}, {0xc00260a960, 0x6}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x10e
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc002c7f780, 0xc001274580)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:256 +0xc08
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc001274580)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc006fc1c30, {0xc00713feb0, 0x0}, 0x696c6163203a656d)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc00274ee10, 0xa}, {0x418c100, 0xc001274580})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00274ee10, 0xa}, {0x4b37fa8, 0xc001274580})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x191
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001064860, {0xc00274ee10, 0x40d214}, {0x4b37fa8, 0xc001274580})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000c17e00, {0xc00274ee10, 0xa}, {0x4b37fa8, 0xc001274580})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000aafc30, {0xc00274ee10, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000aafc30, {0x37c5e40, 0xc0009088c0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000aafc30)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f630febe2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00399f680, {0x4b09600, 0xc0044b6480}, 0x1, 0xc0019d01e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0039a0960, 0x3b9aca00, 0x0, 0xf0, 0xc0039a10e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0039a1680, 0xc0039a1860, 0xc0008fee00)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 5333 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009088c0})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x3f478c0, 0xc005166120})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00537af90, 0x4})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc00260a998, {0xc0019fc6d4, 0x24}, {0xc0019fc6cd, 0xeda95187f}, 0xc006571a40)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xd3
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc00260a95a, 0x5}, {0xc0032e3680, 0x17}}, {{0xc00260a9a0, 0xb}, {0xc00260a960, ...}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2e7
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc00260a95a, 0x5}, {0xc0032e3680, 0x17}}, {{0xc00260a9a0, 0xb}, {0xc00260a960, 0x6}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x10e
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc002c7f780, 0xc001274580)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:256 +0xc08
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc001274580)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc006fc1c30, {0xc00713feb0, 0x0}, 0x696c6163203a656d)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc00274ee10, 0xa}, {0x418c100, 0xc001274580})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00274ee10, 0xa}, {0x4b37fa8, 0xc001274580})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x191
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001064860, {0xc00274ee10, 0x40d214}, {0x4b37fa8, 0xc001274580})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000c17e00, {0xc00274ee10, 0xa}, {0x4b37fa8, 0xc001274580})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000aafc30, {0xc00274ee10, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000aafc30, {0x37c5e40, 0xc0009088c0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000aafc30)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f630febe2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00399f680, {0x4b09600, 0xc0044b6480}, 0x1, 0xc0019d01e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0039a0960, 0x3b9aca00, 0x0, 0xf0, 0xc0039a10e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0039a1680, 0xc0039a1860, 0xc0008fee00)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
```

### PR DESCRIPTION
**Pull request by curlup**
## Problem
Unhandled panic in keycloak client url calculation. 
 
## Solution
Return explicit error, as  function contract allows.

## Testing
Hm, what should i do? 🤔

## Engineering Testing
None done. Pls advise.

Couldn't figure out off the bat:
* which brach / tag I should base this from, please let me know if I need to rebase or something. 
* tests. 
* more intelligent handling (eg support for no `/auth/` prefix, as in keycloak17). 

Happy to do what's needed, please direct me.

### CODE REVIEW

**Comment by MbolotSuse** [comment]
Hey @curlup . Thank you for submitting a PR to fix this issue. To answer your questions:

> which brach / tag I should base this from, please let me know if I need to rebase or something.

`release/v2.6` is the correct branch to base from. This may shift in the near future, if it does I or someone else should let you know here what this changes to.

> tests

As far as automated test goes, I'll provide more guidance on this once we get agreement on the chosen solution, but I think that this code is simple enough that tests would be a good idea here.

As far as manual tests goes, generally speaking it would be a good idea for you to run some basic tests to make sure this has the desired effect. Since this effects the ability to search for users/groups, I would recommend integrating rancher with your keycloak setup and making sure that you can still see users/groups in the search bar when you attempt to add them to clusters/projects.

This also appears to be related to #38480 in the new form.

**Comment by curlup** [comment]
Hi @MbolotSuse

Thanks for your answer!

> As far as automated test goes, I'll provide more guidance on this once we get agreement on the chosen solution, but I think that this code is simple enough that tests would be a good idea here.

Please provide guidance! Dev setup of rancher seems to be a bit complicated for me to grasp on the dot. 

 > As far as manual tests goes, generally speaking it would be a good idea for you to run some basic tests to make sure this has the desired effect. Since this effects the ability to search for users/groups, I would recommend integrating rancher with your keycloak setup and making sure that you can still see users/groups in the search bar when you attempt to add them to clusters/projects.

Oh, I did that in our setup and it is currently working with keycloak as expected. So I'd say manual testing is done? 

> This also appears to be related to #38480 in the new form.

Ah, yes, I added second commit for that. But i'm still not sure if #38480 wants anything more "automatic" in tems of parsing `.well-know` instead of generating this `admin/realms/...` as current code does and this patch too.

**Comment by curlup** [comment]
Actually after double-checking this:
> you can still see users/groups in the search bar when you attempt

doesn't seem to work. Users don't show up, but groups do. Can't quite tell if that's due to our KC setup and is expected behavior or if search doesn't work properly.

**Comment by curlup** [comment]
Hi, it's been two weeks now. Any chance I can get someone's eyes on this?

**Comment by curlup** [comment]
Any word?

**Comment by MbolotSuse** [comment]
@curlup Thank you for the PR. Unfortunately, it currently appears that this change will result in Rancher only supporting newer versions of keycloak (correct me if you disagree). We can't make a breaking change like that, as it would negatively impact our users who are still on older versions. We will need to come up with a solution that allows users on older versions to continue to use the auth provider.

Since these solutions vary in complexity, it will take some time for us to decide on a direction and then provide you with a sufficient outline that allows you to get the PR in a better state. I will reply here once those internal discussions have completed.

**Comment by MbolotSuse** [comment]
@curlup Apologies for the delay. I think we have a path forward here. @cmurphy please feel free to disagree with me if I have said anything that you disagree with.

The strategy that we will want to pursue here is to add a new value to the keycloak auth config called `KeycloakVersion`. Then, the search url will use that version value to determine how to form the url. If the version is higher than or equal to version 17, then it will use the new logic that you have provided. If this value is missing or lower than version 17, it will use the current logic. From what i can see, version 17 appears to be the breakpoint for this (though I'm seeing some conflicting information on the docs side about that). 

Please let me know if you have any questions. I would also ask that you add a quick test of the `getSearchURL` function to ensure that it functions as intended. This test should cover search urls for versions >= 17, versions < 17, and when the version is not specified.

**Comment by tsrats** [comment]
@MbolotSuse Wanted to chime in on your last note about Keycloak version. While I can not contribute to the code, I can give more information on how Keycloak changed.

 It is not a change in version 17, per say, that removed /auth in the URL path. It is the switch from Wildfly (now -legacy) to Quarkus. For what it is worth, Keycloak is still publishing updates with the Wildfly distribution, with the -legacy added for things like Docker containers. So simply basing it on the version will not work. However, as mentioned before, going to the OIDC config at either https://keycloak.domain/auth/realms/<realmname>/.well-known/openid-configuration or https://keycloak.domain/realms/<realmname>/.well-known/openid-configuration will work, and provide the URLs needed for configuring. As you can see though, the Wildfly version for even this has /auth in the path, while the Quarkus version does not. 

Hope this helps.

**Comment by tsrats** [comment]
Ah, I was not aware of the use of the admin rest api in this application. 

Unfortunately I do not have any real experience at this time using the api, but from looking at the URL paths, it seems to be the same idea. Wildfly installs use `https://${hostname}/auth/admin/realms/${realm}` while Quarkus ones use `https://${hostname}/admin/realms/${realm}`. Since even the discovery URL has either `/auth` or not in it, is there the option to instruct the user to provide their discovery URL to Rancher, and then derive all the information from that? It would provide the realm name (after "/realms"), as well as whether it is Wildfly (has "/auth") or Quarkus (no "/auth"). The discovery URL location in the Keycloak admin GUI is the same for both, so the instructions on how to get it would work for either.

Yes, this will break when the user migrates from Wildfly to Quarkus, but basically every client will break because of the URL change, and this is a thing Keycloak has obviously decided was fine for their users. (And why I have both at home, since I do not want to go through the trouble changing a ton of clients haha)

**Comment by MbolotSuse** [comment]
> is there the option to instruct the user to provide their discovery URL to Rancher, and then derive all the information from that?

My objection to this idea is that it introduce more "behind-the-scenes" guessing behavior which can be slippery and imprecise. For example, let's say that the user named the realm `authRancher` - if I look for `/auth` then this condition will fire on both Wildfly and Quarkus. There's ways around this (i.e. looking for very specific items like `/auth/` and checking the index of this in the split url), but this involves tradeoffs and more complex logic that could fail in niche scenarios. I prefer a switch that users can turn on/off that transparently controls rancher's behavior - that way we are always clear on what endpoint rancher is using and why. 

> Yes, this will break when the user migrates from Wildfly to Quarkus, but basically every client will break because of the URL change, and this is a thing Keycloak has obviously decided was fine for their users. 

I'm ok with requiring a change rancher-side when you upgrade/change Keycloak from Wildfly to Quarkus - like you said, there's probably a limit to what we can do to prevent that. Best I think rancher can do here is document that if/when you switch you will need to update certain fields in rancher too.

The thing that I can't do is drop support for the Wildfly distributions entirely - there needs to be a way for users using Keycloak's with that setup to use rancher (and realistically, the default behavior still needs to assume that you are using Wildfly). Basically, if rancher works with Keycloak now, it still should work after this PR.

**Comment by curlup** [comment]
I very much like the discussion, but I disagree with the latest @mbolotsuse statement - on the complex "guessing" logic - It doesn't look that much more complex to split and match differently, and I would not for sure call it guessing - ass there's no well-known discovery for admin rest API in KC.

I can try to come up with an updated pr but I'd very much appreciate some guidance on where to look for how to introduce new user supplied fields (would that be discovery email or KC version) and then how to propagate that to where it is needed for parsing. I can figure it out probably but if someone could point me to analogous fields code, that would help a lot.

**Comment by bpedersen2** [comment]
see #39310 for a fix with compat for  new and old keycloak versions

**Pull request closed without merging**
