### PR TITLE
Gke hosted provisioning

### PR DESCRIPTION
**Pull request by igomez06**
Framework Updates
Implemented helper for provisioning an GKE hosted cluster
Implemented config file read for the particulars of an GKE cluster.

Validation Tests
Implemented simple test for an GKE cluster

### CODE REVIEW

**Review by paynejacob — APPROVED** [review]

**Review by slickwarren — APPROVED** [review]

**Comment by bmdepesa** [comment]
Can we squash the commits?

**Review by slickwarren — APPROVED** [review]

**Review by izaac — COMMENTED** [review]
Is this using the GKEv2 api? or should this also work with GKEv1 on older Rancher versions?

**Comment by izaac** [comment]
> Is this using the GKEv2 api? or should this also work with GKEv1 on older Rancher versions?

Ok this question doesn't apply anymore as 2.5 as well as 2.6 are both using GKEv2. 2.4 is EOL which still used GKEv1

**Review by izaac — APPROVED** [review]
LGTM 🚀

**Pull request merged**
