### PR TITLE
Fix Panic Error Caused by Rancher-Webhook

### PR DESCRIPTION
**Pull request by jiaqiluo**
## Issue: 

https://github.com/rancher/rancher/issues/38701
https://github.com/rancher/rancher/issues/40009
https://github.com/rancher/rancher/issues/39992
 
## Problem

Due to the addition of checks for PSA in rancher-webhook, it does more validations on the request for creating/updating a v3 Management cluster and could return an error if the validation fails.  
Previously, rancher-webhook did not return such an error and rancher also did not catch it, so a panic error did not happen before but happens now. 

## Solution

 
Return the error properly. 

## Testing

Steps:
- create an RKE1 cluster in rancher; during the creation, edit the cluster as YAML and add the following 
```
default_pod_security_admission_configuration_template_name: privileged
```
- update the above cluster to change the template name to an non-existing one 

Expected Results:
The update should fail with an error like the following: 
image

Also, there should be no panic error in rancher's logs. 

### Manual Testing

same as the above
### Automated Testing

n/a 

## QA Testing Considerations

 same as the above
### Regressions Considerations

cluster creation and update

### CODE REVIEW

**Review by kinarashah — DISMISSED** [review]

**Review by cmurphy — CHANGES_REQUESTED** [review]
Could you add the same fix for clustertemplaterevisions

https://github.com/rancher/rancher/blob/28a84c710edf49a4acedfdc3624d427a36124672/pkg/api/norman/store/clustertemplate/store.go#L159

**Comment by jiaqiluo** [comment]
> Could you add the same fix for clustertemplaterevisions
> 
> https://github.com/rancher/rancher/blob/28a84c710edf49a4acedfdc3624d427a36124672/pkg/api/norman/store/clustertemplate/store.go#L159

@cmurphy  Because the rancher-webhook does not validate the `ClusterTemplateRevision`, the panic will not happen when updating a ClusterTemplateRevision. Do you still want me to add the same fix for ClusterTemplateRevision ?

**Comment by cmurphy** [comment]
@jiaqiluo yes, it is still broken in the same way even if it doesn't affect the webhook

**Comment by jiaqiluo** [comment]
Based on the offline discussion with @cmurphy,  the same "error return" is added to the **Create** method for ClusterTemplte for parity with the logic for ClusterStore. However, rancher-webhook does not trigger the panic error when updating Cluster Template.

**Review by cmurphy — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
