### PR TITLE
KEv2 unit tests

### PR DESCRIPTION
**Pull request by annablender**
Issue: https://github.com/rancher/rancher/issues/37818

 
## Problem

Add KEv2 unit tests for cloud providers.
 
## Solution

I wrote KEv2 integration (unit) tests to test code functionality in the rancher/rancher handler for each KEv2 cloud provider (AKS EKS and GKE). The tests are written using the [Go Test Framework](https://pkg.go.dev/testing) and [MockCompose](https://github.com/kelveny/mockcompose). They mock the cluster state and `AKSClusterConfig` objects using test files to simulate reactions to a real cluster, and mock any mockable Interfaces used by the OperatorController. Test files are located in each handler folder and test files are in a `/test` folder in each handler folder. The unit test structure is different from `rancher/rancher/tests` because [Go Test Framework](https://pkg.go.dev/testing) requires test files to be in the same package as the source code.

File structure

```
rancher/rancher
-> pkg/controllers/management/aks
     -> aks_cluster_handler.go
     -> aks_cluster_handler_test.go
     -> tests/
          -> mockdata1.yaml
          -> mockdata2.json
```

## Testing

Git clone rancher/rancher

If you want to test each provider separately

```
go test -v ./pkg/controllers/management/aks
go test -v ./pkg/controllers/management/eks
go test -v ./pkg/controllers/management/gke
```

If you want to run all tests

```
go test -v ./pkg/controllers/management/aks ./pkg/controllers/management/eks ./pkg/controllers/management/gke
```

If you want to check test coverage (current coverage of KEv2: 35.1%, not including mocked sibling funcs so actual coverage is likely around 60-70%)

```
go test (or alias command) -coverprofile=coverage.out
go tool cover -html=coverage.out
```

_Needs backport to 2.6.9_

### CODE REVIEW

**Review by jakefhyde — APPROVED** [review]

**Review by jiaqiluo — APPROVED** [review]

**Review by igomez06 — COMMENTED** [review]
Looks good, but I had a question on the (eks/gke/aks)_cluster_handler_mockc_interface.go files. Is there a need to have multiple implementations of these go mock interfaces? Couldn't you just have on interface definition the different packages would then implement that interface specific to the hosted provider?

**Comment by jakefhyde** [comment]
@annablender Adding to what @igomez06 said, can you add the mock commands somewhere so that they are run as part of `go generate` if they aren't already? If the handler's interface changes it'll be confusing on how to regenerate the mock files.

**Review by igomez06 — APPROVED** [review]
LGTM

**Comment by annablender** [comment]
@jakefhyde and I discussed autogeneration for this unit test PR. We want to autogenerate as much as possible here, but need to do a bit more research on refactoring the mockc so that some of the test functions are created on a `go generate.` That will go into a future improvement PR.

**Pull request merged**
