### PR TITLE
Fix "unknown revision v0.0.0" error caused by the k8s.io/kubernetes module

### PR DESCRIPTION
**Pull request by chiukapoor**
## Issue:
* `go-get` Github action workflow in [rancher/rancher](https://github.com/rancher/rancher/) is failing 
```
go: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

## Problem
* Upstream Issue: https://github.com/kubernetes/kubernetes/issues/79384

## Solution:
* Replace some k8s modules with specific versions to get rid of the "unknown revision v0.0.0" error caused by the k8s.io/kubernetes module in `pkg/apis/go.mod` file.
```
	k8s.io/api => k8s.io/api v0.25.12
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.25.12
	k8s.io/apimachinery => k8s.io/apimachinery v0.25.12
	k8s.io/apiserver => k8s.io/apiserver v0.25.12
	k8s.io/cli-runtime => k8s.io/cli-runtime v0.25.12
	k8s.io/component-base => k8s.io/component-base v0.25.12
	k8s.io/kubectl => k8s.io/kubectl v0.25.12
	k8s.io/pod-security-admission => k8s.io/pod-security-admission v0.25.12
```

### CODE REVIEW

**Comment by snasovich** [comment]
@chiukapoor , could you please provide more context on why this fix is needed? What is that "go-get Github action workflow"?

We've had no issues merging to `release/v2.7` as recent as few days back - https://github.com/rancher/rancher/pull/43029

**Comment by mitulshah-suse** [comment]
@snasovich the automation for fetching the latest rke has been failing. We saw it when we tagged the latest rke tag.
https://github.com/rancher/rancher/actions/workflows/go-get.yml

**Review by snasovich — APPROVED** [review]
Similar change was done for `release/v2.8` a while ago per https://github.com/rancher/rancher/pull/42980 so approving this one too based on the referenced change not knowing to cause issues.

**Review by jiaqiluo — APPROVED** [review]

**Comment by chiukapoor** [comment]
Seems like the fix went in https://github.com/rancher/rancher/pull/42350

**Pull request closed without merging**
