### PR TITLE
Support uppercase characters in helm chart version

### PR DESCRIPTION
**Pull request by stearz**
SemVer supports uppercase characters, so I updated the regex. Would be great if you could merge the pull request as it blocks me from using rancher in production

### CODE REVIEW

**Comment by brendarearden** [comment]
The original error in the related issue `a DNS-1123 subdomain must consist of lower case alphanumeric
characters, '-' or '.', and must start and end with an alphanumeric
character (e.g. 'example.com', regex used for validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]` is an error being thrown by the kubernetes api as the chart is being stored as a kubernetes object for rancher to use - I don't believe this PR will resolve the root cause, but adding a tolower here might be the result we are looking for https://github.com/rancher/rancher/blob/6a60f3386484e841480b3686e2cd6b189fa77b55/pkg/catalog/manager/catalog_common.go#L215 or adding some code here to ensure the version will work as a subdomain in kubernetes 
https://github.com/rancher/rancher/blob/6a60f3386484e841480b3686e2cd6b189fa77b55/pkg/catalog/manager/catalog_preprocess.go

**Comment by stearz** [comment]
I put a `ToLower` in `getValidTemplateNameWithVersion` as there exist other conversions to return a valid label.

**Comment by stearz** [comment]
Is there anything I can do to get this PR merged?

**Comment by brendarearden** [comment]
the root cause will be fixed by the tolower so we should not need to update the regex. Can we get the regex and tests reverted and then commits squashed?

**Comment by maggieliu** [comment]
related to https://github.com/rancher/rancher/issues/19615

**Comment by stearz** [comment]
successor to this PR is here https://github.com/rancher/rancher/pull/26943

**Pull request closed without merging**
