### PR TITLE
[v2.8] Implement new kubectl command function

### PR DESCRIPTION
**Pull request by brudnak**
## Issue: 

Had to make changes to kubectl extension for other issues. Updating where kubectl apply and explain were previously used to the new kubectl command.
 
## Problem

Updated kubectl from apply and explain to a single kubectl command function that can handle any kubectl situation. Also fixed a bug in the previous apply implementation.

### CODE REVIEW

**Comment by brudnak** [comment]
using https://github.com/rancher/shepherd/pull/78

**Review by Priyashetty17 — DISMISSED** [review]
lgtm

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by Priyashetty17 — APPROVED** [review]
lgtm

**Pull request closed without merging**
