### PR TITLE
Ensure cluster controllers are always reenqueued

### PR DESCRIPTION
**Pull request by cmurphy**
Before 23d89f9, when a cluster entered the managementapi user controller, it was guaranteed to enqueue all cluster controllers at the end of the sync unless it encountered an error. With 23d89f9, the sync would exit early in many cases, thereby failing to enqueue the cluster controllers. When a cluster is deleted, one of these cluster controllers is supposed to call Stop on the cluster manager and thereby stop the context, but since this was not always happening, the context sometimes remained running and would mean the healthsyncer controller continued to run and interminably emit errors for the now missing cluster.

This change addresses the problem by adding calls to enqueue the cluster controllers after every success return.

It also prevents reenqueuing nil clusters by copying the cluster objects and never nil-ifying the clusters on errors.

To improve readability and debuggability, all errors returned from the sync method are wrapped, and the private const `_all_` is replaced by the imported `AllKey` from wrangler, to make it clear that this key has meaning to wrangler and is not a random string.

## Problem

The cluster controllers weren't being correctly stopped when a cluster was deleted so one handler that should have stopped was continuing to run and finding the cluster missing.
 
## Solution

Fixed the code that introduced the issue to not short-circuit around enqueuing the controllers that lead to the cluster controllers being stopped.
 
### Manual Testing

Rancher running on a helm install with three control planes. Downstream is a kind cluster, tested versions 1.21.14 and 1.25.2.
Import the cluster, wait for it to  become active. Delete the cluster, and watch for the error log in the rancher logs to appear or not appear.

### Automated Testing

Added unit tests.

## QA Testing Considerations

The code used to specifically handle clusters of version >= 1.25, now it handles clusters of all versions, so both versions < 1.25 and >= 1.25 should be tested.
 
### Regressions Considerations

The code changed is related to this issue: https://github.com/rancher/rancher/issues/40133

### CODE REVIEW

**Review by cbron — COMMENTED** [review]
Lgtm, but what do I know 😄

**Comment by cmurphy** [comment]
Fixed an existing unit test and added new unit tests.

**Review by rmweir — CHANGES_REQUESTED** [review]
What I don't understand is why the enqueue is necessary. The there are multiple places where the controllers can be stopped but one is a lifecycle handler which should run no matter what when a cluster is deleted. I think that is probably only running in the management pod but then I would at least expect 1 pod to not experience this bug which is not what we have observed is it?

**Comment by rmweir** [comment]
There is also a goroutine that should be resyncing every 5 seconds which starts/stop controllers

**Review by rmweir — APPROVED** [review]
Talked offline, LGTM

**Review by maxsokolovsky — APPROVED** [review]

**Pull request merged**
