### PR TITLE
[v2.9] Fix go-get CI and script

### PR DESCRIPTION
**Pull request by chiukapoor**
## Updates
- Add `go generate` step to `go-get` script
- Fix token for PR generation for CI invocation as per https://github.com/rancherlabs/eio/issues/2626#issuecomment-2380066438

## Issue:
- https://github.com/rancher/rancher/issues/47050

### CODE REVIEW

**Review by kinarashah — DISMISSED** [review]

**Review by tashima42 — CHANGES_REQUESTED** [review]
You're missing the id-token permission needed to get secrets from the vault
```diff
permissions:
  contents: write
  pull-requests: write
+  id-token: write
```

**Review by tashima42 — DISMISSED** [review]

**Comment by tashima42** [comment]
Can you also do it on main?

**Review by kinarashah — APPROVED** [review]

**Comment by chiukapoor** [comment]
> Can you also do it on main?

https://github.com/rancher/rancher/pull/47077

**Review by tashima42 — APPROVED** [review]

**Review by tashima42 — CHANGES_REQUESTED** [review]
App not working: https://github.com/rancher/rancher/actions/runs/11117709941/job/30890088813#step:13:132

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
