### PR TITLE
Add integration tests for steve OR and NOT filters

### PR DESCRIPTION
**Pull request by cmurphy**
## Issue:  https://github.com/rancher/rancher/issues/40141

Depends on https://github.com/rancher/steve/pull/76

### CODE REVIEW

**Review by KevinJoiner — DISMISSED** [review]

**Review by igomez06 — DISMISSED** [review]
Looks good. This specific to v2.7 correct?

**Comment by cmurphy** [comment]
Had to add elements of  https://github.com/rancher/rancher/pull/40536 here to run integration tests on local, I misinterpreted https://github.com/rancher/rancher/pull/40310#discussion_r1160782587 and it turns out that causes output.csv to be overwritten with an empty file, which we don't want.

**Review by igomez06 — DISMISSED** [review]
Looks good. For the unwanted empty `output.csv` conditional, will you do a v2.6 PR?

**Comment by cmurphy** [comment]
Good point, yes can do

**Comment by cmurphy** [comment]
I split the local/downstream addition into a separate commit so I could [backport it](https://github.com/rancher/rancher/pull/41184). Also added a commit to make the output testing more flexible, since @rmweir pointed out these don't work on k8s 1.23.

**Review by igomez06 — DISMISSED** [review]
looks good

**Review by KevinJoiner — DISMISSED** [review]

**Review by KevinJoiner — APPROVED** [review]

**Pull request merged**
