### PR TITLE
[Forwardport] [v2.9] Rancher k8s v1.28.6 update

### PR DESCRIPTION
**Pull request by chiukapoor**
## Issue 
* https://github.com/rancher/rancher/issues/43945
 
## Updates
* Bump all Kubernetes libraries to v1.28.x [Jan Patches v1.28.6].
* Update `gnostic` dependencies to `gnostic-models` across the code base. https://github.com/kubernetes/kubernetes/pull/118384
* Implement EachListItemWithAlloc https://github.com/kubernetes/kubernetes/pull/113362 in mockUnstructured struct.
* Bump shell to `v0.1.23`
* Cherry pick b76b7cddc4008febb70632a6e4886aa29a32251d to fix https://github.com/rancher/rancher/issues/45154
* Bump versions to v2.9
  * rke to 1.6.0-rc1
  * kdm to dev-v2.9
  * cli version to v2.9.0-rc1
  * rancher-agent to v2.9

### CODE REVIEW

**Review by jiaqiluo — DISMISSED** [review]
It looks like some changes in the [original PR](https://github.com/rancher/rancher/pull/43652) have been in the release/v2.9 branch, and this PR covers the part that are not.   Also, the etcd version in the release/v2.9 branch is v3.5.12 which is higher than v3.5.9 that is used in the upstream v1.28.6+k3s2, which should be ok.

**Review by kinarashah — DISMISSED** [review]
Need to rebase and update kdm + rke, but rest LGTM. Will reapprove before merge.

**Comment by chiukapoor** [comment]
Successfully tested k8s `v1.28.8` downstream cluster cluster deployment on [rancher v2.9](https://github.com/chiukapoor/rancher/tree/1.28-in-2.9)
image

**Review by jiaqiluo — APPROVED** [review]

**Review by jiaqiluo — DISMISSED** [review]

**Review by snasovich — APPROVED** [review]
Changes look sane to me and given previous approval by @kinarashah and now @jiaqiluo it's good to merge.

**Pull request merged**
