### PR TITLE
[master] Fix Helm changing app answers types

### PR DESCRIPTION
**Pull request by PennyScissors**
Problem:
When we install an app using Helm install, we pass all user provided answers as args to Helm's `--set` which changes will change a value of a quoted string `"true"` to a boolean `true` and break if the app expects a quoted string.

Solution:
Pass the answers that should keep the quoted string type as args to Helm's `--set-string`. Since both changing to the correct type and preserving the value as a quoted string are desirable outcomes depending on the situation, it should be up to the user to decide. For that reason the answers has been split into `answers` (keeps current behavior) and `answersSetString` (keeps its quoted string type). The expectation from the UI perspective is that the user will be able to choose which flag to use (A checkbox next to each answer text field maybe?), and the UI will add the value to the correct map.

Issues: https://github.com/rancher/rancher/issues/26088, https://github.com/rancher/rancher/issues/31109, https://github.com/rancher/rancher/issues/22532

### CODE REVIEW

**Review by StrongMonkey — DISMISSED** [review]
Changes look good to me. Should we use the `answersString` instead? It sounds more straightfoward.

**Comment by PennyScissors** [comment]
> Changes look good to me. Should we use the `answersString` instead? It sounds more straightfoward.

The reason I went for `answersSetString` over `anwersString` is that I named it after the `--set-string` flag rather than the type because `answers` can still take strings so it might be a little misleading. I don't mind changing the name if you think `answersString` is still better though.

**Comment by Jono-SUSE-Rancher** [comment]
@brendarearden, @dramich, @cbron, @PennyScissors - Even if the review for this is good to go, can we please hold off on merging this until we have an opportunity to further consult the UI team on their end, just to ensure proper bandwidth and availability.

**Comment by PennyScissors** [comment]
@Jono-SUSE-Rancher I converted the PR to a draft to prevent it from getting merged in the meantime, but still allow getting it reviewed. Please let me know once it's good to merge.

**Review by brendarearden — APPROVED** [review]
LGTM!!

**Review by dramich — COMMENTED** [review]
@PennyScissors Can you provide an example json blobs where this is used so we can see the difference from an API perspective? 

This will also require CLI and UI changes to support this

**Comment by PennyScissors** [comment]
@dramich 

Example of new behavior:
User input in UI
```
"A"="1"  setString=false
"B"="2"  setString=false
"C"="3"  setString=true
```

Expected json:
```
{
  "answers": {
    "A":"1",
    "B":"2"
  },
  "answersSetString": {
    "C": "3"
  },
  ...
}
```

**Review by dramich — APPROVED** [review]

**Comment by dramich** [comment]
@PennyScissors Can you writeup everywhere this needs to be tested by QA? App, multi-cluster apps, monitoring etc.

**Review by dramich — APPROVED** [review]

**Review by brendarearden — APPROVED** [review]

**Pull request merged**
