### PR TITLE
[Ready For Merge] [2.4.6] Support DingTalk and Microsoft Teams as the notifier

### PR DESCRIPTION
**Pull request by GGGitBoy**
**Problem:**

Microsoft Teams and DingTalk are all very popular IM tools. However, users cannot use them in Rancher out of box.

**Solution:**

AlertManager doesn't support them as a in-tree notifiers.
We can use a generic webhook type alert in AlertManager side and point it to a micro service for redirecting alert requests to Microsoft Teams and DingTalk.
The micro service is responsible for changing the alert payload to fulfill MS Teams' API and redirecting the alert to MS Teams.
Also the micro service will be deployed on demand if there is no Microsoft Teams or DingTalk targets. It will not be deployed.
From Rancher users' perspective, they will be able to use Microsoft Teams and DingTalk out of box just like use other existing notifiers in Rancher UI such as Slack and email.

**Related Issue:**

https://github.com/rancher/rancher/issues/15802
https://github.com/rancher/rancher/issues/19537

**Related PR:**

https://github.com/rancher/ui/pull/4054
https://github.com/rancher/system-charts/pull/263
https://github.com/rancher/types/pull/1167

### CODE REVIEW

**Comment by GGGitBoy** [comment]
rebase

**Comment by maggieliu** [comment]
Hi @GGGitBoy Is it possible to provide QA with a custom build to run the validation test? This can help to speed up the review process.

**Comment by GGGitBoy** [comment]
@maggieliu @guangbochen @loganhz 

1. `docker run -d -e CATTLE_AGENT_IMAGE=dockerrrboy/rancher-agent:alert-enhance -p 443:443 dockerrrboy/rancher:alert-enhance`
2. Set ui-index: https://rancherui.oss-cn-shanghai.aliyuncs.com/ui/jiandao/2.4-fixes/index.html
3. Set system-library: https://github.com/GGGitBoy/system-charts.git. (Branch is `alert-enhance-pr`)
4. Add notifier **dingtalk** and **MicrosoftTeams**
5. Add alert rule and choose recipient **dingtalk** or **MicrosoftTeams**
6. Receive alert message successfully

**Comment by GGGitBoy** [comment]
DingTalk：
image
MicrosoftTeams：
image

**Pull request merged**
