### PR TITLE
WIP: support ARM

### PR DESCRIPTION
**Pull request by imikushin**
Do NOT merge yet, as it installs full Oracle JDK (not JRE) into the ARM image.

### CODE REVIEW

**Comment by imikushin** [comment]
#4703

**Comment by nma** [comment]
trying to replicate and test this out on my pi2, what is the reference to .docker-env.arm ? I can't seem to find it in the builder files.

**Comment by iMartyn** [comment]
I'm having trouble trying this out (size of deployable is not a major issue for me).

It appears that the cattle binaries are not being downloaded, as I get this in the output :
`Step 37 : RUN /usr/share/cattle/install_cattle_binaries &&     cd $CATTLE_HOME && export IFS="," &&     for i in $DEFAULT_CATTLE_CATALOG_URL; do rancher-catalog-service -validate -catalogUrl=$i;done
 ---> Running in 8bb1d344e8be
/tmp/tmp.IFrvScShVG /tmp/extracted_cattle
^[[91m
gzip: stdin: not in gzip format
^[[0m^[[91mtar: ^[[0m^[[91mChild returned status 1
^[[0m^[[91mtar: Error is not recoverable: exiting now^[[0m^[[91m
^[[0m/tmp/extracted_cattle
Archive:  /usr/share/cattle/cattle.jar
`

**Comment by rtis** [comment]
I posted a note a few days ago asking if anyone could give a brief summary of what the state
of an ARM 32 rancher client might be (#9746).  Searched a bit and found this thread.
Is there any good news on this front?  Can I add some effort to help out?
Any thoughts on this topic will be helpful.

Cheers,
Chuck McP

**Pull request closed without merging**
