### PR TITLE
new pipeline for 1903

### PR DESCRIPTION
**Pull request by drpebcak**
Relates to #20804

Needs some more work at the moment - 1903 plugin images need to be built, and we need to spin up 1903 workers.

### CODE REVIEW

**Comment by drpebcak** [comment]
@cloudnautique we just need an updated dapper image added here and then we should be good to go.

**Comment by drpebcak** [comment]
Drone has now been updated, so this can be merged as soon as the dapper plugin gets built.

**Comment by thxCode** [comment]
Steps for building custom rancher/dapper image:
1. Create a 1903 Windows instance on AWS: `ami-031b00caa86f4b96d`
1. Install Git: `iwr -outf git-install.ps1 https://gist.githubusercontent.com/thxCode/cd8ec26795a56eb120b57675f0c067cf/raw/b3cd7c51e76f379cea114c7645f9641400ab648d/git-install.ps1; ./git-install.ps1`
1. Install Golang: `iwr -outf golang-install.ps1 https://gist.githubusercontent.com/thxCode/cd8ec26795a56eb120b57675f0c067cf/raw/b3cd7c51e76f379cea114c7645f9641400ab648d/golang-install.ps1; ./golang-install.ps1`
1. Install Docker: `iwr -outf docker-install.ps1 https://gist.githubusercontent.com/thxCode/cd8ec26795a56eb120b57675f0c067cf/raw/b3cd7c51e76f379cea114c7645f9641400ab648d/docker-install.ps1; ./docker-install.ps1 -Version 18.09`, restarting the instance automatically
1. Download dapper sources via Powershell: `git clone https://github.com/rancher/dapper -b v0.4.2 "$($env:GOPATH)\src\github.com\rancher\dapper"`
1. Build and release dapper image via PowerShell: `pushd "$($env:GOPATH)\src\github.com\rancher\dapper"; .\scripts\windows\release.ps1; popd`

**Comment by drpebcak** [comment]
@thxCode see the error in this build: http://drone-pr.rancher.io/rancher/rancher/3783/4/2

**Pull request merged**
