### PR TITLE
[2.3.2] Add Istio gateway store

### PR DESCRIPTION
**Pull request by gitlawr**
https://github.com/rancher/rancher/issues/20892

Depend on types pr: https://github.com/rancher/types/pull/999

### CODE REVIEW

**Comment by orangedeng** [comment]
Has conflicts, please rebase this PR.

**Comment by alena1108** [comment]
@gitlawr can we add an integration test? As we have a new field, would be nice to cover it with the test.

**Comment by gitlawr** [comment]
Updated

**Comment by gitlawr** [comment]
Rebased

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
