### PR TITLE
<v2.7> Fix Missing Cluster ID Qase test

### PR DESCRIPTION
**Pull request by lscalabrini01**

### CODE REVIEW

**Review by floatingman — APPROVED** [review]
LGTM

**Review by slickwarren — COMMENTED** [review]
this is missing changes to globalroles_v2 test, is that expected?

**Comment by anupama2501** [comment]
globalroles_v2 was introduced in 2.8, so we do not have that test in 2.7 @slickwarren

**Review by slickwarren — APPROVED** [review]

**Review by floatingman — APPROVED** [review]
LGTM

**Pull request merged**
