### PR TITLE
Dont mutate eksv1 subnets

### PR DESCRIPTION
**Pull request by rmweir**
**Problem:**
Prior, if subnets were different an error would be returned. Before v2.5 sending a request with an empty array would result in a nil field. Now it results in an empty array. This is causing the error to return given the same cluster body.

**Solution:**
To prevent field updates sometimes the "noupdate" tag is used. These were not used before because the subnets are in a dynamic config. Now, logic has been added to the cluster store to implement the same behavior as the "noupdate" tag which simply does not mutate its fields value.

**Issue:**
https://github.com/rancher/rancher/issues/28999

### CODE REVIEW

**Review by dramich — CHANGES_REQUESTED** [review]
I think there are a couple of options to address this issue. The most correct would be to add logic [here-ish](https://github.com/rancher/rancher/blob/master/pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go#L178) to check if the driver is EKS and if so set the field update to false. 
Another option would be to extend the `validateEKS` check to see if the len of the subnets is 0, if so return nil. 
My concern with the current fix is we are dropping a field that we say you can update but also provide no error. I think this would be a worse user experience than returning an error on a field we say you can update. I think the best option is fix the schema.

**Comment by rmweir** [comment]
@dramich I understand the concern with the no error behavior but we use the noupdate tag heavily and this is how it behaves. Setting default to false would be the same. I think putting it there would make it harder to fine and confuse someone while debugging.

**Comment by dramich** [comment]
@rmweir But then it's expected behavior. Adding logic to a store to drop a field is not expected and would be much harder to understand vs the schema explicitly stating the field is a no update field. The simplest fix at this point is to just fix the validator and in the interest of time for the release should probably be the path forward.

**Comment by rmweir** [comment]
Closed in favor of https://github.com/rancher/rancher/pull/29092

**Pull request closed without merging**
