### PR TITLE
Improve Alert upgrade

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
1. Project alerting can't show in UI after migrated
2. Need to delete old alertmanager when upgrade rancher

Solution:
1. use clusterName:projectName as projectId
2. we should delete old alertmanager automatically

Issue:
https://github.com/rancher/rancher/issues/17042
https://github.com/rancher/rancher/issues/18007

### CODE REVIEW

**Comment by loganhz** [comment]
What will happen if users downgrade to v2.1? Will the alertmanager will be added back automatically?

**Comment by orangedeng** [comment]
Yes, The controller in v2.1 will add back all the namespace, workload and etc.

**Comment by orangedeng** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
