### PR TITLE
[v2.7] Update TELEMETRY_VERSION to v0.6.2

### PR DESCRIPTION
**Pull request by p-se**
### Receive telemetry reports without cluster logging

https://github.com/rancher/telemetry/pull/83

### Be able to restore data if telemetry stats was offline

https://github.com/rancher/telemetry/pull/84

### Manual Testing

Using the E2E testing framework, I've used `nektos/act` to test the changes locally and ensure data can still be retrieved and reports are still being sent.

### Automated Testing

External tests in rancher/telemetry, see below.

#### Unit Tests

Ensures collector hasn't changed.

https://github.com/rancher/telemetry/pull/85

#### E2E testing

Smoke test to see that telemetry reports can be stored and retrieved.

https://github.com/rancher/telemetry/pull/87

## QA Testing Considerations

- Upgrade as well as new deployments should be unaffected, since the data collected isn't changed. Reports will be sent which previously haven't been sent on clusters which don't have cluster logging enabled, but this change does not affect rancher directly, but the data in the report transmitted to Telemetry Server.
 
### Regressions Considerations

- No API change.

Please let me know if anything is missing.

### CODE REVIEW

**Comment by olblak** [comment]
Reopening this issue, as apparently this should have landed in Rancher 2.7
With Rancher 2.8 coming the current PR may need to be closed

**Comment by l-mb** [comment]
I suggest to close this or directly update to 0.6.2, there's no need to merge 0.6.0 anymore.

**Comment by mattfarina** [comment]
I'm not sure which branch this needs to land on. The `release/v2.8` branch is where the latest code lives so it needs to go there until we open another branch. The `release/v2.7` branch this is set to merge into is now an older path. Though, the v2.8 branch is currently in code freeze.

Can we get this against the 2.8 branch with a backport fix (like [this](https://github.com/rancher/rancher/pull/43360)) or get one for the v2.8 and v2.7 branches (like [this](https://github.com/rancher/rancher/pull/43276) and [this](https://github.com/rancher/rancher/pull/43275))?

**Comment by l-mb** [comment]
This affects the shipping code in 2.7, so we also definitely want those CVEs fixed here. I propose to merge this one to update the dependency, and then open another for v2.8

**Review by l-mb — APPROVED** [review]

**Review by mattfarina — APPROVED** [review]
Connected with QA and others. Should be good to go.

**Pull request merged**
