### PR TITLE
Nutanix Rancher Node driver

### PR DESCRIPTION
**Pull request by tuxtof**
This PR integrate Nutanix Rancher Node driver in the default provided list of driver

https://github.com/rancher/rancher/issues/36348

### CODE REVIEW

**Comment by snasovich** [comment]
@tuxtof , could you please squash the commits?

**Review by Oats87 — DISMISSED** [review]
lgtm

**Comment by thedadams** [comment]
Looks good commits are squashed.

**Review by snasovich — APPROVED** [review]
This looks good to me now, once either/both of @thedadams / @Oats87 approves it's good to merge (following CI succeeding of course).

**Comment by tuxtof** [comment]
normally i have correctly squash and rebase the PR , can you confirm if everything if ok for you @snasovich @thedadams

**Review by Oats87 — APPROVED** [review]

**Pull request merged**
