### PR TITLE
Add config parse flag to rancherd

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
This PR adds the config file parse flag and also clean up systemd file(Changes from @MonzElmasry)

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/29422

**Review by MonzElmasry — APPROVED** [review]
LGTM

**Review by brandond — APPROVED** [review]

**Review by dweomer — APPROVED** [review]

**Comment by cbron** [comment]
Needs backport to release/v2.5

**Pull request merged**
