### PR TITLE
add compare image scripts

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
This will constantly fail until we fix the images.

**Comment by ibuildthecloud** [comment]
@StrongMonkey Can you do all this with never modifying git?  So don't checkout.  There's got to be a way to cat a file at a specific version (git show commit -- foo ??).  Also can you also do all this in a subfolder of ./build.  don't create temp files in scripts.

**Comment by StrongMonkey** [comment]
@ibuildthecloud changes done.

**Comment by StrongMonkey** [comment]
Might not be needed anymore.

**Pull request closed without merging**
