### PR TITLE
[2.8] Update Go to 1.21

### PR DESCRIPTION
**Pull request by pmatseykanets**
## Problem

`eks-operator` requires Go toolchain 1.21.

```
go mod tidy -go=1.20
go: github.com/rancher/eks-operator@v1.3.1-rc7 requires go@1.21, but 1.20 is requested
```
 
## Solution

Update Go to 1.21.
 
### Automated Testing

* Test types added/modified:
    * None

### Regressions Considerations
N/A

### CODE REVIEW

**Review by tomleb — APPROVED** [review]

**Review by JonCrowther — APPROVED** [review]

**Comment by chiukapoor** [comment]
Hello Team,

k8s v1.28.x officially uses go version [1.20](https://github.com/kubernetes/kubernetes/blob/c8dcb00be9961ec36d141d2e4103f85f92bcf291/go.mod#L9). I am currently checking with eks, gke and aks operator team if [go 1.21](https://github.com/rancher/eks-operator/commit/e165ecab5e2a87c9f78f80a13e92b22a7f84988e) can be reverted to match the k8s 1.28.x go version requirement.

**Comment by mjura** [comment]
> Hello Team,
> 
> k8s v1.28.x officially uses go version [1.20](https://github.com/kubernetes/kubernetes/blob/c8dcb00be9961ec36d141d2e4103f85f92bcf291/go.mod#L9). I am currently checking with eks, gke and aks operator team if [go 1.21](https://github.com/rancher/eks-operator/commit/e165ecab5e2a87c9f78f80a13e92b22a7f84988e) can be reverted to match the k8s 1.28.x go version requirement.

Please look on https://github.com/rancher/rancher/pull/44586

**Comment by pmatseykanets** [comment]
@chiukapoor @mjura Thanks! It's great that we were able to revert to 1.20 in eks-operator.
Though rancher itself can still benefit from a newer Go toolchain.

**Review by macedogm — APPROVED** [review]

**Review by mjura — APPROVED** [review]

**Comment by mjura** [comment]
> @chiukapoor @mjura Thanks! It's great that we were able to revert to 1.20 in eks-operator. Though rancher 2.8 itself can still benefit from a newer Go toolchain. Since Go 1.22 is out 1.20 is not going to be supported.

I would go for this change in v2.8 anyway :+1:

**Pull request merged**
