### PR TITLE
update nutanix node driver to v3.4.0

### PR DESCRIPTION
**Pull request by tuxtof**
Issue: https://github.com/rancher/rancher/issues/42576

Update Nutanix Rancher Node Driver to v3.4.0

## Testing

manual installation of the node driver and cluster deployment with it

image

Driver is activated

image

RKE2 install

image

RKE1 install

image

### CODE REVIEW

**Review by snasovich — APPROVED** [review]
LGTM, changes match the previous bump to Nutanix node driver version - https://github.com/rancher/rancher/pull/38864

Though the download URL format has changed in 3.4.0 release but it should not affect anything adversely

**Comment by tuxtof** [comment]
We change the binary name because we hit the same issue as here
https://github.com/rancher/rancher/issues/11339
And it seems all the other plug-in have the same name format

if you have more info please

**Review by jakefhyde — APPROVED** [review]
LGTM, @tuxtof were you able to confirm the driver works for both rke1 and rke2/k3s?

**Comment by tuxtof** [comment]
@jakefhyde yes and i just add a second screenshot above for the rke1 test

**Pull request merged**
