### PR TITLE
[2.5] Fix for machine_cpu_cores being removed from cadvisor metrics

### PR DESCRIPTION
**Pull request by dnoland1**
See also https://github.com/rancher/rancher/issues/29292

### CODE REVIEW

**Review by aiyengar2 — APPROVED** [review]
see comment in https://github.com/rancher/rancher/pull/29860#discussion_r529869576

**Review by guangbochen — APPROVED** [review]

**Review by dramich — APPROVED** [review]

**Comment by aiyengar2** [comment]
Hmm weird, the drone build is failing because of a failure while trying to create rancher-images.txt here:
```
time="2020-12-02T18:35:42Z" level=info msg="generating k3s image list..."
2755	time="2020-12-02T18:35:42Z" level=info msg="finished generating k3s image list..."
2756	2020/12/02 18:35:42 Creating rancher-images.txt
2757	2020/12/02 18:35:42 Image: busybox
2758	2020/12/02 18:35:42 Image [jaegertracing/all-in-one:1.20.0] does not start with rancher/
2759	exit status 1
2760	time="2020-12-02T18:35:45Z" level=fatal msg="exit status 1"
```

This seems to be related to a change made in `rancher/charts` to resolve this [here](https://github.com/rancher/charts/pull/865), but I'm unsure if the fix is just to rebase the PR since re-running the drone build doesn't seem to resolve the issue.

@dnoland1 can you try rebasing this PR against the latest to see if that resolves the issue?

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
I just noticed that this PR is trying to merge changes to `2.5-head`. Can you modify / re-open the PR to point to `release/v2.5` branch?

**Comment by dnoland1** [comment]
@aiyengar2 Created new PR for release/v2.5 here - https://github.com/rancher/rancher/pull/30335

**Comment by aiyengar2** [comment]
Thanks @dnoland1 , closing out this PR in favor of https://github.com/rancher/rancher/pull/30335

**Comment by maggieliu** [comment]
closing in favor of: https://github.com/rancher/rancher/pull/30339

**Pull request closed without merging**
