### PR TITLE
Bump test dependencies

### PR DESCRIPTION
**Pull request by pjbgf**
## Problem
The dependency versions below have known public CVE's:
- `flask`
- `requests`
- `cryptography`

## Solution
Bump Python dependencies used within the Integration and Validation Tests. As part of the changes Python was bumped from `3.6` to `3.11`, which was required as some dependencies no longer support version `3.6`.

### CODE REVIEW

**Comment by macedogm** [comment]
@bmdepesa and @pjbgf I had a look in the PR and its failures and my understanding is:

1. The test `test_alert.py::test_add_notifier` is failing because Flask is not being shutdown, so it times out. `werkzeug.server.shutdown` was deprecated in https://github.com/pallets/werkzeug/issues/1752 in `2.0.0`. In order for the test to work, we need to change https://github.com/rancher/rancher/blob/d0eac94cb41954b67d2c7b17ee34af9713e046a4/tests/integration/suite/alert_common.py#L17-L22

2. Warning message of `PytestUnknownMarkWarning: Unknown pytest.mark.nonparallel - is this a typo? ...` are appearing because we are not defining that custom mark. This can be solved by adding the code below in `tests/integration/tox.ini`.

```python
[pytest]
markers =
    nonparallel: mark a test as non-parallel.
```
3. Other warning messages of `InsecureRequestWarning: Unverified HTTPS request is being made to host '172.17.0.3'. ...` are appearing because we are not verifying the self-signed certificates, which is fine in the tests, we just need to suppress this warning.

I believe that by addressing the points above we should be fine to do the proposed bumps.

Note: I was able to get only point 1 as failed test by slightly increasing the `timeout` in `tests/integration/tox.ini`, which means that overall the only issue after the bumps is really with the Flask deprecation of the shutdown method.

**Comment by pjbgf** [comment]
@macedogm thank you for the support getting this to work. :bow:

**Comment by bmdepesa** [comment]
We are still looking into this. Attempting to test on the upcoming RC

**Comment by macedogm** [comment]
@bmdepesa can we merge this PR, please?

**Comment by bmdepesa** [comment]
We are still working on validating the changes in the validation tests and plan to merge this week.

**Comment by bmdepesa** [comment]
Update - we are wrapping up the testing today. 

Once done we will merge this PR and then will need to merge https://github.com/rancher/rancher/pull/43817 immediately after. 

I am approving now, but let's please let @igomez06 merge once the team wraps up the testing.

**Review by bmdepesa — DISMISSED** [review]

**Comment by pjbgf** [comment]
Re-targeted to `v2.9` as per new branching guidelines.

**Comment by pjbgf** [comment]
Re-based changes for good measure.

**Review by igomez06 — APPROVED** [review]

**Pull request merged**
