### PR TITLE
Tick UI Dashboard index to release-2.6.3-patch3

### PR DESCRIPTION
**Pull request by rak-phillip**
This updates UI Dashboard index to `release-2.6.3-patch3`

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>

### CODE REVIEW

**Review by kinarashah — APPROVED** [review]

**Comment by nwmac** [comment]
@rak-phillip the CU gate failed - otherwise LGTM

**Comment by rak-phillip** [comment]
@nwmac thanks for the heads up, interestingly enough it only fails on the linux-amd64/arm64 builds.. I'll see what if I can't figure out what's going on.

**Review by nwmac — APPROVED** [review]
LGTM - gate failing though

**Comment by rak-phillip** [comment]
Linking rancher/dashboard#5532

**Pull request merged**
