### PR TITLE
Add rbac rules for alerting and logging

### PR DESCRIPTION
**Pull request by zionwu**

### CODE REVIEW

**Comment by zionwu** [comment]
@cjellick, please review this PR. Thanks.

**Comment by aiwantaozi** [comment]
LGTM

**Comment by cjellick** [comment]
Where are the following stored?
clusterpipelines
clusterloggings
clusteralerts
notifiers
pipelines
pipelineexecutions
pipelineexecutionlogs
notifiers
projectalerts
projectloggings

Are they stored in the mgmt cluster or the user cluster?
Are they namespaced or not namespaced?

Can you add tests to prove the auth for these works as expected? I know there are not a lot of tests around auth, but we have to start somewhere.

**Comment by zionwu** [comment]
@cjellick All CRDs are stored in mgmt cluster and are namespaced.

Do you mean adding automation test to rancher/tests?

**Comment by zionwu** [comment]
Related issue: https://github.com/rancher/rancher/issues/12791

**Comment by cjellick** [comment]
I still don't fully understand how these resources should function or what the RBAC _should_ be around them, but I can make pretty good assumptions based off of how you set them up in the roles and you did it correctly.
LGTM

**Pull request merged**
