### PR TITLE
need check whether there is stale app when enable logging

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
if we don't check stale logging app, may not deploy if there is a stale
app

Solution:
check app delete timestampe

Issue:
https://github.com/rancher/rancher/issues/18214

### CODE REVIEW

**Comment by orangedeng** [comment]
Instead of checking the apps when we deploy it, maybe we should watch the apps lifecycle for logging. When we the apps we care(in this case, it is logging apps) is trying to be delete, it should enqueue the logging controller and make sure the logging is in the status(on/off) we want.

**Comment by orangedeng** [comment]
But I go through this again, I think it is good enough for the issue we are trying to address. LGTM

**Comment by aiwantaozi** [comment]
@orangedeng thx, now the system component monitoring, alerting, logging both use similar deploy logic, they aren't watching apps now, no need to just make logging work differently from others, we can make these three both watch apps in next version.

**Comment by loganhz** [comment]
LGTM https://github.com/rancher/rancher/pull/18215#issuecomment-464952610

**Pull request merged**
