### PR TITLE
[2.5]Add support for cluster-level registry(rke) for shell and helm

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
Need dependency of https://github.com/rancher/steve/pull/15

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/30735

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/31618

**Comment by StrongMonkey** [comment]
This PR adds an Enviroment variable(setting) to cluster agent so that the system-default-registry or cluster-level registry is passed into steve agent. The steve agent will use this variable to launch shell images used in helm and kubectl, instead of copying setting from management rancher.

**Review by kinarashah — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
