### PR TITLE
Add Heroku generated app.json

### PR DESCRIPTION
**Pull request by nick-grey**
)

### CODE REVIEW

**Comment by nick-grey** [comment]
9

**Comment by ibuildthecloud** [comment]
Not totally sure what to do with this?  What's the purpose?

**Comment by ununseptium** [comment]
@ibuildthecloud there's no purpose i guess. Look at the commits. 
It seems, he did some mistakes. I would recommend to close this.

**Comment by deniseschannon** [comment]
@nick-grey If you feel this should be re-opened, let me know.

**Pull request closed without merging**
