### PR TITLE
Run goimports on all of rancher and add to CI

### PR DESCRIPTION
**Pull request by dramich**

### CODE REVIEW

**Comment by daxmc99** [comment]
LGTM 💯

**Comment by daxmc99** [comment]
Performed with `goimports  $(find . -type f -name '*.go' -not -path "./vendor/*")`

**Comment by cjellick** [comment]
lgtm, but want to @alena1108 to review too

**Comment by alena1108** [comment]
LGTM

**Comment by alena1108** [comment]
@daxmc99 what's the go imports version you are using?

**Comment by daxmc99** [comment]
@alena1108 Goimports was bumped up in this PR https://github.com/rancher/types/pull/860. 
There is a release branch for v1.12 that we are going to use.

For posterity, the sha1sum of the goimports binary used in this was `d9270b766b303ce234edecfff27445197e0a8af0`

**Pull request merged**
