### PR TITLE
Updated metric mapping

### PR DESCRIPTION
**Pull request by Rucknar**
Following on from testing out the new prometheus compatible metrics endpoint, this PR covers some recommendations to bring the metrics into best practice according to the documentation [here](https://prometheus.io/docs/instrumenting/writing_exporters/)

## Key Changes

* Added prefix for the exporter to help identify metrics easier in larger deployments
* Removed min/max/mean/95th percentile, kept only count. These calculations can easily be done in Prometheus if required (some info in the above link)
* Name change from `_Count` to `_total` to fit conventions
* Added some previously uncaptured counts to give full coverage of the metrics exposed
* Added the flag ` -graphite.mapping-strict-match` to ignore any unmatched metrics that are processed.

Worth Mr @cloudnautique having a look, i'm only approaching this from utilising these metrics in an upcoming update to the Prometheus catalog entry.

### CODE REVIEW

**Comment by cloudnautique** [comment]
Cool, we want it to be "conventional" so this is a good direction. I created this script so that the mapping could be done programmatically since there are a lot of metrics, and @ibuildthecloud is going to add some more for us.

https://github.com/rancher/rancher/blob/master/server/bin/metric_mapper.sh

Any chance you can get the output your hoping for using the script?

**Comment by Rucknar** [comment]
Of course, let me tinker with it today and try match the output files!

**Comment by Rucknar** [comment]
@cloudnautique Script updated. Now implements the logic detailed above when run. 
I've executed it against a server that's been running over 24 hours and logged the output of the script into the config mapping.

**Comment by Rucknar** [comment]
Annnd squashed to a single commit for good measure.

**Comment by Rucknar** [comment]
@cloudnautique Hey Bill, any chance this could get reviewed? Got the updated catalog entry which depends on this.

**Comment by cloudnautique** [comment]
Sorry, Dockercon took up all the time last week. This looks good to me.

**Comment by Rucknar** [comment]
Awesome, thanks @cloudnautique !

**Pull request merged**
