### PR TITLE
[v2.7] feat: bump harvester node driver to v0.6.7

### PR DESCRIPTION
**Pull request by FrankYang0529**
## Issue:
 
https://github.com/rancher/rancher/issues/44312

Releated Harvester issues:

* https://github.com/harvester/harvester/issues/4588
* https://github.com/harvester/harvester/issues/2764
* https://github.com/harvester/harvester/issues/4777

This PR bump Harvester Node Driver to version v0.6.7

### CODE REVIEW

**Review by bk201 — APPROVED** [review]

**Comment by gaktive** [comment]
Hopefully this is an easy review based on past efforts in #43595

**Comment by jiaqiluo** [comment]
It looks like Harvester has been bumped to 0.6.7 in the release/v2.7 branch ([code](https://github.com/rancher/rancher/blob/release/v2.7/package/Dockerfile#L41)).

hi @FrankYang0529 , can you confirm and close this PR if that is true?

**Comment by FrankYang0529** [comment]
> It looks like Harvester has been bumped to 0.6.7 in the release/v2.7 branch ([code](https://github.com/rancher/rancher/blob/release/v2.7/package/Dockerfile#L41)).
> 
> hi @FrankYang0529 , can you confirm and close this PR if that is true?

Yeah, it looks like it has been updated. Not sure whether there it's backport from v2.7.11.

https://github.com/rancher/rancher/commit/d65a22e2886bfebe67780aff5695a140459e7917

**Comment by FrankYang0529** [comment]
Close the PR as we already have the change in v2.7.

**Pull request closed without merging**
