### PR TITLE
Add admin user to allowedIdentities

### PR DESCRIPTION
**Pull request by mrajashree**
https://github.com/rancher/rancher/issues/12373

### CODE REVIEW

**Comment by cjellick** [comment]
> the other change (`https://github.com/rancher/rancher/pull/12596/files#diff-ec250086fd2b87d4ec872bc6e6b6a890R79`) is not in github, idk why it's being set automatically in github, but AD requires it explicitly

this worries me. Using the network tab of the browser, can you capture the request in question for both github and AD and compare them and post them here (sanitized to remove sensitive bits from our test AD set)?

**Comment by mrajashree** [comment]
For GH
The testAndApply request
Request URL: https://localhost:8443/v3/githubConfigs/github?action=testAndApply POST
Request Payload: 
```
{"code":"f1b35d131549d2e09312","enabled":true,"githubConfig":{"actionLinks":{"configureTest":"https://localhost:8443/v3/githubConfigs/github?action=configureTest","testAndApply":"https://localhost:8443/v3/githubConfigs/github?action=testAndApply"},"baseType":"authConfig","created":"2018-04-10T00:38:19Z","createdTS":1523320699000,"creatorId":null,"enabled":false,"hostname":"github.com","id":"github","links":{"self":"https://localhost:8443/v3/githubConfigs/github","update":"https://localhost:8443/v3/githubConfigs/github"},"name":"github","tls":true,"type":"githubConfig","uuid":"7783f5a9-3c57-11e8-99f0-0800273b433d","scheme":"https://","clientId":"e59f0118173797a52275","clientSecret":"e9fee78b786925fc41f56cb9c80a676d03da39f2","accessMode":"restricted","allowedPrincipalIds":[]},"description":"UI Session","ttl":57600000}
```
In the above request, allowedIDs is empty, but the request below has it
Request URL: https://localhost:8443/v3/githubConfigs/github GET
Request Payload: 
```
{"baseType":"authConfig","created":"2018-04-10T00:38:19Z","createdTS":1523320699000,"creatorId":null,"enabled":false,"hostname":"github.com","id":"github","name":"github","tls":true,"type":"githubConfig","uuid":"7783f5a9-3c57-11e8-99f0-0800273b433d","scheme":"https://","clientId":"###","clientSecret":"###","accessMode":"restricted","allowedPrincipalIds":["github_user://###"]}
github?action=configureTest	github?action=testAndApply	principals?me=true&provider=github&limit=-1&sort=name	github	10672776?v=4	github	vendor.css	vendor.js	ui.js	ui-light.css?2.0.35	vendor.css?2.0.35	authProviders	
```

##############
For AD
The testAndApply request
Request URL: https://localhost:8443/v3/activeDirectoryConfigs/activedirectory?action=testAndApply POST
Request Payload:
```
{"activeDirectoryConfig":{"actionLinks":{"testAndApply":"https://localhost:8443/v3/activeDirectoryConfigs/activedirectory?action=testAndApply"},"baseType":"authConfig","connectionTimeout":5000,"created":"2018-04-10T00:43:05Z","createdTS":1523320985000,"creatorId":null,"enabled":false,"groupDNAttribute":"distinguishedName","groupMemberUserAttribute":"distinguishedName","groupNameAttribute":"name","groupObjectClass":"group","groupSearchAttribute":"sAMAccountName","id":"activedirectory","links":{"self":"https://localhost:8443/v3/activeDirectoryConfigs/activedirectory","update":"https://localhost:8443/v3/activeDirectoryConfigs/activedirectory"},"name":"activedirectory","port":389,"tls":false,"type":"activeDirectoryConfig","userDisabledBitMask":2,"userEnabledAttribute":"userAccountControl","userLoginAttribute":"sAMAccountName","userNameAttribute":"name","userObjectClass":"person","userSearchAttribute":"sAMAccountName","uuid":"218c0c5a-3c58-11e8-b077-080027d96914","servers":["###"],"defaultLoginDomain":"###","serviceAccountUsername":"###","serviceAccountPassword":"###","userSearchBase":"###","accessMode":"unrestricted"},"enabled":true,"username":"###","password":"###"}
```
For AD, the same request doesn't even have the allowedPrincipalIDs field, and there's no second request as in case of GH

**Comment by mrajashree** [comment]
For GH
The testAndApply request
Request URL: https://localhost:8443/v3/githubConfigs/github?action=testAndApply POST
Request Payload: 
```
{"code":"f1b35d131549d2e09312","enabled":true,"githubConfig":{"actionLinks":{"configureTest":"https://localhost:8443/v3/githubConfigs/github?action=configureTest","testAndApply":"https://localhost:8443/v3/githubConfigs/github?action=testAndApply"},"baseType":"authConfig","created":"2018-04-10T00:38:19Z","createdTS":1523320699000,"creatorId":null,"enabled":false,"hostname":"github.com","id":"github","links":{"self":"https://localhost:8443/v3/githubConfigs/github","update":"https://localhost:8443/v3/githubConfigs/github"},"name":"github","tls":true,"type":"githubConfig","uuid":"7783f5a9-3c57-11e8-99f0-0800273b433d","scheme":"https://","clientId":"###","clientSecret":"###","accessMode":"restricted","allowedPrincipalIds":[]},"description":"UI Session","ttl":57600000}
```
In the above request, allowedIDs is empty, but the request below has it
Request URL: https://localhost:8443/v3/githubConfigs/github GET
Request Payload: 
```
{"baseType":"authConfig","created":"2018-04-10T00:38:19Z","createdTS":1523320699000,"creatorId":null,"enabled":false,"hostname":"github.com","id":"github","name":"github","tls":true,"type":"githubConfig","uuid":"7783f5a9-3c57-11e8-99f0-0800273b433d","scheme":"https://","clientId":"###","clientSecret":"###","accessMode":"restricted","allowedPrincipalIds":["github_user://###"]}
github?action=configureTest	github?action=testAndApply	principals?me=true&provider=github&limit=-1&sort=name	github	10672776?v=4	github	vendor.css	vendor.js	ui.js	ui-light.css?2.0.35	vendor.css?2.0.35	authProviders	
```

##############
For AD
The testAndApply request
Request URL: https://localhost:8443/v3/activeDirectoryConfigs/activedirectory?action=testAndApply POST
Request Payload:
```
{"activeDirectoryConfig":{"actionLinks":{"testAndApply":"https://localhost:8443/v3/activeDirectoryConfigs/activedirectory?action=testAndApply"},"baseType":"authConfig","connectionTimeout":5000,"created":"2018-04-10T00:43:05Z","createdTS":1523320985000,"creatorId":null,"enabled":false,"groupDNAttribute":"distinguishedName","groupMemberUserAttribute":"distinguishedName","groupNameAttribute":"name","groupObjectClass":"group","groupSearchAttribute":"sAMAccountName","id":"activedirectory","links":{"self":"https://localhost:8443/v3/activeDirectoryConfigs/activedirectory","update":"https://localhost:8443/v3/activeDirectoryConfigs/activedirectory"},"name":"activedirectory","port":389,"tls":false,"type":"activeDirectoryConfig","userDisabledBitMask":2,"userEnabledAttribute":"userAccountControl","userLoginAttribute":"sAMAccountName","userNameAttribute":"name","userObjectClass":"person","userSearchAttribute":"sAMAccountName","uuid":"218c0c5a-3c58-11e8-b077-080027d96914","servers":["###"],"defaultLoginDomain":"###","serviceAccountUsername":"###","serviceAccountPassword":"###","userSearchBase":"###","accessMode":"unrestricted"},"enabled":true,"username":"###","password":"###"}
```
For AD, the same request doesn't even have the allowedPrincipalIDs field, and there's no second request as in case of GH

**Comment by cjellick** [comment]
See my comment in the associated isssue. I think the UI should consistently be sending/not-sending it across providers. I don't think this should be a backend change (or if it shoiuld, it shoiuld be to all providers).

**Comment by deniseschannon** [comment]
Fixing in the UI.

**Pull request closed without merging**
