### PR TITLE
Report DNSRecord and Service via websocket in the same time

### PR DESCRIPTION
**Pull request by orangedeng**
Refer to issue https://github.com/rancher/rancher/issues/14367.
We should not use the same store for two types. It will cause watch func
of this store returns two datas with one of the types
instead of two data for each type.

### CODE REVIEW

**Comment by orangedeng** [comment]
@ibuildthecloud @cjellick we can not share the same store for service and dnsRecord. Even creating the new store object with following code.
```
	dnsSchema.Store = struct {
		types.Store
	}{
		serviceSchema.Store,
	}
```
Both Service's and DNSRecord's store will share broadcasters attributes. And then we will use shareWatch in each Watch func of the store(`https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/norman/store/proxy/proxy_store.go#L208`). And Both of the store will use the same `Broadcaster` but only one of the realWatch function will be execute. it might be Service or DNSRecord schema which depends on which one gets the lock first.

So it this case, we should not share the same store between Service and DNSRecord schema.

And the `addProxyStore` func could work but it will assign the store to the schema immediately. I don't want that so I create a new function for creating proxyStore for another schema.

**Comment by ibuildthecloud** [comment]
First, I don't understand what this code is supposed to accomplish
```go
       dnsSchema.Store = struct {
		types.Store
	}{
		serviceSchema.Store,
	}
```
I know you didn't write it, but it seems like it is the same as
```go
dnsSchema.Store = serviceSchema.Store
```
But anyways, I'm still confused.  I don't really get it.  So the subscribe handler basically does "for each schema.Store" and calls watch.  So shouldn't that mean in the current setup it does watch on dnsSchema and watch on service schema.  Which are the same store but two different method calls.  Each call should make a new channel which duplicates the message from the broadcaster.  I'm not saying this code is wrong, I just honestly don't understand how the existing code is wrong.

**Comment by ibuildthecloud** [comment]
I finally understand the issue.  The problem is that dnsRecord and service both use the same instance of the store.  When watch is call only one real watch can be made and the core mapper logic is associated with the real watch.  Only one of the two can do the real watch so the core mapper can only be one of the two.  So they have to have different stores.

**Comment by ibuildthecloud** [comment]
@orangedeng I don't like the mirrorProxyStore method because it is so subtly different from addProxyStore that it's hard to understand what is going on.  I'd rather do something like
```go
func Service(schemas *types.Schemas) {
	serviceSchema := schemas.Schema(&schema.Version, "service")
	dnsSchema := schemas.Schema(&schema.Version, "dnsRecord")
	// Move service store to DNSRecord and create new store on service, so they are then
        // same store but two different instances
	dnsSchema.Store = serviceSchema.Store
	addProxyStore(ctx, schemas, mgmt, client.ServiceType, "v1", service.New)
}

```

**Comment by orangedeng** [comment]
Updated

**Comment by ibuildthecloud** [comment]
LGTM

**Pull request merged**
