### PR TITLE
Add cloudscale.ch driver.

### PR DESCRIPTION
**Pull request by alakae**
This adds the [cloudscale.ch](https://www.cloudscale.ch/en/) machine and ui-driver to the list of drivers available for installation with rancher.

Our drivers are maintained at:
 * https://github.com/cloudscale-ch/ui-driver-cloudscale
 * https://github.com/cloudscale-ch/docker-machine-driver-cloudscale

Screenshot

### CODE REVIEW

**Comment by alakae** [comment]
I am looking into why the CI failed.

**Comment by alakae** [comment]
CI is now passing.

**Comment by daxmc99** [comment]
Hi @alakae, 
Thanks for the PR. I am hoping to be able to take a look at it this week.

**Comment by vincent99** [comment]
The UI component URL is loaded directly by the user's browser, so its hostname does not need to be whitelisted.  

The component _does_ make AJAX calls `https://api.cloudscale.ch` though.  It's making them directly to the API and therefore requires CORS, but no CORS headers are sent back with e.g. auth error responses (e.g. the token is wrong) so you will be unable to see the response body. (They are sent back for successful responses).

So that should either always return CORS headers, or be changed to go through the Rancher proxy `/meta/proxy`, in which case `api.cloudscale.ch` needs to be whitelisted.

**Comment by vincent99** [comment]
What I said above is wrong, the UI CSS/JS does get proxied so the domain (`objects.cloudscale.ch`) does need to be whitelisted.

You do still probably want to fix CORS on errors or use the proxy for API calls.

**Comment by alakae** [comment]
Hi Vincent, I am currently investigating how we can fix the „CORS on errors„ issue. I hope that we can roll-out the change next week. Thanks a lot for your help.

**Comment by alakae** [comment]
@vincent99 Thanks again for brining our attention to the CORS misconfiguration. We have adapted the configuration of the web server. The CORS headers are now always returned. If an invalid token is specified the error message is now visible to the user. The merge request does not need to be changed.

**Pull request closed without merging**
