### PR TITLE
[SURE-5388]: add owner reference to the secret

### PR DESCRIPTION
**Pull request by pratikjagrut**
## Issue: https://github.com/rancher/rancher/issues/40849
 Re-opening PR: https://github.com/rancher/rancher/pull/44560
## Problem
Custom downstream cluster secrets remain in the local cluster after the custom downstream cluster is deleted 
 
## Solution
Add owner reference to the secret so that the secret will be automatically deleted once the cluster is deleted.
 
### Manual Testing

- Create a custom rke1 cluster
- Check secret (kubectl -n cattle-system get secrets -l cattle.io/creator=norman) if it's created or not
- Delete the custom cluster
- Check secret (kubectl -n cattle-system get secrets -l cattle.io/creator=norman) if it's deleted or not

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

### CODE REVIEW

**Comment by jakefhyde** [comment]
@pratikjagrut Can you re-run CI/figure out why the tests aren't passing?

**Comment by pratikjagrut** [comment]
> @pratikjagrut Can you re-run CI/figure out why the tests aren't passing?

@jakefhyde All checks are passing now. CI was failing due to some network issue.

**Comment by snasovich** [comment]
Found this neglected PR while reviewing linked issues; added @rancher/observation-backup to reviewers per the above request.

**Comment by jbiers** [comment]
Hi @snasovich and @jakefhyde, sorry it took us a while to get to this PR, it went unnoticed by us for quite a while.

As far as I understood from this PR and its linked issue, downstream cluster secrets are currently created without an ownerReference and because of that are left behind after the downstream cluster deletion. So this PR seeks to add the ownerReference to fix this behavior. Please correct me if there's any misunderstanding from my part.

I can assure that BRO maintains ownerReferences during backups so that would not be a problem. Are there any other specific concerns from you guys regarding how these changes would interact with BRO?

**Comment by jakefhyde** [comment]
I just wanted to confirm, my memory of BRO is a little hazy but it should loop through OwnerReferences and update the uid to the newly restored object correct? I just want to make sure there are no secrets with ownerReferences to non-existent objects. If you are confirming that isn't a problem, then feel free to rubber-stamp this PR so we can get it merged.

**Review by jbiers — APPROVED** [review]

**Comment by jbiers** [comment]
@jakefhyde Yep, the restore should be handled correctly by BRO. Gave it an approval.
Perhaps it could be interesting to also have a QA Engineer from O&B test this change before release with your team just to make sure the BRO mechanism is working as expected and doesn't run into any edge cases in this specific scenario. 

Usually BRO changes are tested by @nickwsuse so testing could be coordinated with him based on his availability :D

**Pull request merged**
