### PR TITLE
Update rancher golang version to 1.11

### PR DESCRIPTION
**Pull request by mrajashree**
1. I tried upgrading rancher to golang 1.11, its again failing with same error as it did for go 1.10.3/4
```
Running: go fmt
# github.com/rancher/rancher
loadinternal: cannot find runtime/cgo
# github.com/rancher/rancher/pkg/agent
loadinternal: cannot find runtime/cgo
Running tests
./test: line 37: 30468 Trace/breakpoint trap   (core dumped) KUBECONFIG= ../../$CMD --add-local=true  (wd: /go/src/github.com/rancher/rancher/build/testdata)
```
2. Then I tried removing CGO_ENABLED=0 from build-server/build-agent. `make ci` was successfult, but then rancher server crashed while creating a single node DO cluster with some cgo related errors.
```
goroutine 20542 [syscall]:
runtime.cgocall(0x3d0ad10, 0xc435f24f58, 0x51c3a04)
    /usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc435f24f10 sp=0xc435f24ed8 pc=0x4022f4
os/user._Cfunc_mygetgrgid_r(0x0, 0xc425e7f540, 0xc419d70, 0x400, 0xc427b07470, 0x0)
```
These are same failures that happened while upgrading to golang 1.10.3/4
3. Then I added CGO_ENABLED=0 back and removed linkmode=external from linkflags, and the images got created plus the server didn’t crash either on DO cluster creation, but the cluster doesn’t get created properly and fails with this error (at least didn't crash this time)
```
2018/09/05 21:18:06 [ERROR] cluster [c-cn9rf] provisioning: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [138.197.101.9]: Get https://localhost:6443/healthz: can not build dialer to c-cn9rf:m-9gsfl, log: I0905 21:17:00.456185       1 logs.go:49] http: TLS handshake error from 138.197.101.9:46406: EOF
```
4. After that I added back `linkmode external`, and also added osusergo and netgo tags to the go build command, but that again leads to the first error and eventually seg fault.

### CODE REVIEW

**Comment by mrajashree** [comment]
UPDATE: As per @ibuildthecloud's suggestion, going with the 3rd option, i.e, dropping linkmode external. I ran `make ci` for current rancher master without upgrading golang or any other changes and even that led to the same TLS handshake error and prevented DO cluster creation. So this error isn't related to golang upgrade.

**Comment by mrajashree** [comment]
UPDATE: As per @ibuildthecloud's suggestion, going with the 3rd option, i.e, dropping linkmode external. @alena1108 suggested I run `make ci` for current rancher master without upgrading golang or any other changes, to see if I get same errors, and even that led to the same TLS handshake error and prevented DO cluster creation. So this error isn't related to golang upgrade.

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/14502

**Pull request merged**
