### PR TITLE
[v2.9] Port fix 478

### PR DESCRIPTION
**Pull request by bfbachmann**
Porting https://github.com/rancher/rancher/pull/45767

### CODE REVIEW

**Comment by snasovich** [comment]
Need to bump RKE1 but we're currently blocked with RKE1 tag builds failing, see https://github.com/rancher/rke/actions/runs/9511782925/job/26218563519 / https://github.com/rancher/rke/actions/runs/9511782925/job/26218563359

**Comment by jakefhyde** [comment]
@snasovich What version of RKE1 do we need to bump to?

**Comment by jakefhyde** [comment]
Closing i favor of https://github.com/rancher/rancher/pull/45940.

**Comment by snasovich** [comment]
> @snasovich What version of RKE1 do we need to bump to?

@jakefhyde , https://github.com/rancher/rke/releases/tag/v1.6.0-rc8 cut a couple days ago or anything newer should do fine as it includes https://github.com/rancher/rke/pull/3610

We should now be unblocked.

Edit: I see you closed this PR just as I was typing my response and fact-checking.

**Pull request closed without merging**
