### PR TITLE
updated to run proxy in HA mode

### PR DESCRIPTION
**Pull request by cloudnautique**

### CODE REVIEW

**Comment by cloudnautique** [comment]
@cjellick would you mind taking a look here as well?

**Comment by cjellick** [comment]
LGTM

**Comment by deniseschannon** [comment]
@cloudnautique we moved the documentation to it's own repo now. can you make the change there?

https://github.com/rancher/rancher.github.io

**Comment by cloudnautique** [comment]
Closing because docs repo has moved.

**Pull request closed without merging**
