### PR TITLE
set latest channel as default for rancherd install.sh

### PR DESCRIPTION
**Pull request by MonzElmasry**
This pr sets the latest channel -if not specified via INSTALL_RANCHERD_CHANNEL- as the default install channel. 
issue : https://github.com/rancher/rancher/issues/29209

### CODE REVIEW

**Review by dweomer — APPROVED** [review]

**Review by StrongMonkey — APPROVED** [review]

**Comment by BloodyIron** [comment]
So why wasn't the installation documentation updated to actually state this, and then provide a method to switch channels in the same documentation? I've had to go down so many rabbit holes just to find this single merge, and have had zero success getting RancherD working after 3x attempts so far.

Gee, I wonder why...

**Comment by vincent99** [comment]
Stable and latest are the same version almost all the time except right after a major release (e.g. 2.4.x -> 2.5.0).  This is not related to your problem,

**Comment by BloodyIron** [comment]
Then why even have two branches?

**Comment by vincent99** [comment]
Because during those times we want the community using the newest by default while more conservative users can opt for the older more stable one.

**Pull request merged**
