### PR TITLE
don't consider x-forwarded-for header for awsv4 signing request

### PR DESCRIPTION
**Pull request by kinarashah**
`X-Forwarded-Header` in the signed request causes issues and returns `AuthFailure: AWS was not able to validate the provided access credentials` even if the credentials are correct

### CODE REVIEW

**Comment by alena1108** [comment]
LGTM

**Comment by vincent99** [comment]
You probably want to drop all headers starting with `X-Forwarded-`, there are others that might be set/changed by a proxy in between.

**Comment by kinarashah** [comment]
@vincent99 then should I drop them only for AWS or all requests that we sign? 
 
I was also just skipping the header during signing process and adding the value back after, should I continue doing the same or just delete them?

**Comment by vincent99** [comment]
They can all still be proxied and sent along, you just don't sign them (i.e. they are not included in `X-Amz-SignedHeaders`) because their value/presence may be changed by a proxy further down the line.

**Pull request merged**
