### PR TITLE
feat: Allows configuration of the Service

### PR DESCRIPTION
**Pull request by robcharlwood**
## Issue: 
https://github.com/rancher/rancher/issues/16061
 
## Problem
When deploying to GKE using the chart provided service, the load balancer fails to deploy. I specifically noticed this when running the setup below.

* Private GKE cluster
* Using the GKE (Google) Ingress  (Not ``nginx`` or ``trafeik``.)
* Binding the ingress with a static IP address and DNS record already provisioned by terraform using extra annotations (https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#static_ip_addresses_for_https_load_balancers)
* Using Google Managed TLS Certificates using extra annotations (https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#setting_up_a_google-managed_certificate)
* Terminating SSL at load balancer

Basically it seems that Google Managed certificates / GKE ingress can only run with NodePort services. Currently the chart defaults to ``ClusterIP`` and doesn't give you any manner of overriding this.

We also had problems applying IAP (Identity Aware Proxy) and service timeouts (google kills connections after 30 seconds by default and this breaks websockets) to our Rancher service. This is because the current rancher ``service.yaml`` file does not allow for customisation of service annotations.
 
## Solution
This PR contains a fix to allow the ``type`` attribute on the service to be provided by the user and to utilise that if it is passed. If it is not passed, the current behaviour will apply and a ``ClusterIP`` will be used.

It also allows a user to pass a block of service annotations to apply to the service. If no service annotations are passed, then the current behaviour will apply an no annotations will be provided for the service.
 
### Manual Testing
* Ran the changes above in a local check out of the chart and deployed successfully using a ``NodePort`` service type.

### Automated Testing
This PR has added helm tests for the feature added.

### Regressions Considerations
No regressions should be introduced here since the current behaviours will persist unless specifically overridden.

### CODE REVIEW

**Review by gecBurton — DISMISSED** [review]
looks sensible

**Comment by oncipriani** [comment]
This is a **very** welcome change, but it is missing some way to add extra annotations to the Service (like the `ingress.extraAnnotations` field).

This would make it possible to use Amazon NLB without having to create a new Service manually, and would allow a good workaround for some issues:

- https://github.com/rancher/rancher/issues/17963
- https://github.com/rancher/rancher/issues/28961

**Comment by robcharlwood** [comment]
Thanks @oncipriani - I'll add a few extra bits to the PR to make this possible. 👍

**Comment by robcharlwood** [comment]
@oncipriani hey there! So I have made the additional changes requested to allow the service to be configured using user provided annotations. 👍 😄

**Review by oncipriani — APPROVED** [review]
I tested this changes using `helm template` with a `values.yml` from our own Rancher installation and these changes are exactly what we needed.

**Comment by robcharlwood** [comment]
@oncipriani @ibuildthecloud - Bump on this please! 😄 👍

**Comment by robcharlwood** [comment]
Any ideas when this might get merged please? 😄  @oncipriani @ibuildthecloud

**Review by oncipriani — APPROVED** [review]

**Comment by oncipriani** [comment]
This PR requires at least 1 approving review from someone with write
access to the repository. I have already approved it, but I do not
have write access.

Maybe @jiaqiluo could help?


Em qui., 5 de jan. de 2023 às 04:46, Rob Charlwood
***@***.***> escreveu:

**Comment by oncipriani** [comment]
This PR is still **very** relevant!

**Review by rmweir — APPROVED** [review]
LGTM

**Review by KevinJoiner — APPROVED** [review]
👍🏾

**Comment by KevinJoiner** [comment]
@robcharlwood We will target this PR for our Q2 release and merge after v2.7.2 is released. Thanks for updating this and adding the test.

**Comment by robcharlwood** [comment]
> @robcharlwood We will target this PR for our Q2 release and merge after v2.7.2 is released. Thanks for updating this and adding the test.

Thank you! and my pleasure! Glad I could help!

**Pull request merged**
