### PR TITLE
Added fleet.cattle.io client to the automation framework

### PR DESCRIPTION
**Pull request by igomez06**
**Framework updates**
 Generated fleet client, as well as implemented the hooks for automation cleanup for gitreop and clustergroups.

### CODE REVIEW

**Review by paynejacob — COMMENTED** [review]
Do we need these clients in rancher proper? I though we generated them in the test framework package?

**Comment by igomez06** [comment]
> Do we need these clients in rancher proper? I though we generated them in the test framework package?

So only the v3 clients are generated in our framework. We have been generating the  v1 clients (catalog, and provisioning) in rancher proper from the `rancher/rancher/pkg/codegen/main.go` file, and then extending them to have our session cleanup in the framework. Since we did that with catalog and provisioning, I did the same with fleet. That's really the only reason why.

**Comment by paynejacob** [comment]
@igomez06 how are we using fleet in our testing? this is going to require vendoring fleet to be part of the release process.

**Comment by paynejacob** [comment]
@igomez06 if it were in the framework that would be fine.

**Comment by igomez06** [comment]
@paynejacob Sounds good I'll implement a client that just lives in the framework.

**Pull request closed without merging**
