### PR TITLE
Update gke-operator to latest release

### PR DESCRIPTION
**Pull request by cmurphy**

### CODE REVIEW

**Review by cbron — DISMISSED** [review]
Lgtm since we shouldn’t have to do in operator anymore

**Comment by cmurphy** [comment]
Updated go.sum now that RC6 is actually tagged

**Review by cbron — DISMISSED** [review]

**Review by rmweir — APPROVED** [review]
LGTM

**Comment by cmurphy** [comment]
Had to fix pkg/apis/go.mod too

**Review by thedadams — APPROVED** [review]

**Review by rmweir — APPROVED** [review]
Oh yeah, the other go.mod- LGTM.

**Pull request merged**
