### PR TITLE
Add fix for rancher-v3_ontag_az_certification job

### PR DESCRIPTION
**Pull request by rishabhmsra**
## Issue: 
- https://github.com/rancher/qa-tasks/issues/530

 
## Problem

- The `rancher-v3_ontag_az_certification` jenkins job was failing because of the outdated config.
 
## Solution

- Updating the OS image in code as mentioned in the [issue](https://github.com/rancher/qa-tasks/issues/530) fixed the docker installation error, however cluster provisioning started failing with new error: `[ERROR] error syncing 'c-m9zds': handler cluster-provisioner-controller: [controlPlane] Failed to upgrade Control Plane: [[host rishabh-471699 not ready]], requeuing`
- On manually provisioning the cluster via rancher was successful, hence compared the template used in rancher with the one used in the automation code and updated the az config.

### CODE REVIEW

**Review by izaac — DISMISSED** [review]
LGTM

**Comment by rishabhmsra** [comment]
Updated the PR to include the ports for network checks.

**Review by sowmyav27 — APPROVED** [review]
lgtm

**Review by slickwarren — APPROVED** [review]
LGTM

**Review by markusewalker — APPROVED** [review]

**Comment by izaac** [comment]
@rishabhmsra is there a backport PR?

**Review by izaac — APPROVED** [review]
LGTM

**Comment by rishabhmsra** [comment]
@izaac, here's the backport PR : https://github.com/rancher/rancher/pull/40515

**Pull request merged**
