### PR TITLE
WIP: store templatecontent on disk

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
need https://github.com/rancher/types/pull/613

**Comment by StrongMonkey** [comment]
@dramich @cjellick i think the memory consumption from catalog can be reduced significantly by this pr as it write templateContent into disks instead etcd database.(i was wrong, templateContent resource is actually watched because we use lister)

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/16077

**Comment by pehbehbeh** [comment]
@john-bakker Same here. Did you find a solution to permanently disable the Catalog? Currently the Library Catalog gets re-enabled everytime we restart the rancher server workload. 😞

**Comment by StrongMonkey** [comment]
close in favor of https://github.com/rancher/rancher/pull/17596.

**Pull request closed without merging**
