### PR TITLE
Fix the issue that ports are not populated when creating service

### PR DESCRIPTION
**Pull request by loganhz**
Problem:

Rancher will always drop the ports in the payload and add a default 42 port in server side when create a service.

Solution:

We should check if there are ports defined in the payload and we should respect them if there are.

Issue:

https://github.com/rancher/rancher/issues/17288

### CODE REVIEW

**Comment by orangedeng** [comment]
It will also change the logic for dns record resource. I think dns record should not support ports as input.

**Comment by loganhz** [comment]
@orangedeng Updated. Thanks

**Comment by orangedeng** [comment]
LGTM

**Comment by cjellick** [comment]
@vincent99 @ibuildthecloud is this right/ok based on your knowledge of services?

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
