### PR TITLE
Add Windows support for recognized CA

### PR DESCRIPTION
**Pull request by thxCode**
(*) self-signed CA will be import into Windows Certificate Manager
    (*) if using recognized CA, Windows agent doesn't need to set it
    into TLSConfig
    (*) tweaks components restarting sequence

Issues:
    - https://github.com/rancher/rancher/issues/15966

### CODE REVIEW

**Comment by thxCode** [comment]
@nlowe, here is the patch PR. You can get a way to test this PR from #15966 comment.

**Comment by thxCode** [comment]
@alena1108 , please review this PR.

**Comment by thxCode** [comment]
@StrongMonkey , @cjellick, please review this PR. @alena1108  isn't the Windows initial reviewer.

**Comment by StrongMonkey** [comment]
LGTM

**Pull request merged**
