### PR TITLE
[WIP] Upgrade Rancher to support Helm v3.8.0 and K8s v1.23

### PR DESCRIPTION
**Pull request by maxsokolovsky**
Related to https://github.com/rancher/rancher/issues/36464

The original goal of this PR is upgrade Helm to v3.8.0. But this requires upgrades to Kubernetes packages related to v1.23.

### CODE REVIEW

**Comment by liyimeng** [comment]
@maxsokolovsky  Nice to see this. Is it targeting v2.6.4 official release?

**Comment by maxsokolovsky** [comment]
@liyimeng, yes!

**Comment by maxsokolovsky** [comment]
Closing this, @kinarashah pulled in the necessary changes from my branch, she'll add more changes and open a separate main PR for this issue.

**Comment by liyimeng** [comment]
@kinarashah any plan when this will be landed.

**Pull request closed without merging**
