### PR TITLE
fix(arm64): gate docker machine drivers behind arch check

### LINKED ISSUE #36153: [BUG] Rancher Harvester Node driver sticks in Downloading state
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s on arm64
- Proxy/Cert Details: Cert Manager /w Rancher generated certificate

**Information about the Cluster**
- Kubernetes version: v1.22.5+k3s1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
When running 2.6.3 Rancher console on an arm64 host to manage Harvester cluster the Harvester Node Driver remains stuck in a "Downloading" state.

**To Reproduce**
1. Deploy Rancher 2.6.3 on a arm64 Kubernetes cluster (K3S in my case)
2. Install Harvester 1.0.0 on a machine as initial cluster
3. Perform "Import Existing" under Virtualization Management in Rancher and allow to complete
4. Navigate to Cluster Management -> Drivers -> Node Drivers
5. Harvester driver still remains in Downloading state 48 hours after Harvester cluster import
6. Harvester does not show up as an available Cloud provider under Cluster Creation
7. Harvester node driver package can be successfully downloaded with wget or curl

**Result**
Harvester driver still remains in Downloading state 48 hours after Harvester cluster import
Harvester does not show up as an available Cloud provider under Cluster Creation

**Expected Result**
Harvester Node Driver finishes download and Harvester shows up as an available Cloud Provider for RKE2 provisioning

**Screenshots**
Screenshot_20220114_130049
Screenshot_20220114_130146

### PR DESCRIPTION
**Pull request by konstfish**
## Issue: Rancher Harvester Node driver sticks in Downloading state / Machine Drivers Fail on ARM64
https://github.com/rancher/rancher/issues/36153
https://github.com/rancher/rancher/issues/40471
https://github.com/rancher/rancher/issues/44165
 
## Problem
As described in #40471, the download URLs for machine drivers are hardcoded in [machinedriver_data.go](https://github.com/rancher/rancher/blob/release/v2.7/pkg/data/management/machinedriver_data.go#L74). These URLs are for amd64 machines, which causes arm64 deployments to never finish the setup for either Harvester or Linode machine Drivers. Their state is thus stuck in "Downloading." This blocks the creation of other machine drivers & locks the user out of the "Add Node Template" menu (example attached below.)

image

## Solution
This PR resolves #36153 & #44165 by gating off the creation of the Harvester & Linode drivers behind a check for the runtime GOARCH. I originally wanted to do this a little cleaner by specifying arm & amd download urls for each node driver, but as the harvester machine driver doesn't have an official arm release yet I opted for this rather simple fix for now instead. This wouldn't really change much regarding the issue of all drivers being hardcoded to amd, but it does enable the node driver functionality for arm deployments since it resolves the blocking issue. 

Node List Example with this deployment (With an ARM64 driver for Hetzner Nodes added)
image

## Testing
Repro steps in the GitHub issue (#36153 / #44165) are valid.

### Manual Testing
Deployed this change on my arm64 cluster, where node drivers can now be added & used.

### CODE REVIEW

**Comment by konstfish** [comment]
@Oats87 would love if you could take a look at this seeing as you're assigned to https://github.com/rancher/rancher/issues/40471 :)

**Comment by gregkonush** [comment]
is there a manual way to upload drivers somehow for arm?

**Comment by konstfish** [comment]
@gregkonush Yeah, you can add them just like you would with regular Node Drivers, only pointing the download URL to an ARM binary. Problem right now is that the newly added drivers never get processed since rancher is stuck in an infinite loop trying to to add the Linode & Harvester drivers. If you look at the diff to this PR you can see why that is, only AMD binaries are provisioned by default.

**Comment by gregkonush** [comment]
@konstfish thanks for the fix, I went into the rabbit hole yesterday to find url to download driver as there is a modal where I can upload driver manually but I couldn’t find the correct link. I found this repo https://github.com/harvester/docker-machine-driver-harvester but not sure about their release process. Do you happen to know what’s the correct link for arm?

**Comment by konstfish** [comment]
@gregkonush That repo is why this PR is so minimal. I don't think that there is an official Harvester ARM Node Driver yet sadly, [maybe since harvester itself only supports x86](https://arc.net/l/quote/huwhyojj).

If you want a super hacky way to use other Node Drivers on an ARM instance, you can turn off the validatingwebhook (`rancher.cattle.io`) that blocks deletions of `nodedrivers.management.cattle.io` CRDs, remove the Harvester & Linode ones, turn the webhook back on, and then add new ones.

**Comment by gregkonush** [comment]
harvester released a technical preview for arm support since 1.3.0. I guess there are still some bugs to fix for full release
https://github.com/harvester/harvester/releases/tag/v1.3.0

**Pull request closed without merging**
