### PR TITLE
Restart kubelet after sharemnt is run

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
Fix https://github.com/rancher/rancher/issues/25506

**Comment by superseb** [comment]
Another option would be if we could detect it is a running cluster which didn't need it anyway (as it wouldnt be able to come up properly if it would fail), and just don't run it.

**Comment by StrongMonkey** [comment]
@superseb With the change introduced ion share-mnt I think it is safe to restart kubelet once share-mnt is run. I still need to understand why kubelet restart fix it, but force deploy doesn't look like a better option. Restarting kubelet shouldn't impact existing workloads, But I wonder if share-mnt is still needed to be run on every host.

**Comment by StrongMonkey** [comment]
After talking to @ibuildthecloud, this approach seems better https://github.com/rancher/share-mnt/pull/14. First we check if root directory is mounted as shared, and if it is, skip stage2.(stage2 is to mark directory as shared).

**Comment by StrongMonkey** [comment]
@superseb ^^

**Pull request closed without merging**
