### PR TITLE
[v2.6] Update-provisioning-input-k8s-versions-v2.6

### PR DESCRIPTION
**Pull request by igomez06**
## Problem

In its current implementation it is not possible to run provisioning tests across packages. This is something we do with code coverage runs,

## Solution

 I add inputs for the the different cluster types: rke1, rke2, and k3s in the provisioningInput config entry.

### CODE REVIEW

**Review by markusewalker — DISMISSED** [review]

**Comment by igomez06** [comment]
New branch was merged so I had updated this branch again.

**Review by markusewalker — DISMISSED** [review]

**Review by caliskanugur — APPROVED** [review]
Looks good to me

**Comment by igomez06** [comment]
@markusewalker I accidentally deleted something in the k3s README put it back and pushed up the change.

**Review by markusewalker — APPROVED** [review]
LGTM

**Pull request merged**
