### PR TITLE
Removing istio and cluster templates test from code base

### PR DESCRIPTION
**Pull request by anupama2501**
## Issue: 
https://github.com/rancher/qa-tasks/issues/1281
 
## Problem:
v1 monitoring was deprecated in 2.5 and was removed from code base. the following 2 files have been not remove and they import monitoring files. 

## Solution
 Istio has been deprecated and the tests are not run anymore so its safe to remove istio.
cluster templates are still in use but we do not run these tests anymore. Following issue tracks the same:
https://github.com/rancher/qa-tasks/issues/1509

### CODE REVIEW

**Review by lscalabrini01 — APPROVED** [review]
LGTM

**Comment by slickwarren** [comment]
@markusewalker @susesgartner @Josh-Diamond confirming hostbusters doesn't want rke1 template code ran / in anymore?

**Comment by markusewalker** [comment]
@slickwarren @anupama2501 yes, this is fine to remove as we do not run these tests.

**Review by markusewalker — APPROVED** [review]

**Comment by anupama2501** [comment]
FYI added an issue for tracking as well to migrate it to golang: https://github.com/rancher/qa-tasks/issues/1509, if we want to keep this in python, we would need to add a functionality to validate monitoring related functionality which might not be worth to update in python.

**Pull request merged**
