### PR TITLE
check for nil Backupconfig.Enabled and disable backup if nil

### PR DESCRIPTION
**Pull request by MatthewKohner**
Fix for new panic I saw in 2.2.0 rc17 
Also fixed: shouldBackup will return false if Enabled is null.

```2019/03/25 13:39:36 [ERROR] EtcdBackupController c-lzksq/c-lzksq-rl-gf6wc recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:154
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:88
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_etcd_backup_lifecycle_adapter.go:29
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:219
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:191
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:181
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:219
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:64
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:45
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_etcd_backup_lifecycle_adapter.go:56
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_etcd_backup_controller.go:134
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:348
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:258
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:246
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:238
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1333
2019/03/25 13:39:36 [ERROR] EtcdBackupController c-lzksq/c-lzksq-rl-gf6wc recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:154
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:88
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_etcd_backup_lifecycle_adapter.go:29
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:219
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:191
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:181
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:219
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:64
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:45
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_etcd_backup_lifecycle_adapter.go:56
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_etcd_backup_controller.go:134
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:348
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:258
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:246
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:238
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1333
```

### CODE REVIEW

**Comment by alena1108** [comment]
Thank you for putting a pr, but looks like the issue was fixed with https://github.com/rancher/rancher/pull/19098

**Comment by MatthewKohner** [comment]
This isn't a dupe of #19093.  The panic is in a new place because with the changes in #19098 ShouldBackup now returns true when Enabled is nil. 
Eventually it hits line 88
```!*cluster.Spec.RancherKubernetesEngineConfig.Services.Etcd.BackupConfig.Enabled ```
 in Change() and panics.

**Comment by alena1108** [comment]
@MatthewKohner let me check

**Comment by alena1108** [comment]
@MatthewKohner how can i reproduce the issue

**Comment by MatthewKohner** [comment]
You would need to somehow set BackupConfig.Enabled to nil. I see the panics every few minutes but I don't have steps to reproduce the issue in a fresh install, unfortunately. I can send more logs if that is any help.

**Comment by alena1108** [comment]
@MatthewKohner 

> You would need to somehow set BackupConfig.Enabled to nil.

Yea, I just wonder how you set it. UI always sets it to true. API defaults it to true as well on create. Therefore I'd really like the steps to reproduce it.

**Comment by alena1108** [comment]
@MatthewKohner were you by any chance upgrading from one rc version of rancher to another?

**Comment by MatthewKohner** [comment]
yes, it should be defaulting to true.
I tried to find where BackupConfig.Enabled was initialized to true but setClusterServicesDefaults doesn't set it to anything. 
https://github.com/rancher/rke/blob/master/cluster/defaults.go

**Comment by MatthewKohner** [comment]
@alena1108 yes rc->rc upgrade, after which this issue first appeared.

**Comment by alena1108** [comment]
@MatthewKohner can you try the fresh rc install and see if you hit the issue. RC to RC upgrade can result in issues.

**Comment by MatthewKohner** [comment]
@alena1108 I will do that and report back

**Comment by MatthewKohner** [comment]
I did a fresh install of 2.2 and do not see the panics any more.

**Comment by cjellick** [comment]
Seems fixed. Closing

**Pull request closed without merging**
