### PR TITLE
Clean Rancher Namespaces

### PR DESCRIPTION
**Pull request by orangedeng**
**Problem:**
We only delete `cattle-system` ns when removing imported cluster.

**Solution:**
We should also remove `cattle-prometheus`, `cattle-logging` and
any other project monitoring namespaces.

Related issue:
https://github.com/rancher/rancher/issues/19476

### CODE REVIEW

**Comment by gitlawr** [comment]
Also, take into account pipeline related namespaces:
1. `cattle-pipeline` namespace in the system project
2. project pipeline namespaces that have the `pipeline.project.cattle.io/pipeline-namespace: “true”` label

**Comment by orangedeng** [comment]
Updated

**Comment by gitlawr** [comment]
LGTM

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
