### PR TITLE
reduce rancher/agent image size by ~130MB

### PR DESCRIPTION
**Pull request by imikushin**
reduce rancher/agent image size by ~130MB

and speedup the build

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Across the board we use ubuntu 14.04 as the base.  I'd rather not just switch this image to debian but the reset be Ubuntu.  I am open to switch everything to Debian though.  @cloudnautique Thoughts?  Should we just switch to Debian?

**Comment by cloudnautique** [comment]
I think we would be ok switching to Debian... in general we need to reset our baseline across the projects. I think we are drifting a little between 14.04.1 and 14.04.2. I think the space savings make it worth a look.

@imikushin do you know when they made it so you don't really need to do apt-get update anymore?

**Comment by anapsix** [comment]
you could make it smaller by another 50MB if you combine all the RUN steps into one

**Comment by aboyett** [comment]
Is there still any interest in using Debian as the base image, or is most effort focused on alpine and #1443? I'd be willing to revive this work and try my hand at porting all components, but I want to make sure the change would be well received.

**Comment by GottZ** [comment]
just out of interest.. why not use alpine? i suspect it to decrease the footprint even further.

**Pull request closed without merging**
