### PR TITLE
[2.8] Expand Kubernetes Upgrade Validation Tests for Local and Imported Clusters

### PR DESCRIPTION
**Pull request by caliskanugur**
## Problem

Currently imported clusters and local cluster upgrades tests happen manually.
 
## Solution

Add local upgrade test case and expand existing upgrade Kubernetes validation test to enable testing on downstream imported clusters.

### Automated Testing

* Test types added/modified:
    * Validation (Go Framework)

Existing / newly added automated tests that provide evidence there are no regressions: Runs will be provided offline.

Todos:
- [x] Add missing godocs

### CODE REVIEW

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by markusewalker — APPROVED** [review]
LGTM

**Review by izaac — APPROVED** [review]
:shipit:

**Review by markusewalker — DISMISSED** [review]

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by slickwarren — APPROVED** [review]
lgtm; some conflicts have appeared though after recent merges.

**Review by izaac — APPROVED** [review]

**Review by igomez06 — DISMISSED** [review]
LGTM

**Review by markusewalker — DISMISSED** [review]

**Review by slickwarren — DISMISSED** [review]

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by git-ival — APPROVED** [review]
LGTM 💯

**Review by markusewalker — APPROVED** [review]

**Pull request merged**
