### PR TITLE
[v2.8] Bump webhook to the v0.4.4

### PR DESCRIPTION
**Pull request by JonCrowther**
Bump to version from here: https://github.com/rancher/charts/pull/3868

### CODE REVIEW

**Review by maxsokolovsky — APPROVED** [review]

**Review by ericpromislow — CHANGES_REQUESTED** [review]
I think because of https://github.com/rancher/rancher/issues/44980 this should bump to webhook version 103.0.4+up0.4.5-rc1

**Comment by kinarashah** [comment]
Webhook updated to v0.4.5-rc2 here https://github.com/rancher/rancher/pull/45415

**Review by ericpromislow — CHANGES_REQUESTED** [review]
This PR looks obsolete -- webhook on `release/v2.8` is already at `v0.4.5-rc2`

**Comment by ericpromislow** [comment]
We had to bump to a newer version of webhook to pull in a fix.

**Pull request closed without merging**
