### PR TITLE
Update security email and add PGP key

### PR DESCRIPTION
**Pull request by macedogm**
Update security email to `security-rancher@suse.com` and add PGP key.

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

### CODE REVIEW

**Review by cbron — APPROVED** [review]
Didn't double check the PGP key here, but format seems fine.

**Comment by macedogm** [comment]
@cbron I've no idea why the [manifest step](https://drone-publish.rancher.io/rancher/rancher/7244/9/2) keeps failing. Could you provide some guidance here, please?

**Comment by cbron** [comment]
Typically a rebase will fix this. If not then re-branch and cherry-pick your commits.

**Comment by macedogm** [comment]
@cbron I rebased and it failed again. It only worked after I manually triggered the pipeline. Does this sounds okay to you now?

**Pull request closed without merging**
