### PR TITLE
[v2.7] Fix creation of dual stack cluster

### PR DESCRIPTION
**Pull request by GuillaumeOuint**
## Issue: 
Possibly https://github.com/rancher/rancher/issues/41650 (a user and me are in dual stack mode and faced this issue)

 
## Problem
When machines are registered in the management cluster, probes are failing.
Advertised address was "ip1,ip2"
Node IP was ["ip1,ip2"]

 
## Solution
Split the internal IP and use them as following:
Advertised address: "ip1"
Node IP:  ["ip1","ip2"]

 
## Testing
My own cluster is deployed with this code

### Automated Testing

* Test types added/modified:
    * None
* If "None" - Reason: 
    - No application logic is modified by this change, e.g. refactoring/cosmetic/non-code/test change
    - Minor change that do "dumb" logic on a string and an array
  -->

Summary: _TODO_

### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

### CODE REVIEW

**Comment by GuillaumeOuint** [comment]
Any update ? It's a critical bug for a feature that had to work from the beginning ! We're in 2023 and not supporting ipv6/dual stack correctly is concerning for a product that size. This PR block me for using the upstream rancher docker image as I need this patch (I'm currently running my cluster on a custom rancher image that include this PR)

**Comment by GuillaumeOuint** [comment]
Hey developers, can someone MERGE this branch? This is a very small fix for a MAJOR feature. Rancher not supporting dual stack in 2023 is shameful. Problems have been reported since the beginning of the year but nobody wants the fix, so I fix it, but you don't want to integrate these URGENT changes. Many of us are experiencing this problem, so please act quickly. I'm sure this problem is blocking the adoption of Rancher for some companies.

**Comment by cboergermann** [comment]
Right, it's definitely annoying since we are not able to extend our cluster because of that (wondering why it worked in the first place).

**Comment by Meirongliu-csc** [comment]
hello.. I have one question about dual-stack configration, when using dual-stack , do I set the eth0 to support ipv4 and ipv6 at the same time OR I can  use eth0 for ipv4 and eth1 for ipv6?  how to specifiy different network interface eth1 for the node to use ipv6 in RKE2 config.yaml?

**Comment by GuillaumeOuint** [comment]
> hello.. I have one question about dual-stack configration, when using dual-stack , do I set the eth0 to support ipv4 and ipv6 at the same time OR I can  use eth0 for ipv4 and eth1 for ipv6?  how to specifiy different network interface eth1 for the node to use ipv6 in RKE2 config.yaml?

Hello, as you want it doesn't matter. For the rke2 config.yaml I don't know as I don't manage it, this PR is for the planner that make config.yaml file and deploy it to some hosts.

**Comment by cboergermann** [comment]
+1

**Comment by Oats87** [comment]
@GuillaumeOuint I'm sorry we have not been able to get this PR merged.

I have some concerns around the logic (specifically, the potential implications of edge cases it may introduce). A while back, we introduced functionality to set stack preference, which can be seen here: https://github.com/rancher/rancher/blame/release/v2.9/pkg/capr/common.go#L233

I think we could try to expand upon this logic to ensure dual-stack compatibility to the node IP advertisement level. What do you think? I am happy to work on implementing this as a solution but would also like to give you the opportunity to rebase your PR upon `release/v2.9` and integrate the stack preference functionality in Rancher.

Please let me know.

**Comment by GuillaumeOuint** [comment]
@Oats87 Sorry but I will not have time to rebase, patch, build, test & PR. Changes are straightforward and can be added by you or another contributor quite easily.

**Comment by Oats87** [comment]
@GuillaumeOuint Are you trying to create a custom cluster and specifying your node config with `--address` and `--internal-address` parameters? Adding logic to split on `,` is seemingly an arbitrary UX enhancement (as we don't officially support defining multiple address/internal addresses).

Did you find documentation somewhere that states multiple addresses delineated with `,` was acceptable?

**Comment by GuillaumeOuint** [comment]
> @GuillaumeOuint Are you trying to create a custom cluster and specifying your node config with `--address` and `--internal-address` parameters? Adding logic to split on `,` is seemingly an arbitrary UX enhancement (as we don't officially support defining multiple address/internal addresses).
> 
> Did you find documentation somewhere that states multiple addresses delineated with `,` was acceptable? 

Hello, this is what I'm doing, the planner take the first IP in the slice as kube components can only listen on one IP (no comma accepted). It's not only an UX enhancement as we need this setting to correctly set up a dual stack cluster.

**Comment by Oats87** [comment]
> > @GuillaumeOuint Are you trying to create a custom cluster and specifying your node config with `--address` and `--internal-address` parameters? Adding logic to split on `,` is seemingly an arbitrary UX enhancement (as we don't officially support defining multiple address/internal addresses).
> > Did you find documentation somewhere that states multiple addresses delineated with `,` was acceptable?
> 
> Hello, this is what I'm doing, the planner take the first IP in the slice as kube components can only listen on one IP (no comma accepted). It's not only an UX enhancement as we need this setting to correctly set up a dual stack cluster.

I understand what your intention with the PR was, but I don't see this as a bug fix but rather an enhancement to add functionality (where we are defining multiple IPs). I'm not fundamentally opposed to the introduction of this behavior; however, there are potential implications that I'll need to discuss with others on my team before doing this.

**Comment by GuillaumeOuint** [comment]
> > > @GuillaumeOuint Are you trying to create a custom cluster and specifying your node config with `--address` and `--internal-address` parameters? Adding logic to split on `,` is seemingly an arbitrary UX enhancement (as we don't officially support defining multiple address/internal addresses).
> > > Did you find documentation somewhere that states multiple addresses delineated with `,` was acceptable?
> > 
> > Hello, this is what I'm doing, the planner take the first IP in the slice as kube components can only listen on one IP (no comma accepted). It's not only an UX enhancement as we need this setting to correctly set up a dual stack cluster.
> 
> I understand what your intention with the PR was, but I don't see this as a bug fix but rather an enhancement to add functionality (where we are defining multiple IPs). I'm not fundamentally opposed to the introduction of this behavior; however, there are potential implications that I'll need to discuss with others on my team before doing this. 


IPv6 launch day was in 2012, but since, most apps today is ipv4 hardcoded (because of bad devs that put 0.0.0.0 everywhere they need to listen on a port instead of ::), I thought this feature was indeed because IPv6 is supported (and because of bad software, dual stack would be indeed) so for me it's a bug but you call call it improvement if you want. Hope this will come quickly in the upstream version because as this PR was created in v2.7, I'm still in 2.7 and rke can't be upgraded so I'm stuck in 1.26.6

**Comment by Oats87** [comment]
> > > > @GuillaumeOuint Are you trying to create a custom cluster and specifying your node config with `--address` and `--internal-address` parameters? Adding logic to split on `,` is seemingly an arbitrary UX enhancement (as we don't officially support defining multiple address/internal addresses).
> > > > Did you find documentation somewhere that states multiple addresses delineated with `,` was acceptable?
> > > 
> > > 
> > > Hello, this is what I'm doing, the planner take the first IP in the slice as kube components can only listen on one IP (no comma accepted). It's not only an UX enhancement as we need this setting to correctly set up a dual stack cluster.
> > 
> > 
> > I understand what your intention with the PR was, but I don't see this as a bug fix but rather an enhancement to add functionality (where we are defining multiple IPs). I'm not fundamentally opposed to the introduction of this behavior; however, there are potential implications that I'll need to discuss with others on my team before doing this.
> 
> IPv6 launch day was in 2012, but since, most apps today are still ipv4 hardcoded (because of bad devs that put 0.0.0.0 everywhere they need to listen on a port instead of ::), I thought this feature was indeed because IPv6 is supported (and because of bad software, dual stack would be indeed) so for me it's a bug but you call call it improvement if you want. Hope this will come quickly in the upstream version because as this PR was created in v2.7, I'm still in 2.7 and rke can't be upgraded so I'm stuck in 1.26.6

If you need to define multiple internal IPs on a RKE2 node, there is a workaround you can apply.

On the node, you can create a file in a directory `/etc/rancher/rke2/config.yaml.d` (create if it does not exist, for example if you are using cloud-init to create this file)

Within there, you can simply create a YAML file that defines your desired IPs in order:
```
cat << EOF > /etc/rancher/rke2/config.yaml.d/0-config-override.yaml
node-ip:
  - 1.2.3.4
  - 2001:db8:3333:4444:5555:6666:7777:8888
EOF
```

It's best to drop this file in before the initial bootstrapping of your node, so for example, during bootstrapping of the node before the rancher-system-agent is installed.

You can override other RKE2 parameters as you see fit; however, you do need to use caution as changing things out of the realm of what the planner is expecting can lead to undesirable results.

**Pull request closed without merging**
