### PR TITLE
adding loglevel

### PR DESCRIPTION
**Pull request by leodotcloud**
https://github.com/rancher/rancher/issues/12750

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@leodotcloud I don't think the agent main turns on loglevel.

**Comment by leodotcloud** [comment]
@ibuildthecloud I already made a PR (merged).
https://github.com/rancher/agent/pull/279/commits/f6226044c201212547756fe599ff4b87d823b5a8#diff-7ddfb3e035b42cd70649cc33393fe32cR24

**Comment by cjellick** [comment]
@leodotcloud just so i understand, why do we need to install the binary?

**Comment by leodotcloud** [comment]
@cjellick Because you could do this:
```
docker exec -it rancher-agent-container loglevel --set debug
docker exec -it rancher-agent-container loglevel --set info
```

**Comment by cjellick** [comment]
cool. lgtm

**Pull request merged**
