### PR TITLE
Add the --no-cacerts flag to recognizedCA templates

### PR DESCRIPTION
**Pull request by lonewulf**
Without this flag, when an external load balancer is used with a certificate signed by a recognized CA, the ca-cert is not cleared up upon installation/upgrade. It leads to issues with getting correct kubectl configuration files in the UI and incorrect command lines generated to add nodes to custom clusters (and may lead to new nodes in other kind of clusters to fail being provisioned)

### CODE REVIEW

**Comment by superseb** [comment]
This needs a docs change before merge, and changes apply to `3-node-certificate-recognizedca.yml` as well.

**Comment by alena1108** [comment]
@superseb could you test the fix, so we can sign off the PR?

**Comment by superseb** [comment]
Must be merged together with https://github.com/rancher/docs/pull/369

**Comment by superseb** [comment]
This is tested and docs are merged, @deniseschannon @alena1108 can you merge

**Pull request merged**
