### PR TITLE
[2.9] Add a Jenkinsfile for the Local Upgrade Test Case

### PR DESCRIPTION
**Pull request by caliskanugur**
## Problem

Currently, local cluster upgrade tests happen manually.

## Solution

Add a Jenkinsfile to automate local upgrade test case that uses the expanded upgrade Kubernetes validation tests, covered steps:

1. Deploy HA local cluster
2. Deploy downstream RKE1/RKE2/K3s clusters (optional) (supports different cluster types with multiple instances)
3. Run pre-upgrade checks
4. Upgrade the local cluster's Kubernetes version
5. Run post-upgrade on downstream clusters.

### Automated Testing

* Test types added/modified:
    * Validation (Go Framework)

Existing / newly added automated tests that provide evidence there are no regressions: Runs will be provided offline.

Todos:
- [x] Rebase this PR after https://github.com/rancher/rancher/pull/43327.
- [x] Rebase this PR and update recurring runs Jenkinsfile' rancher configuration keys after https://github.com/rancher/rancher/pull/43513.

### CODE REVIEW

**Comment by caliskanugur** [comment]
Backport: https://github.com/rancher/rancher/pull/43796

**Comment by caliskanugur** [comment]
Updated the target to `release/v2.9`.

**Comment by caliskanugur** [comment]
Moved Shepherd bits to: https://github.com/rancher/shepherd/pull/13. 

Todos:
- [ ] Rebase after the framework updates

**Review by markusewalker — DISMISSED** [review]
LGTM

**Comment by caliskanugur** [comment]
Updated Shepherd to the latest version

**Comment by caliskanugur** [comment]
Backports:

- 2.7 -> https://github.com/rancher/rancher/pull/44570
- 2.8 -> https://github.com/rancher/rancher/pull/44588

**Review by slickwarren — DISMISSED** [review]

**Review by igomez06 — APPROVED** [review]
LGTM

**Comment by caliskanugur** [comment]
Removed unnecessary Shepherd-related generated files

**Pull request merged**
