### PR TITLE
[v2.7] Bump rancher webhook to v0.3.8

### PR DESCRIPTION
**Pull request by JonCrowther**
Bump to version from here: https://github.com/rancher/charts/pull/3858

### CODE REVIEW

**Review by maxsokolovsky — APPROVED** [review]

**Review by ericpromislow — CHANGES_REQUESTED** [review]
I think because of https://github.com/rancher/rancher/issues/44980 this should bump to `CATTLE_RANCHER_WEBHOOK_VERSION=2.0.9+up0.3.9`

**Comment by kinarashah** [comment]
This PR can now be closed, webhook is updated to v0.3.9-rc1 here -  https://github.com/rancher/rancher/pull/45414.

**Review by ericpromislow — CHANGES_REQUESTED** [review]
This PR is now obsolete.

**Comment by ericpromislow** [comment]
We had to bump to a newer version of webhook to pull in a fix.

**Pull request closed without merging**
