### PR TITLE
fix apigroup for sourcecodecredential

### PR DESCRIPTION
**Pull request by gitlawr**
Address Issue https://github.com/rancher/rancher/issues/16153

### CODE REVIEW

**Comment by alena1108** [comment]
@gitlawr is it going to affect the upgrade?

**Comment by gitlawr** [comment]
No, for these resources we don't use management.cattle.io apigroup in v2.1.0 so these are two outdated and invalid rbac rules

**Comment by orangedeng** [comment]
LGTM

**Comment by qingdi** [comment]
2.1.3 . workless
sourcecodecredentials.project.cattle.io "p-2s4nb-gitlab-microservice" is forbidden: User "u-ckjnbpotf7" cannot get sourcecodecredentials.project.cattle.io in the namespace "u-ckjnbpotf7"

**Comment by gitlawr** [comment]
We haven't backported this fix to 2.1, so it is available in 2.2

**Pull request merged**
