### PR TITLE
Change Active Directory authentication provider logic to work with generic LDAP

### PR DESCRIPTION
**Pull request by Overv**
The Active Directory authentication provider currently assumes that it can bind directly to the username, however this is an Active Directory specific feature. This PR changes the logic to first look up the user by username and only then bind by its DN, which makes the provider compatible with any LDAP server. (See also issue #12729)

As far as user authentication goes, this makes the provider fully compatible with OpenLDAP servers rather than just Microsoft's Active Directory.

### CODE REVIEW

**Comment by tfiduccia** [comment]
@cjellick - Are we not going to provide a separate OpenLDAP auth, like we did in 1.6.  Instead of combining with AD?

**Comment by Overv** [comment]
@tfiduccia @cjellick That would seem like a whole lot of code duplication for no reason to me.

**Comment by cjellick** [comment]
@Overv @tfiduccia yes, we are going to have separate providers for each implementation. So, AD, OpenLDAP, 389 DS, etc will each be their own distinct provider.
But, that doesn't mean they won't share code or have the same backend. The distinction serves a few purposes:
1. When a new provider shows up, it is explicitly clear what it has been tested and verified to work with
2. If a provider _does_ beheave differently from others or the spec, we can tweak the integration for it specifically without impacting others.

In our experience, there has been enough nuanced difference between the providers to warrant this approach.

**Comment by cjellick** [comment]
That said, this PR will still be fine (and a good backdoor way to integration openldap until we can do the official integration). I will review soon

**Comment by Overv** [comment]
Do you have an update on this PR?

**Comment by bensallen** [comment]
We're also interested in this PR or otherwise status of OpenLDAP support. Thanks!

**Comment by cjellick** [comment]
a dedicated open LDAP provider is high on our list. shouldn't be too long

**Comment by strowi** [comment]
also very interested in this. Since our LDAP-Setup which works fine with rancher1.6, doesn't with rancher2/AD.

**Comment by cjellick** [comment]
Its not intended to work with ranchere2/AD @strowi. We are methodically rolling out auth provider support as we explicitly develop, test, and verify each specific backend provider.

**Comment by strowi** [comment]
@cjellick  Ah, good to know.. i will stop trying;) Wasn't clear to me from reading the docs and some issues... (some projects just have 1 auth provider for AD + LDAP). Thx!

**Comment by Overv** [comment]
@strowi You can technically use the vanilla Active Directory plugin with OpenLDAP by using DNs as usernames, but it's not very pretty.

**Comment by cjellick** [comment]
Im going to close this PR. we are working on explicit providers for openLDAP and freeIPA.
I kept this open to see if we could combine the two, but it doesnt look like that is going to happen.
Rest assured: openLDAP support coming soon!

**Pull request closed without merging**
