### PR TITLE
Add workaround for networkmanager

### PR DESCRIPTION
**Pull request by rancher-max**
As documented in https://github.com/rancher/rke2/issues/786

### CODE REVIEW

**Review by sangeethah — DISMISSED** [review]
LGMT

**Review by ShylajaDevadiga — APPROVED** [review]
LGTM

**Comment by Oats87** [comment]
@rancher-max this is not going to work, it needs to use the `flannel` interface name, not the calico standard ones

**Review by Oats87 — CHANGES_REQUESTED** [review]
I think there may need to be a network manager config reload forced as well, I'm not entirely sure how to do this, otherwise the changes won't take effect

**Comment by Oats87** [comment]
I think adding the contents from: https://github.com/rancher/rke2/issues/786

and doing a subsequent restart of NetworkManager would work...

**Review by Oats87 — APPROVED** [review]
LGTM

**Pull request merged**
