### PR TITLE
[v2.7] Updated KubernetesVersion of the provisioningInput

### PR DESCRIPTION
**Pull request by igomez06**
## Problem

In its current implementation it is not possible to run provisioning tests across packages. This is something we do with code coverage runs,

## Solution

 I add inputs for the the different cluster types: rke1, rke2, and k3s in the provisioningInput config entry.

### CODE REVIEW

**Review by caliskanugur — APPROVED** [review]
Looks good to me

**Review by markusewalker — APPROVED** [review]
LGTM

**Comment by igomez06** [comment]
Backport: https://github.com/rancher/rancher/pull/39830

**Review by markusewalker — DISMISSED** [review]

**Comment by igomez06** [comment]
New branch was merged so I had updated this branch again.

**Review by markusewalker — APPROVED** [review]

**Review by caliskanugur — APPROVED** [review]

**Pull request merged**
