### PR TITLE
update cn ami image-id to latest

### PR DESCRIPTION
**Pull request by aiwantaozi**
Issue: https://github.com/rancher/rancher/issues/28317

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks

**Review by rmweir — APPROVED** [review]
Unable to actually validate the AMI's because I don't have access but otherwise LGTM.

**Comment by cbron** [comment]
This was accidentally merged into 2.4-head instead of release/v2.4, can we revert this and re-open against release/v2.4 branch ?  @aiwantaozi

**Comment by cbron** [comment]
We also need the AMI's for 1.18, as that was recently released: https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-kubernetes-version-1-18/

**Pull request merged**
