### PR TITLE
Support Windows with GCE cloud provider

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
Windows worker cannot query GCE metadata

**Solution:**
- Add the metadata accessing route
- Add GCE cloud provider logic
- Adjust `get-hyper-vswitch`

**Issue:**
https://github.com/rancher/rancher/issues/20156

### CODE REVIEW

**Comment by loganhz** [comment]
LGTM

**Comment by cjellick** [comment]
Are you going to write tests for this?
Does this map to any test cases in QA's test plan?
Now that preview is out, we need to see much better automation tests for windows. Can you give me a summary of the tests we have written for windows?

**Comment by loganhz** [comment]
Trying to add validation tests in https://github.com/rancher/rancher/pull/20384 but we are blocked by https://github.com/rancher/rancher/issues/20440

We can merge this PR first and we will continue to work on the automation test

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
