### PR TITLE
Add support for Ingress for k8s 1.22

### PR DESCRIPTION
**Pull request by cmurphy**
## Add compatibility helpers for ingress controllers

This change adds a package called ingresswrapper which provides
utilities that help make controllers able to use either the
extensions/v1beta1 Ingress API or the networking.k8s.io/v1 Ingress API,
depending on the version of the kubernetes API server the controllers
are running on. Kubernetes 1.18 only supports the extensions/v1beta1
Ingress API, while Kubernetes 1.22 only supports the
networking.k8s.io/v1 Ingress API. The compatibility layer defaults to
using the networking.k8s.io/v1 API when it is available.

The wrapper package provides two main helper objects that the
controllers can use. One is the Ingress interface, which is just a
controller-runtime client Object, which itself is a meta interface for
the apimachinery runtime Object and the meta/v1 Object. It allows direct
access to the object's TypeMeta and ObjectMeta data and can be used when
information from the object's Spec field is not needed. The other is the
CompatIngress struct, which inlines the networking.k8s.io/v1/Ingress
struct and provides methods to convert any Ingress object. This is
useful when the actual Spec of an Ingress object is needed. The data
structure is the same as for a networking.k8s.io/v1/Ingress object, so
when support for Kubernetes 1.18 is eventually removed, we should be
able to simply replace `CompatIngress` with `knetworkingv1.Ingress` in
every controller.

The wrapper also provides interfaces and wrapper methods to help with
setting up controllers.

~~## Update project.cattle.io ingress schema~~

~~This change updates the norman ingress store to use the
networking.k8s.io/v1 Ingress API for storing Ingress objects when
possible, and modifies the project.cattle.io schema for Ingress
resources to use the k8s.io/api/networking/v1 package. This also adds
norman mappers to copy fields where needed, such as from
"defaultBackend" to "backend", so that no matter which storage API is
used, the right data exists in the object. See the deprecation guide[1]
for notes on how the fields are translated.~~

~~[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122~~

https://github.com/rancher/rancher/issues/33312

To do:

- [x] Add compatibility wrapper for norman clients (e.g. `IngressLister` and `IngressInterface`)
- [x] Update project.cattle.io [schema](https://github.com/rancher/rancher/blob/d77f618d20e52ec1788918a8cf0323099d896267/pkg/schemas/project.cattle.io/v3/schema.go#L702-L740)
- [x] Unit tests for ingresswrapper
- [x] Squash commits

Areas that need to be tested:

|                     | managementagent/ingress | managementlegacy/globaldns | managementuserlegacy/approuter | managementuserlegacy/endpoints | managementuserlegacy/globaldns | managementuserlegacy/ingresshostgen |
|---------------------|-------------------------|----------------------------|--------------------------------|--------------------------------|--------------------------------|-------------------------------------|
| Local 1.18 - docker |                         |                            |                                |                                |                                |                                     |
| Local 1.22 - docker |                         |                            |                                |                                |                                |                                     |
| Local 1.18 - helm   |                         |                            |                                |                                |                                |                                     |
| Local 1.22 - helm   |                         |                            |                                |                                |                                |                                     |
| Downstream 1.18     |                         |                            |                                |                                |                                |                                     |
| Downstream 1.22     |                         |                            |                                |                                |                                |                                     |

### CODE REVIEW

**Comment by cmurphy** [comment]
I dropped the changes for the project.cattle.io schema, I found it wasn't working on 1.18. I will split it into a separate PR. The controller changes should still work without it.

The project.cattle.io changes should only affect the Ember UI. I'm having a hard time getting it right, and I think it might be safest to not make any changes at all and say that the Ember UI isn't supported for managing ingresses on kubernetes 1.22.

**Review by rmweir — CHANGES_REQUESTED** [review]
Both comments apply to all applicable handlers. @cmurphy @git-ival are there any plans for performance testing this? I think we might want to look at api server metrics and see how much more time is being spent reading and writing ingress objects. Could also look for noticeable cpu spikes.

**Comment by cmurphy** [comment]
I pushed up changes and now github isn't letting me reply directly to comments.

@rmweir

https://github.com/rancher/rancher/pull/35449#discussion_r749782981

> Could the logic contained in sync be put into a single function that accepts the new interface and then we can have two syncs, one for the v1 ingress type and one for the v1beta1 type? That way we don't need to use reflect.ValueOf? The other option may be to do the nil check in the function return by that helper functions CompatSyncV1 and CompatSyncv1Beta1.

`AddHandler` will fail unless the argument matches the controller type, i.e. `workload.Networking.Ingresses("").AddHandler` can only take a sync function whose object argument is type `*knetworkingv1.Ingress`. I also can't move the nil check to the helper function, because in some cases the controller is still supposed to run when the object is nil https://github.com/rancher/rancher/pull/35449/files#diff-cc012132def2a0d86b41b1ac06f83f0529ac56047437405c83a216db3497ce0cL23-L28

https://github.com/rancher/rancher/pull/35449#discussion_r749814127

> In situations like this where we know we are only reading from the object and this is the only operation we are doing with the Ingress object, can we just use compat in the parent function. Here we could use it in the sync handler and then pass it own into at least generateExpectedServices and calls of generateNewService.

I've added this here and a few places where it makes sense.

https://github.com/rancher/rancher/pull/35449#pullrequestreview-806674667

> are there any plans for performance testing this?

We haven't made specific plans yet. The conversion logic will inevitably have performance overhead. At least we'll be able to remove it once we drop support for 1.18.

**Comment by kinarashah** [comment]
@rmweir can't merge changes since changes were requested, could you approve and discuss more with @cmurphy on the issue/another PR? we need this to unblock https://github.com/rancher/rancher/pull/35357

**Review by rmweir — APPROVED** [review]
Approved for merge with feedback to possibly be addressed after.

**Pull request merged**
