### PR TITLE
v2.7 Rancher forward port from 2.7.4

### PR DESCRIPTION
**Pull request by pjbgf**

### CODE REVIEW

**Review by macedogm — CHANGES_REQUESTED** [review]
@pjbgf we also need to bump:

1. https://github.com/rancher/rancher/blob/release/v2.7/package/Dockerfile#LL174C3-L174C3 to `1.1.10` -> https://github.com/rancher/rancher/pull/41690/files#diff-c55d1ee74f32cd4b9eeeceaec981a180f52e761acb158a5b0b0e088c7725c9caR170
2. https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L112 to `1.1.10` -> https://github.com/rancher/rancher/pull/41690/files#diff-b2f1f4f0c50b7452d729bccde70315eb06368408c5062c97febbe7dd6f87e2edR112

I'm unsure about these, but I guess they will be reviewed by the release captain when the next release happens:

1. https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L202
2. https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L217

**Comment by pjbgf** [comment]
@macedogm thank you for the review, I have now added your suggestions. PTAL

As for the additional points, I am really not sure as well - especially the second one.

**Comment by macedogm** [comment]
> @macedogm thank you for the review, I have now added your suggestions. PTAL
> 
> As for the additional points, I am really not sure as well - especially the second one.

Thanks! LGTM

Regarding:

> I'm unsure about these, but I guess they will be reviewed by the release captain when the next release happens:
>
> https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L202
> https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L217

Giving that this is how they are in `release/v2.7`, let's keep them as they are.

**Review by macedogm — APPROVED** [review]

**Review by maxsokolovsky — COMMENTED** [review]
Comparing the commits with those in this PR https://github.com/rancher/rancher/pull/41690.

Looks like you're keeping the UI bump commits out of this one, which makes sense.

But noticing also that the https://github.com/rancher/rancher/pull/41690/commits/94495894b08a5c509c7d6637c77e0ec3f43fc4fe commit is missing here.

**Review by maxsokolovsky — APPROVED** [review]

**Review by macedogm — APPROVED** [review]

**Pull request merged**
