### PR TITLE
[2.8] Update Provisioning Input & Release Upgrade fields'  tags and Support OS & Upgrade HA Jenkinsfiles

### PR DESCRIPTION
**Pull request by caliskanugur**
## Problem

- Because of multiple unmarshal and marshal while updating the generating configuration, glue codes are generating zero value fields, causing some nil checks in the tests to pass. 
- Support matrix OS can't point to different branches and repos.
- Release upgrade HA's last step is dependent on generated patched configs rather than initial configurations, this was causing not to provision the new clusters on the upgraded version if the initial cluster provision failed.
 
## Solution

- Added omit empty tags to provisioning input fields
- Updated support OS matrix and release HA upgrade Jenkinsfiles' repo logics to unify with e2e Jenkinsfile.
- Updated release upgrade HA's last loop to use the initially generated configuration files. 
- Updated release upgrade HA configuration matrix fields to have JSON tags

 
### Automated Testing

* Test types added/modified:
    * Validation (Go Framework)

### CODE REVIEW

**Comment by caliskanugur** [comment]
Forgot to add branches initially, added branch params that are passing to downstream jobs in the support OS matrix.

**Review by igomez06 — APPROVED** [review]
LGTM

**Review by markusewalker — APPROVED** [review]
LGTM

**Review by slickwarren — APPROVED** [review]
lgtm

**Review by izaac — DISMISSED** [review]
I've approved the 2.7. I missed this one.

**Comment by caliskanugur** [comment]
Added JSON tags to release upgrade fields, which are now necessary because of the new yaml package that the config package uses. Rebased. Should be ready for another round.

**Review by igomez06 — APPROVED** [review]
LGTM

**Comment by caliskanugur** [comment]
Backport: https://github.com/rancher/rancher/pull/43087

**Review by markusewalker — APPROVED** [review]
LGTM

**Pull request merged**
