### PR TITLE
[2.6] Add airgap setup support to the validation charts tests

### PR DESCRIPTION
**Pull request by caliskanugur**
- [x] This PR relies on #39342. And requires updates according to the changes.

**Extensions Updates:**

- Implemented:
  - Default registry and server URL IDs and their values for each of the chart install and update functions
- Refactored:
  - Payload options for each of the charts and the payload options struct to contain the default registry
  - Removed unnecessary double error checks in charts cleanups
  - Gatekeeper zero-value maps

**Tests Updates:**

- Implemented:
  - Istio P0 case Monitoring and Istio charts installation checks
  - Readme for the configuration
- Refactored:
  - Some Istio assertions
  - Removed an unnecessary monitoring helper
  - Gatekeeper typos
  - Moved Istio example application to the resources directory
  - Private helpers error throwing with errors package

### CODE REVIEW

**Review by nataliefyi — DISMISSED** [review]
LGTM

**Comment by caliskanugur** [comment]
Updated the v1 steve client changes.

**Review by igomez06 — APPROVED** [review]
Looks Good!

**Review by izaac — APPROVED** [review]
LGTM

**Review by nataliefyi — APPROVED** [review]
LGTM

**Pull request merged**
