### PR TITLE
Adding rbac test suite to validate cluster owner & cluster member use cases for v1 endpoints

### PR DESCRIPTION
**Pull request by anupama2501**
Addresses the test cases listed in https://github.com/rancher/qa-tasks/issues/380

Cluster Owner
1.  Standard user cannot list downstream cluster
2.  Cluster owner can list the downstream cluster
3.  Cluster owner should be able to assign members to the cluster
4.  Cluster owner should be able to list projects the user does not own
5.  Cluster owner should be able to list namespaces the user does not own
6.  Cluster owner should be able to create namespaces in Projects the user does not own
7.  Cluster owner should be able to create Projects in the cluster

Cluster Member

1. Cluster member owner can list the downstream cluster --> v1 call
2. Cluster member should NOT be able to list projects the user does not own --> v1 call
3. Cluster member should NOT be able to list namespaces the user does not own --> v1 call
4. Cluster member should NOT be able to create namespaces in Projects the user does not own --> v1 call
5. Cluster member should be able to create Projects in the cluster --> v1 call

In addition to the above, following test cases are addressed as well:

1. Deleting namespace as a cluster owner
2. Deleting project as a cluster owner

### CODE REVIEW

**Comment by anupama2501** [comment]
Waiting on a few changes to go in before this gets merged worked upon by @igomez06 to the object clusterlist from rancher as not being k8s compatible.

**Comment by igomez06** [comment]
> Waiting on a few changes to go in before this gets merged worked upon by @igomez06 to the object clusterlist from rancher as not being k8s compatible.

This PR needs to be approved beforehand https://github.com/rancher/rancher/pull/38281

**Comment by slickwarren** [comment]
@anupama2501 can you review the conflict and revisit this now that the dependent PR has merged?

**Comment by anupama2501** [comment]
Since this needs new changes from Israel's PR, will add in the required ones and re add reviewers.

**Comment by anupama2501** [comment]
Closing this PR. opening a new one.

**Pull request closed without merging**
