### PR TITLE
Bump Go to 1.22.7

### PR DESCRIPTION
**Pull request by tomleb**
### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

### CODE REVIEW

**Comment by macedogm** [comment]
@tomleb might also be good to bump https://github.com/rancher/rancher/blob/main/hack/airgap/go.mod#L3 if possible, please.

**Comment by tomleb** [comment]
@macedogm Just realized the airgap script is using `go` directive, not `toolchain`. Should I add a toolchain directive in there or we keep it as is?

**Comment by macedogm** [comment]
@tomleb I believe that we should add the `toolchain` directive to keep it in line with the rest.

**Comment by tomleb** [comment]
Closing since right now the toolchain is not being used at all (due to the image having GOTOOLCHAIN=local). We just need to wait for latest BCI image to be updated..

**Pull request closed without merging**
