### PR TITLE
Added abiity to drop componentstatuses based on additional annotation

### PR DESCRIPTION
**Pull request by ibrokethecloud**
During the import of managed k8s clusters, such as AKS, the component status fails because scheduler and controller-manager cs are not valid.

This cause the Rancher dashboard to show a red warning in the main dashboard page.

For certain customers who are only using managed k8s clusters, this can send the wrong message every time they login to the rancher ui.

The tweak allows users to specify a new annotation in the Rancher UI during the process to create "import cluster" type clusters.

An annotation of the form:

`lifecycle.cattle.io/ignorecslist: scheduler, controller-manager`

Will cause the healthsyncer controller to drop the CS for scheduler and controller-manager.

This will default the UI to drop the error and show a healthy cluster.

Ideally the cs for missing components should be greyed out but this will need a UI fix.

Related issue: https://github.com/rancher/rancher/issues/24203

### CODE REVIEW

**Review by mrvarmazyar — COMMENTED** [review]
Supposedly it needs to assignee to someone in rancher team, I've just tested it, and it works fine!

**Comment by mohag** [comment]
There is [this deprecation of the API](https://github.com/kubernetes/kubernetes/pull/93570) as well:

**Comment by Eric-Fontana-Tjx** [comment]
Bump - Why is this not merged, it looks REALLY bad for Rancher when you import AKS clusters.   Need this ASAP.

**Comment by mohag** [comment]
This would be a nice option to fix the kubeadm clusters showing broken as well

**Comment by ibrokethecloud** [comment]
2.6.x handles this. Closing this issue as its not needed.

**Comment by mohag** [comment]
In 2.6, they still show broken on a kubeadm cluster (which disables the HTTP port which is used by componentstatuses)
image

**Pull request closed without merging**
