### PR TITLE
Stop deploying agent in planner after agent is deployed

### PR DESCRIPTION
**Pull request by thedadams**
Issue: https://github.com/rancher/rancher/issues/37465

## Problem
The RKE2 planner would include the manifest for the cluster agent in the
plan for a node. This causes the cluster to go into an updating state on
Rancher upgrade, which is unexpected.

## Solution
After this change, the planner will not include the cluster agent
manifest file. Instead, the cluster agent will be deployed via a periodic 
instruction that is only included until the cluster agent is deployed.

## Testing
Updating Rancher and rancher-agent with deployed RKE2 clusters.

### CODE REVIEW

**Review by Oats87 — CHANGES_REQUESTED** [review]
Clarification around the desired behavior of the K3s/RKE2 deploy-controller needs to be made before this can be merged, as originally the intention was to allow for deleting manifests from a cluster by "blanking" a manifest file in the `/var/lib/<runtime>/server/manifests`. From a quick test, this does not appear to work today; however, we don't want to have future versions of K3s/RKE2 suddenly start behaving in this way and causing inadvertent orphaning of downstream clusters through deletion of the `cattle-cluster-agent` deployment.

@briandowns @galal-hussein @brandond if you folks have any insight into this, that would be much appreciated.

**Comment by thedadams** [comment]
An issue has been create in the K3S repo: https://github.com/k3s-io/k3s/issues/5559
And a PR has been submitted to fix the issue pointed out by Chris: https://github.com/k3s-io/k3s/pull/5560

**Comment by brandond** [comment]
Sounds like a reoccurrence of https://github.com/rancher/wrangler/issues/195

**Comment by thedadams** [comment]
The approach of this solution has changed and the k3s issue is no longer apart of the discussion.

**Comment by thedadams** [comment]
The current implementation of this solution is to include a periodic instruction with the plan until the `AgentDeployed` condition is true. This periodic instruction will check for the `cattle-cluster-agent` deployment in the `cattle-system` namespace. If the deployment doesn't exist, then it will try to create it (and not erroring if it is unsuccessful). Once the deployment is created, the periodic instruction will still run for a little bit, but won't try to overwrite the deployment. This is because Rancher's controllers will redeploy the agent as expected and this instruction shouldn't overwrite it.

The only iffy part of this implementation is dealing with clusters upgraded from v2.6.5 to v2.6.6. These older clusters will have the cluster-agent manifest saved to the manifest directory. In order to avoid RKE2/K3S redeploying these old manifests from the directory when the `rke2-server` service is restarted, then files should be deleted. This is done through a one-time instruction.

Right now, this one-time instruction is included with all control plane plans after the agent is deployed, forever. This is to ensure that the file is properly cleaned up. Personally, I wish there was some other way to clean this file up. The other possible solutions that I can think of for this would require significant changes (like updating the plan to delete the file on Rancher upgrade and pausing the `planner` until this plan is successfully applied by the system-agent). I am open to discussion and suggestion on how to make this second part better (and the first part above, but I feel much better about that).

**Comment by thedadams** [comment]
Closing in favor of another implementation.

**Pull request closed without merging**
