### PR TITLE
fix invalied full path of alias path

### PR DESCRIPTION
**Pull request by whywaita**
This PR fix saved the path of SSH private key.

### before
- when devMode, save under 
  - key save under tempfile (`/tmp/~~~`)
  - config save under tempfile (`/tmp/~~~`)
- when not devMode (no option)
  - key save under jail (`/opt/jail/~~~`)
  - config save under root (`/~~~`)

### after
- when devMode
  - key save under tempfile (`/tmp/~~~`)
  - config save under tempfile (`/tmp/~~~`)
- when not devMode (no option)
  - key save under jail (`/opt/jail/~~~`)
  - config save under root (`/opt/jail/~~~`)

### CODE REVIEW

**Comment by whywaita** [comment]
Hi, contributors!

Sorry, I don't understand why to fail CI.
What should I do?

**Comment by dramich** [comment]
@whywaita The build is failing because this change is causing the tests to fail. This change is not correct as it would put the full path including the jail, for every file which is not the intended behavior. Do you have an issue this is related to?

**Comment by whywaita** [comment]
sorry, I don't make related issue yet 🙇 

when not devMode, `config[driverField]` is not a correct file path. (like `/~~~`), correct path is under jail (`/opt/jail/~~~`).

**Comment by whywaita** [comment]
@dramich fix test 💪 

please check me again 🙏

**Comment by dramich** [comment]
@whywaita This change will break a real Rancher container. Dev mode is to enable local development and pathing of files and their locations. When not running in dev mode docker-machine is executed within a 'jail' which is why the path changes based off the dev mode flag. When running inside the jail docker-machine can not see the path for the tmp dir of the system as we build a new root using chroot which is why the files path given to the docker-machine command line args have `/` as the beginning of the path. We are writing these files to the base of the jail dir as seen by docker-machine.

**Comment by whywaita** [comment]
I fixed this problem, The reason is https://github.com/rancher/rancher/issues/20721 🙇 .

I will close this PR 🙇

**Pull request closed without merging**
