### PR TITLE
Updates for k8s v1.26

### PR DESCRIPTION
**Pull request by vardhaman22**
Issue: https://github.com/rancher/rancher/issues/41113

- update cluster-api to `v1.2.12` (no changes for `pkg/crds/provisioningv2` crds) 
- updated HPA from v2beta2 to v2, `v2beta2` is deprecated with k8s 1.26. Lowest available version is v1.22 so we're good with versions we support >= v1.23 
- updated k3s local version to `v1.26.4` 
- updated RKE to `v1.4.6-rc2` (has new k8s v1.26.4) 

Note: we could not bump other k8s dependencies because of conflict with cluster-api which is still on k8s 1.25 in go.mod
 
### Manual Testing

**RKE1** 
- created a custom image with the PR changes 
- KDM url pointing to `dev-v2.7` which has v1.26 changes merged
- provisioned v1.26.4-rancher2-1 and v1.25.9-rancher2-1 cluster successfully with all three CNIs calico, canal and flannel 
- upgraded cluster from `v1.25.9-rancher2-1` to `v1.26.4-rancher2-1`

**RKE2/k3s**
- created a custom image with the PR changes 
- KDM url pointing to custom URL having v1.26 RKE2/k3s changes https://github.com/rancher/kontainer-driver-metadata/pull/1135 
- provisioned `v1.26.4+rke2r1` and `v1.26.4+k3s1` cluster successfully with 3 nodes, one node per role 
 
 **Local cluster** 
- Both tests above were with local cluster `v1.26.4+k3s1` single node docker install 

### Automated Testing

**RKE1**
- Covers standalone provisioning cases that have been tested through CI, see https://github.com/rancher/rke/pull/3237 for more details

**RKE2** 
- Covers provisioning tests that will run in drone with `v1.26.4+k3s1`

 **Local cluster** 
- PR updates embedded local k3s cluster to `v1.26.4+k3s1`

### CODE REVIEW

**Review by kinarashah — CHANGES_REQUESTED** [review]
@vardhaman22 I know this was there in previous PR so maybe it’s just a matter of bringing it here but we need to 
- bump k3s version 
- change kubeVersion in chart.yml 
- update CRDs for capi

**Comment by kinarashah** [comment]
@vardhaman22 Apologies, looks like CRDs haven't been updated upstream for CAPI v1.2.12 so ignore the first point. https://github.com/kubernetes-sigs/cluster-api/tree/v1.2.8/config/crd/bases vs https://github.com/kubernetes-sigs/cluster-api/tree/v1.2.12/config/crd/bases

**Comment by vardhaman22** [comment]
> @vardhaman22 I know this was there in previous PR so maybe it’s just a matter of bringing it here but we need to
> 
> * bump k3s version
> * change kubeVersion in chart.yml
> * update CRDs for capi

done please review.

**Review by jiaqiluo — DISMISSED** [review]
LGMT

**Review by jiaqiluo — APPROVED** [review]
LGTM. It looks like bumping the RKE module is the only change since the previous approval.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
