### PR TITLE
Support run kube-proxy on Windows with AWS cloud provider

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
Cannot run kube-proxy on Windows with AWS cloud provider if doesn't
indicate the AWS instance internal name.

**Solution:**
Set `hostname-override` on agent side

**Issue:**
https://github.com/rancher/rancher/issues/20185

### CODE REVIEW

**Comment by loganhz** [comment]
LGTM

**Comment by cjellick** [comment]
Are you going to write tests for this?
Does this map to any test cases in QA's test plan?
Now that preview is out, we need to see much better automation tests for windows. Can you give me a summary of the tests we have written for windows?

**Comment by loganhz** [comment]
Trying to add validation tests in https://github.com/rancher/rancher/pull/20384 but we are blocked by https://github.com/rancher/rancher/issues/20440

We can merge this PR first and we will continue to work on the automation test

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
needs rebased

**Comment by thxCode** [comment]
@cjellick rebased

**Pull request merged**
